### DISCUSSION TITLE
How to config clusterReadOnlyRole in version > 7.1.x

### DISCUSSION THREAD

**Discussion by will4j** [kubernetes/dashboard#8802] [Q&A]
Is there Easy ways to config clusterReadOnlyRole with kubernetes-dashboard 7.1.x, without external reverse proxy.

I have tried to create cluster readonly role, sc, rb myself like it in version helm chart 6.x.
then create service-account-token secret and use kong plugin request-transformer to add header Authorization: Bearer.

The only way I found successful was change kong gateway configmap as below:
```yaml
- name: api
        host: {{ template "kubernetes-dashboard.fullname" . }}-{{ .Values.api.role }}
        port: 8000
        protocol: http
        routes:
          - name: api
            paths:
              - /api
            strip_path: false
          - name: metrics
            paths:
              - /metrics
            strip_path: false
        plugins:
          - name: request-transformer
            config:
              add:
                headers:
                  - "Authorization: Bearer xxxx"
```
also tried to use annotations konghq.com/plugins but it seems not work
```yaml
kind: Service
apiVersion: v1
metadata:
  labels:
    {{- include "kubernetes-dashboard.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "kubernetes-dashboard.name" . }}-{{ .Values.api.role }}
    app.kubernetes.io/version: {{ .Values.api.image.tag }}
    app.kubernetes.io/component: {{ .Values.api.role }}
  annotations:
   #  KongPlugin kubernetes-dashboard-readonly-auth has been created
    konghq.com/plugins: kubernetes-dashboard-readonly-auth
```

both these ways need hard code or change the helm charts resource, any better ideas ?
