### DISCUSSION TITLE
Blank page for K8s-dasboard UI

### DISCUSSION THREAD

**Discussion by redshadeaux** [kubernetes/dashboard#9166] [Q&A]
I upgraded to the 7.5.0 release of the helm chart for the k8s-dashboard. I am seeing an issue where, when loading the webpage for the UI in my browser, I am met with an empty page. No errors or anything like that showing either. I expected to see a login page where I can supply a token.

Has anyone else had this problem upgrading from 6.x.x to 7.5.0? Any help would be greatly appreciated!

**Comment by floreks** [comment]
1. It requires a clean install.
2. There is a new way of accessing the Dashboard since 7.0.0. Check the README.

**Reply by redshadeaux** [reply]
I have already done a clean install. 

I don't see the new method of accessing the dashboard listed in the README. I have a separate host name set up to access the dashboard rather than the local host.

**Reply by floreks** [reply]
Dashboard now uses kong as api gateway. You have to point to it instead of Dashboard web.

https://github.com/kubernetes/dashboard/blob/master/docs%2Fuser%2Faccessing-dashboard%2FREADME.md

**Reply by redshadeaux** [reply]
I see. I read that part and saw that the dashboard now uses kong as an API gateway. However, how would I point to it when using the ingress provided in the helm chart? 
I have the ingress enabled and a couple parameters defined such as annotations, ingress class name, and hosts. I currently have a custom host provided in the helm chart under app.ingress.hosts and would like to be able to reach the dashboard UI from there. Do I need to introduce a new annotation or provide a new host name?

**Reply by redshadeaux** [reply]
Hey, just wanted to know if there was anything else that should be looked at to resolve this. Would creating an issue from this discussion be better? Still facing the same issue.

**Reply by floreks** [reply]
If you are using our helm chart it should work. To be sure you can provide exact steps, values and the way you are trying to access Dashboard.

This is most likely a configuration issue, not related to the application itself so creating an issue won't help since we do not provide support via issues.

**Reply by redshadeaux** [reply]
Yes I am using your official helm chart. Sure, I can provide that information. I also thought it was a configuration issue however I might be missing something obvious or perhaps something I don't fully understand with the new changes introduced. 
These are the values that I am supplying to the helm chart:
```yaml
app:
  ingress:
    enabled: true
    useDefaultAnnotations: false
    issuer:
      scope: disabled
    annotations:
      alb.ingress.kubernetes.io/backend-protocol: HTTPS
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:676117500464:certificate/08617f1e-230b-44d2-9cff-275f178eaab7
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: 5
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: 4
      alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true
      alb.ingress.kubernetes.io/security-groups: sg-03452c58d507822b8
      alb.ingress.kubernetes.io/ssl-redirect: 443
      alb.ingress.kubernetes.io/subnets: subnet-0cca458eb809c2747,subnet-08f312e743108d54f
      alb.ingress.kubernetes.io/target-type: ip
    ingressClassName: alb-ingress-class
    hosts:
      - kubernetes-dashboard.example.kube
``` 

I am trying to access the dashboard at the host listed above `https://kubernetes-dashboard.example.kube`.

As for steps, I am just deploying the helm chart via an ArgoCD app and supplying the values to override within the app. 

If there is any other information I can provide, please let me know. Thank you for your help!
