### DISCUSSION TITLE
Getting "400 Bad Request The plain HTTP request was sent to HTTPS port" when trying to access dashboard UI in browser

### DISCUSSION THREAD

**Discussion by maisam94** [kubernetes/dashboard#9185] [Q&A]
I upgraded to the 7.5.0 release of the helm chart for the k8s-dashboard. I am getting "400 Bad Request
The plain HTTP request was sent to HTTPS port"  when loading the webpage for the UI in my browser. 
I expected to see a login page where I can supply a token.

I did clean installation for the new helm chart with  ingress enabled and a couple parameters defined such as annotations, ingress class name, host and lets-encrypt for ssl connection, but when trying to access the dashboard UI in my browser, I got "400 Bad Request ..."

These are the values that I am supplying to the helm chart:
```
app:
  ingress:
    useDefaultAnnotations: false
    enabled: true
    annotations:
      ingress.kubernetes.io/force-ssl-redirect:  'true'
      konghq.com/strip-path: 'true'
    ingressClassName: kong
    hosts:
      - k8s-new.app.xxx.com
    secretName: kubernetes-dashboard-tls
    issuer:
      name: letsencrypt-prod
    host: k8s-new.app.xxx.com


kong:
  enabled: true
  ingressController:
    enabled: true
  proxy:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```
 I would like to be able to reach the dashboard UI from outside the cluster via Https protocol with custom host.
so what should be configured or how would I point to kong proxy when using the ingress provided in the helm chart?

If there is any other information I can provide, please let me know. Thank you for your help!
