### ISSUE TITLE
`app.ingress.path` does not work

### ISSUE THREAD

**Issue by The-Judge** [kubernetes/dashboard#10071]
### What happened?

Setting `app.ingress.path` to something else than '/' results in a rewrite-target annotation for the ingress.
The Browser, however, is always redirected to `{URL}/#/`.

This is the values.yaml I use:

```yaml
---
app:
  ingress:
    enabled: true
    hosts:
      - k8sdb-20-113-189-65.nip.io
    ingressClassName: nginx
    path: /k8sdb

    tls:
      enabled: true
    issuer:
      name: letsencrypt-http-prod
      scope: cluster
```

### What did you expect to happen?

The Dashboard should be accessible at https://k8sdb-20-113-189-65.nip.io/k8sdb/ instead of redirecting to https://k8sdb-20-113-189-65.nip.io/#/ .

### How can we reproduce it (as minimally and precisely as possible)?

Just deploy the Dashboard with the values.yaml provided with k8sdb-20-113-189-65.nip.io replaced by an actual endpoint of your test environment and TLS setup matching your Cluster.

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

7.11.1

### Kubernetes version

1.30.5
