### ISSUE TITLE
Can not authenticate to dashboard using kubernetes/ingress-nginx

### ISSUE THREAD

**Issue by red-lichtie** [kubernetes/dashboard#10108]
### What happened?

When using Ingress https://github.com/kubernetes/ingress-nginx I get the error message

`Unknown error (200): Http failure during parsing for https://kubernetes-dashboard.svc.internal/#/login`

Should I be using "kubernetes-dashboard-kong-proxy:kong-proxy" or "kubernetes-dashboard-web:web" in the Ingress? I have tried both and neither works.

Why isn't there a "Here is how to configure a standard Ingress with our service" example?

Search for it, there are hundreds of answers, ranging from "use --enable-skip-login" (no longer supported) to "try changing all these parameters".

Why isn't there a decent "Here is how to use Ingress with our Service" ?

The description and screen shots look brilliant, the big issue is, I can't load the application.

You could say it is a "support issue" but I would say it is a documentation and example issue.

Even "Accessing Dashboard" is separate from "Access control", why?

Should I just be using Kong? No idea, I don't use Kong in my cluster.

I don't want to use `kubectl port-forward` or `kubectl proxy`, I want to use a standard k8s Ingress.

### What did you expect to happen?

I expected the token that was generated by `kubectl -n kubernetes-dashboard create token dashboard-admin` to work.

### How can we reproduce it (as minimally and precisely as possible)?

Go to the service, try to access it and get rejected with a 200 (200 = OK, right? HUH?).

### Anything else we need to know?

ingress.yaml
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
  annotations:
    cert-manager.io/cluster-issuer: myissuer
spec:
  tls:
    - hosts:
        - kubernetes-dashboard.svc.internal
      secretName: kubernetes-dashboard-cert
  rules:
    - host: kubernetes-dashboard.svc.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard-kong-proxy
                port:
                  name: kong-proxy
...
```

values.yaml
```yaml
app:
  ingress:
    enabled: false
kong:
  proxy:
    type: ClusterIP
    http:
      enabled: true
api:
  containers:
    args:
      - '--disable-csrf-protection=true'
```

### What browsers are you seeing the problem on?

Others

### Kubernetes Dashboard version

7.11.1

### Kubernetes version

v1.29.0
