### ISSUE TITLE
Kubernetes Dashboard does not accept Authorization: Bearer token even when passed via Ingress Reverse Proxy

### ISSUE THREAD

**Issue by venkatsunil5** [kubernetes/dashboard#10242]
### What happened?

I have using Kubernetes Dashboard v7.13.0 behind an OAuth2 Proxy (via NGINX Ingress and Kong gateway). The OAuth2 proxy correctly authenticates the user and responds with an Authorization: Bearer <token> header. The ingress is configured with annotations to forward this header to the Kubernetes Dashboard.

Despite successful authentication and the presence of the bearer token in the ingress response (verified via /oauth2/auth returning 202 and including the Authorization header), the dashboard still prompts for manual token input on the login screen.

However we suspect Kong is either stripping or not receiving the Authorization header, as the token is not visible in Kong logs or the requests reaching the dashboard. Even with nginx.kubernetes.io/auth-response-headers and other annotations configured, the dashboard does not detect the token.

dashboard-ingress.yaml annotations:

```
    annotations:
      #konghq.com/plugins: "preserve-auth-header"
      nginx.ingress.kubernetes.io/auth-url: "https://<host>/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://<host>/oauth2/start?rd=https://$host$request_uri"
      nginx.ingress.kubernetes.io/auth-response-headers: >-
        X-Auth-Request-Email,X-Auth-Request-Preferred-,X-Auth-Request-Access-Token,
        X-Auth-Request-Roles,X-Auth-Request-User,X-Auth-Request-Groups,X-Forwarded-Groups,
        Authorization
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/rewrite-target: "/"
      nginx.ingress.kubernetes.io/proxy-buffers: "4 512k"
      nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "512k"
```

oauth2-proxy configs:

```
        --set config.clientID="xxxxxx" \
	--set config.clientSecret="xxxxxxx" \
	--set config.cookieSecret="xxxxxxxxx" \
        --set image.repository="docker.io/oauth2-proxy/oauth2-proxy" \
        --set image.tag="v7.9.0" \
        --set extraArgs.provider="oidc" \
        --set extraArgs.azure-tenant="xxxxxxxxxx" \
        --set extraArgs.oidc-issuer-url="https://login.microsoftonline.com/xxxxxxxxxx/v2.0" \
        --set extraArgs.redirect-url="https://<host>/oauth2/callback" \
        --set extraArgs.scope="openid profile email offline_access" \
        --set extraArgs.email-domain="*" \
        --set extraArgs.upstream="https://kubernetes-dashboard-kong-proxy.kubernetes-dashboard.svc.cluster.local:443" \
        --set extraArgs.whitelist-domain="xxxxxxxx" \
        --set extraArgs.cookie-domain=".cloud.xxx.net" \
        --set extraArgs.cookie-csrf-expire="59m" \
        --set extraArgs.cookie-csrf-per-request=true \
        --set extraArgs.cookie-expire="1h" \
        --set extraArgs.cookie-refresh="59m" \
        --set extraArgs.cookie-secure=true \
        --set extraArgs.cookie-name="_oauth2_proxy_csrf" \
        --set extraArgs.reverse-proxy=true \
        --set extraArgs.set-authorization-header=true \
        --set extraArgs.pass-authorization-header=true \
        --set extraArgs.pass-access-token=true \
        --set extraArgs.show-debug-on-error=true \
        --set extraArgs.ssl-upstream-insecure-skip-verify=true \
        --set extraArgs.ssl-insecure-skip-verify=true \
        --set extraArgs.skip-auth-strip-headers=false \
        --set extraArgs.pass-user-headers=true \
	--set extraArgs.pass-host-header=true \
        --set extraArgs.set-xauthrequest=true \
        --set extraArgs.skip-provider-button=true \
        --set extraArgs.skip-jwt-bearer-tokens=true \
        --set ingress.enabled=true \
        --set ingress.className="nginx" \
        --set ingress.path="/oauth2" \
        --set ingress.hosts[0]="<host>" \
        --set ingress.annotations."nginx\.ingress\.kubernetes\.io/proxy-buffer-size"="256k" \
        --set ingress.annotations."nginx\.ingress\.kubernetes\.io/proxy-body-size"="5000m"
```

### What did you expect to happen?

- If a valid Authorization: Bearer <token> header is present on the request reaching the dashboard, it should automatically log in the user
- The dashboard should recognize the token and not prompt for manual token entry
- The behavior should be consistent with OAuth2 proxy + reverse proxy flows as suggested in the documentation and community discussions

### How can we reproduce it (as minimally and precisely as possible)?

- Deploy Kubernetes Dashboard v7.13.0 using the official Helm chart
- Use OAuth2 Proxy with --reverse-proxy, --set-xauthrequest, --pass-authorization-header, and --pass-access-token
- Use NGINX Ingress with annotations as shown above
- Route ingress backend to the kubernetes dashboard via a Kong proxy service
- Login via OAuth2 proxy works and returns 202 with Authorization: Bearer token
- Dashboard still shows manual token login instead of using the bearer token
- No Authorization header seen in the request headers or logs

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

v7.13.0

### Kubernetes version

Client Version: v1.30.3 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.30.4

**Comment by venkatsunil5** [comment]
EDIT: Upon enabling the verbose on the dashboard components, I see that the bearer token is reaching the dashboard but dashboard is rejecting the token and hence resulting in 401 Unauthorized. OIDC is enabled on our aks cluster and api-server is reachable. What is that we are missing here? Please shed some inputs!

**Comment by oskarm93** [comment]
```
--set extraArgs.scope="openid 6dae42f8-4368-4678-94ff-3960e28e3630/.default" \
```
This will send `X-Auth-Request-Access-Token` header to the dashboard with correct JWT. However, I still haven't figured out how to rename the header from `X-Auth-Request-Access-Token` to `Authorization`. You cannot take `Authorization` header straight from the oauth2 proxy as it has the wrong scope. Perhaps use `auth-snippet` annotation on nginx ingress?

**Comment by pierluigilenoci** [comment]
Probably related: https://github.com/oauth2-proxy/manifests/issues/348

**Comment by pierluigilenoci** [comment]
Probably related: https://github.com/kubernetes/dashboard/issues/10103

**Comment by Joseph-Wagner-Frequentis** [comment]
Stuck here with the same problem ... how can just a simple thing be so complicated and broken for such a long time ?

**Comment by SergeSpinoza** [comment]
Hi! This is the solution that worked for me (I tested it with oauth dex), maybe it helps anyone.

1. Install kubernetes-dashboard version 7.14.0 from the default installation using helm in the namespace `system-services` (i.e., I didn't make any changes to values.yaml and didn't include ingress in values.yaml).
2. Next, I applied the manifests that create the oauth-proxy deployment, secret, service, and ingress for kubernetes-dashboard oauth-proxy (but don't forget to change the variables oidc-id, oidc-secret, cookie-secret, DASHBOARD.DOMAIN.PRINT.HERE, DEX.DOMAIN.PRINT.HERE, and ssl-cert-chain-tls to your own values):

```
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard-oidc-creds
  namespace: system-services
type: Opaque
stringData:
  oidc-id: "dex-k8s-auth"
  oidc-secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  cookie-secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard-oauth2-proxy
  name: kubernetes-dashboard-oauth2-proxy
  namespace: system-services
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kubernetes-dashboard-oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: kubernetes-dashboard-oauth2-proxy
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:latest
          imagePullPolicy: IfNotPresent
          args:
            - --provider=oidc
            - --provider-display-name="Dex SSO"
            - --scope=openid profile email groups
            - --redirect-url=https://DASHBOARD.DOMAIN.PRINT.HERE/oauth2/callback
            - --oidc-issuer-url=https://DEX.DOMAIN.PRINT.HERE
            - --oidc-email-claim=email
            - --oidc-groups-claim=groups
            - --cookie-secure=false
            - --email-domain=*
            - --upstream=https://kubernetes-dashboard-kong-proxy:443
            - --http-address=0.0.0.0:4180
            - --pass-access-token=true
            - --pass-authorization-header=true
            - --pass-user-headers
            - --ssl-upstream-insecure-skip-verify=true
          env:
          - name: OAUTH2_PROXY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: kubernetes-dashboard-oidc-creds
                key: oidc-id
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: kubernetes-dashboard-oidc-creds
                key: oidc-secret
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: kubernetes-dashboard-oidc-creds
                key: cookie-secret
          ports:
            - containerPort: 4180
              protocol: TCP
      serviceAccountName: kubernetes-dashboard-api
      nodeSelector:
        "kubernetes.io/os": linux
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard-oauth2-proxy
  name: kubernetes-dashboard-oauth2-proxy
  namespace: system-services
spec:
  ports:
    - name: kubernetes-dashboard-oidc-port
      port: 4180
      targetPort: 4180
  selector:
    k8s-app: kubernetes-dashboard-oauth2-proxy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-dashboard-oauth2-proxy
  namespace: system-services
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/use-http2: 'true'
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  tls:
    - hosts:
        - https://DASHBOARD.DOMAIN.PRINT.HERE
      secretName: ssl-cert-chain-tls
  rules:
    - host: https://DASHBOARD.DOMAIN.PRINT.HERE
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: kubernetes-dashboard-oauth2-proxy
                port:
                  number: 4180

```

Then I create RoleBinding for user, authorized via oauth:
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-user-rbinding-view
  namespace: monitoring
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: test-user@example.org
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
```

After applying this RoleBinding, the user can log into the kubernetes-dashboard without token, logging in via oidc.
