### ISSUE TITLE
Add insecure api client support 

### ISSUE THREAD

**Issue by RandyAbernethy** [kubernetes/dashboard#1039]
#### Issue details
While KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT envs appear to be respected by the dashboard, there appears to be no way to disable TLS. This makes it difficult to test and experiment with an insecure cluster (e.g. hack/local-up-cluster.sh). The message: "Get https://127.0.0.1:8080/version: http: server gave HTTP response to HTTPS client" is displayed.

To get the host and port right I used the host net and added the below to the spec:
       env:
       - name: KUBERNETES_SERVICE_PORT
         value: "8080"
       - name: KUBERNETES_SERVICE_HOST
         value: "127.0.0.1"

Using the spec element:
        args:
          - --apiserver-host=http://localhost:8080

appears not to work (the message: "Creating API server client for https://10.0.0.1:443" is displayed by the dashboard).

If I have just missed the trick I will happily stand corrected if someone can point me in the right direction.

##### Environment
The test environment is a min install Ubuntu 14.04 server with Kubernetes 1.3 built from source and a single node loop back cluster launched as follows:

```
root@ubuntu:/home/user/kubernetes-1.3.0# hack/local-up-cluster.sh
Go version: go version go1.6.1 linux/amd64
...
```

Various edits (and the stock) kubernetes-dashboard.yaml were tried:
kubectl create -f kubernetes-dashboard.yaml

```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.1.0
(also tried 1.0.1 and 1.0.0)
Kubernetes version: 1.3.0
Operating system: Ubuntu 14.04
Node.js version: none (on the host)
Go version: 1.6.1
```

##### Steps to reproduce
Use this etcd: https://github.com/coreos/etcd/releases/download/v2.3.1/etcd-v2.3.1-linux-amd64.tar.gz
This Go: https://storage.googleapis.com/golang/go1.6.1.linux-amd64.tar.gz
This k8s: https://github.com/kubernetes/kubernetes/archive/v1.3.0.tar.gz
hack/local-up-cluster.sh
then kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml

##### Observed result
Many iterations but this is as close as I can get a connection from dashboard to api:
user@ubuntu:~$ docker logs 477546d852dd
Starting HTTP server on port 9090
Creating API server client for https://127.0.0.1:8080
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://127.0.0.1:8080/version: http: server gave HTTP response to HTTPS client

##### Expected result
Hoping to have the dashboard use http://127.0.0.1:8080 without TLS 

##### Comments
Here is an iteration of the config tried:

```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: kubernetes-dashboard
    version: v1.1.0
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-dashboard
  template:
    metadata:
      labels:
        app: kubernetes-dashboard
    spec:
      hostNetwork: true
      containers:
      - name: kubernetes-dashboard
        image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.1.0
        imagePullPolicy: Always
        env:
        - name: KUBERNETES_SERVICE_PORT
          value: "8080"
        - name: KUBERNETES_SERVICE_HOST
          value: "127.0.0.1"
        ports:
        - containerPort: 9090
          protocol: TCP
        args:
          - --apiserver-host=http://localhost:8080
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9090
  selector:
    app: kubernetes-dashboard
```
