### ISSUE TITLE
How to build a kubernetes dashboard when kube-apiserver use token authentication

### ISSUE THREAD

**Issue by workhardcc** [kubernetes/dashboard#1116]
I follow the page: https://github.com/kubernetes/dashboard to create a kubernetes-dashboard for my cluster.

using the insecure port
- --apiserver-host=http://{{ .Env.MASTER_PRIVATE }}:8080
  it works well.

However, if I using the secure port(token authentication) for kube-apiserver
- --apiserver-host=https://{{ .Env.MASTER_PRIVATE }}:6443

I get this from exited pod（docker logs $contianer）:

> Starting HTTP server on port 9090
> Creating API server client for https://10.93.78.11:443
> Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.93.78.11:443/version: x509: failed to load system roots and no roots provided

So how can I add token information for kubernetes-dashboard pod?

Thanks for help!

**Comment by bryk** [comment]
You can use your kubeconfig file for this. This is the same file you use for kubectl. Then create an env var KUBECONFIG=/path/to/.kubeconfigfile

**Comment by workhardcc** [comment]
Thanks for reply @bryk 
You mean like this? Part of kubernetes-dashboard.yaml:

>     spec:
>       containers:
>       - name: kubernetes-dashboard
>         image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.1.0
>         imagePullPolicy: IfNotPresent
>         env:
>         - name: KUBECONFIG
>           value: /search/authentication/token_file
>         ports:
>         - containerPort: 9090
>           protocol: TCP
>         args:
>           # Uncomment the following line to manually specify Kubernetes API server Host
>           # If not specified, Dashboard will attempt to auto discover the API server and connect
>           # to it. Uncomment only if the default does not work.
>           - --apiserver-host=https://10.93.78.11:443

`cat  /search/authentication/token_file`

```
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    insecure-skip-tls-verify: true
contexts:
- context:
    cluster: local
    user: vpsadmin
users:
- name: vpsadmin
  user:
    token: adawrqqrqfqfdasflkasdfdsafijiw
```
Issue still there...

**Comment by workhardcc** [comment]
@bryk Could you please give me some more information? Thanks!

**Comment by drinktee** [comment]
I have the same question.

**Comment by cheld** [comment]
Server address missing?

```
clusters:
- cluster:
    server: http://MASTER_IP:8080
  name: default
```

**Comment by floreks** [comment]
With authentication it should be actually `server: https://MASTER_IP:SECURE_PORT`

**Comment by cheld** [comment]
The file /search/authentication/token_file must be mounted to the container, I guess

**Comment by drinktee** [comment]
My dashboard worked with token.This is my kubeconfig and replication yaml.

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
  labels:
    k8s-app: kubernetes-dashboard
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kubernetes-dashboard
  template:
    metadata:
      labels:
        k8s-app: kubernetes-dashboard
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kubernetes-dashboard
        image: registry.xxxx.com/path/k8s-dashboard:v1.4.0-beta2
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        env:
        - name: KUBECONFIG
          value: /etc/kubernetes/kubeconfig.yaml
        ports:
        - containerPort: 9090
          hostPort: 8888
        volumeMounts:
        - name: "config"
          mountPath: "/etc/kubernetes"
          readOnly: true
        args:
        -  --apiserver-host=https://xxxxxxxxx:8443
        livenessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
      volumes:
      - name: "config"
        hostPath:
          path: "/home/work/conf"
```

```
apiVersion: v1
kind: Config
users:
- name: kubelet
  user:
    username: secret
    password: admin
clusters:
- name: local
  cluster:
    insecure-skip-tls-verify: true
contexts:
- context:
    cluster: local
    user: kubelet
```

**Comment by cheld** [comment]
The yaml suggested @drinktee is fine. Thanks

I have added a flag as well::
https://github.com/kubernetes/dashboard/pull/1256

**Comment by workhardcc** [comment]
I still can not make it.
`apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    insecure-skip-tls-verify: true
contexts:
- context:
    cluster: local
    user: vpsadmin
users:
- name: vpsadmin
  user:
    token: 123456789`

`kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-dashboard
  template:
    metadata:
      labels:
        app: kubernetes-dashboard
    spec:
      containers:
      - name: kubernetes-dashboard
        image: index.tenxcloud.com/google_containers/kubernetes-dashboard-amd64:v1.4.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          protocol: TCP
        env:
        - name: KUBECONFIG
          value: /etc/kubernetes/token_file
        volumeMounts:
        - name: "config"
          mountPath: "/etc/kubernetes"
          readOnly: true
        args:
          # Uncomment the following line to manually specify Kubernetes API server Host
          # If not specified, Dashboard will attempt to auto discover the API server and connect
          # to it. Uncomment only if the default does not work.
          # - --apiserver-host=http://my-address:port
          #- --apiserver-host=http://10.93.78.11:8080
          - --apiserver-host=https://172.16.88.1:443
        livenessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
      nodeSelector:
        node: kube-system
      volumes:
      - name: "config"
        hostPath:
          path: "/etc/kubernetes/token"
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9090
  selector:
    app: kubernetes-dashboard`

**Comment by maciaszczykm** [comment]
@workhardcc Is API accessible at https://172.16.88.1:443?

**Comment by cheld** [comment]
can you please check my latest trouble shooting guide:

https://github.com/kubernetes/dashboard/pull/1404

**Comment by workhardcc** [comment]
@cheld
Read your trouble shooting guide, I have two question:
1.If my API authentication by token, how can I  `translate into` username and password, my token file as below,
```
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    insecure-skip-tls-verify: true
contexts:
- context:
    cluster: local
    user: vpsadmin
users:
- name: vpsadmin
  user:
    token: 151651dqw51dqw1dqw1dw1qd
```
all of my node use this file to connected "kube-master" .
2. I never used command `kubectl proxy` before, seems need run it when I want access the dashboard page?

**Comment by workhardcc** [comment]
@maciaszczykm yes

**Comment by cheld** [comment]
@workhardcc hmm...not sure if I understand your questions correctly.

1. You must add user and password to a config file and configure api server to use it. I think a restart is required.

2. Browsers do not authenticate with tokens. So yes. kubectl will authenticate with token and create a local proxy webserver that does not require authentication.

If you find issues in the documentation you are welcome to add a review in the PR

**Comment by workhardcc** [comment]
@cheld As we know, there're three ways to authentication kube-api.
1.CA
2.TOKEN
3.user and password
So  you mean that I must use the third way (I'm using the second way now)?

**Comment by workhardcc** [comment]
dashboard create file as below:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-dashboard
  template:
    metadata:
      labels:
        app: kubernetes-dashboard
    spec:
      containers:
      - name: kubernetes-dashboard
        image: index.tenxcloud.com/google_containers/kubernetes-dashboard-amd64:v1.4.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          protocol: TCP
        env:
        - name: KUBECONFIG
          value: /etc/kubernetes/token_file-cc
        volumeMounts:
        - name: "config"
          mountPath: "/etc/kubernetes"
          readOnly: true
        args:
          # Uncomment the following line to manually specify Kubernetes API server Host
          # If not specified, Dashboard will attempt to auto discover the API server and connect
          # to it. Uncomment only if the default does not work.
          # - --apiserver-host=http://my-address:port
          #- --apiserver-host=http://10.93.78.11:8080
      #    - --apiserver-host=http://172.16.88.1:8080
          - --apiserver-host=https://10.93.78.11:443
        livenessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
      nodeSelector:
        node: kube-system
      volumes:
      - name: "config"
        hostPath:
          path: "/etc/kubernetes/token"
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9090
  selector:
    app: kubernetes-dashboard
```
authentication file( node use this file registered to master successfully):
```
apiVersion: v1
kind: Config
users:
- name: vpsadmin 
  user:
    username: vpsadmin
    password: casdfasfqw
clusters:
- name: local
  cluster:
    insecure-skip-tls-verify: true
contexts:
- context:
    cluster: local
    user: vpsadmin
```

**Comment by workhardcc** [comment]
I think the point is how you write the "kubeconfigfile", is there anything wrong with my kubeconfigfile?
Can we reopen this issue?

**Comment by cheld** [comment]
You have to authenticate twice:

browser/cli ----> apiserver <----- dashboard

It seems the user authentication works, I assume. If you access `https://master-ip` then a login dialog should pop-up. When you authenticate correctly you should see server response

When accessing apiserver with browser you have the following options

1. token  => you must use kubectl proxy 
2. certificate => you must use kubectl proxy
2. username & password => you can use kubectl proxy for secure access or use browser directly (insecure)

`kubectl config view` will show your kubectl configuration. Typically, it is generated by the cluster setup. If it does not exist, then you must specify all params on each request e.g. instead of `kubectl get nodes` you must specify `kubectl --apiserver=.... get nodes`

Your dashboard configuration seems to be correct (could be improved) but should work. 

I will improve the troubleshooting guide

**Comment by workhardcc** [comment]
Thanks all of you guys. It's worked!
There are three points I think maybe we should improve:
1.I change the image from kubernetes-dashboard-amd64:v1.4.1 to kubernetes-dashboard-amd64:v1.4.0, use config file as above. Then it worked !
So maybe is there anything "wrong" with new version?
2.In kube-dashboard readme.md 

> Please note, this works only if the apiserver is setup to allow authentication with username and password. Currently, the setup tool kubeadm is not doing so. If username and password is unknown to you then use kubectl config view to find it.

When I read this I thought only we use basic authtication for kube-apiserver that  can make dashborad work. Now it seems that we also use token authtication for kube-apiserver.
3.Note that kube-dashboard is a service
```
kind: Service
apiVersion: v1
metadata:
  labels:
    app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9090
  selector:
    app: kubernetes-dashboard
```
So we can access the kube-dashboard page by $node_ip:30xxx, browser/cli don't need any authentication . This will be a security problem?
Thanks for help!
