### ISSUE TITLE
[Question] Heapster endpoint config to work with Dashboard

### ISSUE THREAD

**Issue by ntquyen** [kubernetes/dashboard#1403]
I'm running Heapster v1.2.0, Dashboard v1.4.x in kubernetes cluster v1.4.5. Heapster and Dashboard are running in `kube-system` namespace but Dashboard still cannot connect to Heapster. According to this issue https://github.com/kubernetes/dashboard/issues/1096, I must configure heapster to be accessible via service proxy `http://[api-server]/api/v1/proxy/namespaces/kube-system/services/heapster/`. However, I can only make it to work with the endpoints `http://[api-server]/api/v1/proxy/namespaces/kube-system/services/heapster:8082/`. So how can I make it work without putting the port 8082?

**Comment by floreks** [comment]
Could you show me your yaml files used to deploy heapster and service? Do you have dns configured?

Here are mine (I can access heapster via `https://<master-ip>/api/v1/proxy/namespaces/kube-system/services/heapster/`):

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: heapster
    version: v6
    app: heapster
  name: heapster
  namespace: kube-system
spec:
  revisionHistoryLimit: 5
  replicas: 1
  template:
    metadata:
      labels:
        app: heapster
    spec:
      containers:
      - name: heapster
        image: kubernetes/heapster:canary
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes:https://<master-ip>
        - --sink=influxdb:http://influxdb.kube-system.svc.cluster.local:8086/
```

```
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Heapster
  name: heapster
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    k8s-app: heapster
```
