### ISSUE TITLE
Dashboard can also be used with client certificates

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/dashboard#1476]
##### Environment

I deploy Kubernetes and the Dashboard with my own Ansible playbook.  I make a local CA and use it to sign certs for the apiserver and other platform components and a user named "admin".  I run the apiserver in a static pod, and the controller manager in another static pod.  I have a local authorization server consulted as a webhook.  Here is what `ps lwww` shows about the apiserver process on the (it's a simple setup for testing) master:
```
4     0 15262 15247  20   0 559704 206556 futex_ Ssl ?         50:59 /hyperkube apiserver --bind-address=0.0.0.0 --insecure-bind-address=127.0.0.1 --etcd-servers=https://100.126.0.2:4001 --allow-privileged=true --service-cluster-ip-range=10.10.10.0/24 --secure-port=8443 --insecure-port=8080 --advertise-address=100.126.0.2 --tls-cert-file=/etc/kubernetes/cert/apiserver.pem --tls-private-key-file=/etc/kubernetes/cert/apiserver-key.pem --client-ca-file=/etc/kubernetes/cert/ca.pem --etcd-cafile=/etc/kubernetes/cert/ca.pem --etcd-certfile=/etc/kubernetes/cert/apiserver.pem --etcd-keyfile=/etc/kubernetes/cert/apiserver-key.pem --authorization-mode=Webhook --authorization-webhook-config-file=/etc/kubernetes/webhook-config --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota --v=6
```

```
Dashboard version: Fetched from https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml on 23 Nov 2016
Kubernetes version: release 1.4.6
Operating system: k8s cluster is on Ubuntu 16.04; Firefox browser is on MacOS 10.10.5
Node.js version: ??
Go version: 1.6.3
```

##### Steps to reproduce

1. Deploy k8s release 1.4.6 on Ubuntu 16.04; no addons controller.
2. `kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml`
3. My k8s cluster is not directly accessible from my Mac, so I created a SOCKS proxy and configured Firefox on my Mac to use it.
4. In the Preferences page of Firefox on my Mac, navigate in the left column to "Advanced", then to the "Certificates" tab, click the "View Certificates" button, and: (a) navigate to the "Authorities" tab and import the CA cert used in the k8s cluster, and (b) navigate to the "Your Certificates" tab and import a `.p12` file containing the cert and key of the admin user.
5. Using Firefox on the Mac, visit https://<master_ip>:<api_port>/ui .

##### Observed result

Before importing the CA cert, Firefox complains that the server's cert is not signed by a recognized CA.  After adding the CA cert and the user cert, the dashboard works as normal.  You can browse and modify things.

##### Expected result

The doc at https://github.com/kubernetes/dashboard/blob/3e147d1d41bbbdc9199fbac17a59eacfaef3c334/README.md#alternative-usage says I can only use the dashboard if the apiserver is configured to allow authentication with username and password.  My apiserver is not (as you can see in the command line above), so I expected to have a problem.

##### Comments

I am not trying to solve all of #964, just point out that right now things are better than documented --- so the doc should be updated.

**Comment by floreks** [comment]
Yes, that's true. I haven't noticed that and I have the same set up as you. We'll fix that. Thanks!

**Comment by bryk** [comment]
@floreks @cheld Do you know how to fix the docs to solve the problem? I don't...

**Comment by floreks** [comment]
I've explained step by step configuration process (using certificates) in here: https://github.com/kubernetes/dashboard/issues/1287#issuecomment-250681546

**Comment by liujiawinds** [comment]
@floreks hi, I follow your steps. But I can't see the config detail just like below:

```
[root@maxcd03-kube1 maxent]# kubectl config view
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
```

I'm sure this file appended in controller-manager,kubelet,proxy, scheduler with`--kubeconfig=/etc/kubernetes/tls_config` : 

```
[root@maxcd03-kube1 maxent]# cat /etc/kubernetes/tls_config 
current-context: default-context
apiVersion: v1
clusters: 
- cluster:
    certificate-authority: /etc/kubernetes/ssl_keys/ca.crt
    server: https://10.18.1.16:9443
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    namespace: development
    user: admin
  name: default-context
- context:
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate: /etc/kubernetes/ssl_keys/admin.crt
    client-key: /etc/kubernetes/ssl_keys/admin.key
```
 
Is there something wrong ?
