### ISSUE TITLE
Long TPR names do not fit menu

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1708]
![image](https://cloud.githubusercontent.com/assets/2823399/23657751/001e9dfe-0340-11e7-9839-7d768e9ae630.png)

**Comment by maciaszczykm** [comment]
Perhaps we should display short names (i.e. `CronTabs`/`Cron Tabs` instead of `cron-tab.stable.example.com`)?

**Comment by cheld** [comment]
The names are ugly. Would it be possible to show only first part by default and show full name only in case of clash?

**Comment by cheld** [comment]
How can we shorten the name? First part unitl dot? 

I think it is a good idea. By default we should show the short name and only in case of name clash we show the long name

**Comment by maciaszczykm** [comment]
@cheld When you take a look on sample TPR definition:

``` yaml
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
metadata:
  name: cron-tab.stable.example.com
description: "A specification of a Pod to run on a cron style schedule"
versions:
- name: v1
```

You can see, that TPR group is taken from its name. 

If specified name is `cron-tab.stable.example.com` real name will be `CronTab` and group will be `stable.example.com` with `v1` version.

`kubectl get crontabs` is correct query to get TPRs and we'd have `Cron Tabs` entry in the menu.
