### ISSUE TITLE
Ownership matching finds too many Pods

### ISSUE THREAD

**Issue by konryd** [kubernetes/dashboard#1727]
#### Issue details
Pods managed by ReplicaSets, ReplicationControllers and some other resource types should be tracked by OwnerReference, not by simple label match. Simple label match is too wide.

##### Environment
```
Dashboard version: 1.5.0
Kubernetes version: 1.5.3
```

##### Steps to reproduce
Reproduction steps:

Create a ReplicationController and ReplicaSet using the following yaml files:

```
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginxrs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```
and
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 4
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```

##### Observed result
The details pages for each of them will show (7/4) and (7/3), and list pods not managed by the given resource.

##### Expected result
Those pages should say 4/4 and 3/3 respectively, and only the pods managed by the resource should be displayed.
