### ISSUE TITLE
Percentage values for maxUnavailable/maxSurge for Deployment not rendered properly

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/dashboard#1745]
##### Environment

```
Dashboard version: v1.5.0
Kubernetes version: Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

##### Steps to reproduce

Create a Deployment with percent values:

```
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 40%
  ...
```

##### Observed result

Percent value is shown as `0` in the Dashboard.

![image](https://cloud.githubusercontent.com/assets/159209/24018911/1c7d0dd6-0a53-11e7-8ef8-aed62edc5aa9.png)
