### ISSUE TITLE
heapster error

### ISSUE THREAD

**Issue by timchenxiaoyu** [kubernetes/dashboard#1769]
dashboard version : kubernetes-dashboard-amd64:v1.5.1
heapster version: heapster-amd64:v1.3.0-beta

no monitor data :
error
Getting pod metrics
Skipping Heapster metrics because of error: invalid character 'E' looking for beginning of value

**Comment by floreks** [comment]
Check out my [comment](https://github.com/kubernetes/dashboard/issues/1754#issuecomment-287535708) in other issue about heapster.

To sum up:
 - make sure that heapster is running inside the cluster
 - make sure that heapster is accessible from inside the cluster by using service proxy or that it is exposed and `heapster-host` argument is provided to dashboard

**Comment by timchenxiaoyu** [comment]
I can get monitor data from heapster svc ip

**Comment by timchenxiaoyu** [comment]
kubectl describe svc heapster -n kube-system
Name:			heapster
Namespace:		kube-system
Labels:			kubernetes.io/cluster-service=true
			kubernetes.io/name=Heapster
			task=monitoring
Selector:		k8s-app=heapster
Type:			ClusterIP
IP:			10.254.51.153
Port:			<unset>	80/TCP
Endpoints:		192.168.67.4:8082
Session Affinity:	None

**Comment by floreks** [comment]
How does your heapster yaml file looks like? It should have `--source=kubernetes` param set.

**Comment by timchenxiaoyu** [comment]
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kubernetes-dashboard
  template:
    metadata:
      labels:
        app: kubernetes-dashboard
      # Comment the following annotation if Dashboard must not be deployed on master
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: |
          [
            {
              "key": "dedicated",
              "operator": "Equal",
              "value": "master",
              "effect": "NoSchedule"
            }
          ]
    spec:
      containers:
      - name: kubernetes-dashboard
        image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.5.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
          protocol: TCP
        args:
          # Uncomment the following line to manually specify Kubernetes API server Host
          # If not specified, Dashboard will attempt to auto discover the API server and connect
          # to it. Uncomment only if the default does not work.
         - --apiserver-host=http://10.39.0.6:8080
        livenessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 31081
  selector:
    app: kubernetes-dashboard

**Comment by timchenxiaoyu** [comment]
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      nodeName: slave2
      containers:
      - name: heapster
        image: gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes:http://10.39.0.6:8080?inClusterConfig=true&useServiceAccount=true&auth=
        - --sink=influxdb:http://monitoring-influxdb:8086

**Comment by timchenxiaoyu** [comment]
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Heapster
  name: heapster
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    k8s-app: heapster

**Comment by floreks** [comment]
Can you access heapster metrics using: `<apiserver_ip:port>/api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/model/namespaces/kube-system/pod-list/<pod_name>/metrics/cpu-usage`?

I have just tried configuring heapster on minikube and it works fine. Here are yaml files that I used:

heapster-deployment.yaml
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: heapster
    app: heapster
  name: heapster
  namespace: kube-system
spec:
  revisionHistoryLimit: 5
  replicas: 1
  template:
    metadata:
      labels:
        app: heapster
        k8s-app: heapster
    spec:
      containers:
      - name: heapster
        image: gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes
        - --sink=influxdb:http://influxdb.kube-system.svc.cluster.local:8086/
```

heapster-service.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Heapster
  name: heapster
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    k8s-app: heapster
```

Is there any reason why you are using `apiserver-host` param for dashboard? Can't you use in cluster config same as for heapster?

Could you also show me the logs of dashboard when it's started? There should be info whether or not heapster client was created and if in cluster config was used.
