### ISSUE TITLE
EnvVar from the field of the pod is missing

### ISSUE THREAD

**Issue by supereagle** [kubernetes/dashboard#1798]
#### Issue details
In the pod details page of dashboard, only envs with specified values are shown, but envs with values from fields of the pod (such as metadata.name, metadata.namespace) are missing.

##### Environment

```
Dashboard version: v1.5.1
Kubernetes version: v1.5.3
Operating system: CentOS Linux release 7.3
Node.js version:
Go version: 
```

##### Steps to reproduce
1. Create pod with spec
```
spec:
  containers:
  - env:
    - name: DB_URL
      value: mysql.master.com
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
```
2. Check the pod env in the pod details page of dashboard

##### Observed result

In dashboard, both DB_URL and POD_NAME can be found in the envs of the pod, DB_URL has value, but POD_NAME has no value.
POD_NAME has the correct value when `kubectl describe pod` or exec `env` command in pod.

##### Expected result

Both DB_URL and POD_NAME can be found and have values.

**Comment by maciaszczykm** [comment]
Tested it and it doesn't work. Thanks for letting us know. We'll try to fix it.

**Comment by maciaszczykm** [comment]
To reproduce use: 

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: envar-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    env:
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
```

![image](https://cloud.githubusercontent.com/assets/2823399/24606996/1484a190-1870-11e7-80f3-251e3696243b.png)

![image](https://cloud.githubusercontent.com/assets/2823399/24607006/1dfdbd1a-1870-11e7-8e07-cb9157d8872d.png)
