### ISSUE TITLE
What happened to the cluster-service annotation?

### ISSUE THREAD

**Issue by colemickens** [kubernetes/dashboard#1849]
https://github.com/kubernetes/dashboard/blob/b98d167dadaafb665a28091d1e975cf74eb31c94/src/deploy/kubernetes-dashboard.yaml

Why do the yamls in this repo not feature the `cluster-service` tag that causes it to appear in `kubectl cluster-info` ?

From some dashboard yaml that we imported ages ago and have been updating, for example, we had these:
```
   labels:
     kubernetes.io/cluster-service: "true"
     k8s-app: kubernetes-dashboard
    version: v1.5.1
```
