### ISSUE TITLE
Support for user-customizeable links in Pods, Service and StatefulSets through Annotations

### ISSUE THREAD

**Issue by mwitkow** [kubernetes/dashboard#1989]
##### Environment
Standard pre-built docker container.

```
Dashboard version: 1.5.1
Kubernetes version: 1.5.3
```

##### Feature Request

It would be fantastic to be able to leverage Kubernetes dashboard as a command and control place for all your services by cross-linking the relevant resources for a Service, StatefulSet or a Pod.

This could be done either through
 * forking dashboard and customizing the Angular templates to add these
 * adding annotations to Pods/Services/StatefulSets

###### Adding links to `/debug` pages of Pods
A lot of go servers expose `/debug` pages, e.g. [`/debug/requests`](https://twitter.com/zekjur/status/713476432282955776). It would be fantastic for users to be able to add links to the relevant endpoints with the [Pod's DNS](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/) address. 

For example, an annotation for Pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    alpha.dashboard.kubernetes.io/links/pod: |
      {
        "requests":"http://{{.pod.dns_name}}:9090/debug/requests",
        "pprof":"http://{{.pod.dns_name}}:9090/debug/pprof",
      }
```
###### Adding links to monitoring dashboards for Services
It would be fantastic to be able to link from a Service page to other, richer monitoring services. For example with Grafana you can cross link to a dashboard using [templating variables](http://docs.grafana.org/reference/templating/):

For example, an annotation for Service :
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    alpha.dashboard.kubernetes.io/links/pod: |
      {
        "monitoring":"https://mymonitoring.example.com/dashboard/file/service.json?var.cluster={{.cluster.name}}&var.job="{{.service.name}}",
      }
  labels:
    component: myservice
    k8s-app: myservice
  name: myservice
  namespace: myteam
```

It would be fantastic if it was generic enough to access any property of the Pod or Service definition, but simple things such as DNS name, cluster name and Pod/Service/StatefulSet name would be enough.

We would be happy contributing support for this feature :)
