### ISSUE TITLE
Pod attach/exec enhancements

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#2029]
Moved task list from #1939 to an issue to keep track of them:
- [ ] Ability to attach as in kubectl attach
- [ ] Implement locking for session map (while the current code is bad, actually triggering the problem is unlikely)
- [ ] Add links leading to exec view (something like logs button)
- [ ] Serve SockJSURL from dashboard
- [ ] utf-8 input (needs hterm needs configuration)
- [ ] Add some tests
- [ ] Some solution to respawn if the user exits the shell (?)
- [ ] Some padding on the left (?)

**Comment by Zexi** [comment]
If I run 'while true; do echo 1; done' command in shell, the browser will be stucked.
![image](https://user-images.githubusercontent.com/10767027/27340837-1817a3bc-560e-11e7-811e-6e0e051ac907.png)

**Comment by adrianchifor** [comment]
When I leave a shell and refresh, the dashboard crashes with the following error: 

![dash-crash](https://user-images.githubusercontent.com/6370064/27427580-6a628e64-5737-11e7-84f2-919b8daa8104.png)

Is this related to the `Some solution to respawn if the user exits the shell (?)` point ?

**Comment by floreks** [comment]
> I assume the problem is that it tries to read data from a closed socket.

I think you are right. We probably should have some button to open terminal and when session is terminated or there is a timeout automatically close it. Refreshing the page would close the session and open a new one.

**Comment by IanLewis** [comment]
FYI exec/attach should work w/ kubectl proxy after https://github.com/kubernetes/kubernetes/pull/49534 gets merged.

**Comment by maciaszczykm** [comment]
@IanLewis Great.

**Comment by IanLewis** [comment]
@maciaszczykm Yah. Not sure if updating to use WebSockets is in scope of this issue or not though.

**Comment by kfox1111** [comment]
A couple more issues for the list:

1. Most of my pods are multi container. I need a way to specify which container to exec into.
2. Quite a few containers these days don't have /bin/bash but only /bin/sh. Being able to specify would let it work in many more cases.

**Comment by floreks** [comment]
1. There is a combobox on exec page where you can select a container.
2. If `/bin/bash` is not found it falls back to `/bin/sh` already. If both are not present you'll get an error.

**Comment by shamil** [comment]
@floreks the second part never works, when it fails back to `/bin/sh` the console closes right after shell started. 

![](http://i.imgur.com/lAyn6iU.png)

If `/bin/bash` present, everything works well!

**Comment by floreks** [comment]
This is related to incorrect session handling. Exec is in early stage and we are aware that there are some issues that make exec unusable for now. We are working on fixing them. Hopefully it will be more stable in 1.7 release.

**Comment by kachkaev** [comment]
Just FYI as this is relevant to this thread. I've started seeing the following message after upgrading dashboard to 1.7: `unable to upgrade connection: you must specify at least 1 of stdin, stdout, stderr`.

Rolling back to 1.6.3 made it again possible to execute bash and getting "connection closed" for shell-only pods.

**Comment by maciaszczykm** [comment]
@kachkaev It is fine. Security was out piority 0 issue for 1.7 release, but now we should be able to find some time for issues like that.

**Comment by Globegitter** [comment]
I am using the kops version of the dashboard in one of our environments and have taken this yaml: https://github.com/kubernetes/kops/blob/master/addons/kubernetes-dashboard/v1.7.0.yaml, just updated the dashboard image to 1.7.1 and still seeing the 'Connection closed' issue if the pod does not have bash. I have confirmed in the About section that it really is 1.7.1 and interestingly enough in our other cluster where we are using the recommended yaml from the repo here it all works fine.

**Comment by floreks** [comment]
They differ a bit :) Very important part is missing in your yaml file.
```yaml
        volumeMounts:
        - name: kubernetes-dashboard-certs
          mountPath: /certs
          readOnly: true
          # Create on-disk volume to store exec logs
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /
            port: 8443
          initialDelaySeconds: 30
          timeoutSeconds: 30
      volumes:
      - name: kubernetes-dashboard-certs
        secret:
          secretName: kubernetes-dashboard-certs
      - name: tmp-volume
        emptyDir: {}
```
