### ISSUE TITLE
Secrets in environment variables are displayed in plaintext in the pod details

### ISSUE THREAD

**Issue by Firehed** [kubernetes/dashboard#2153]
##### Environment

```
Dashboard version: 1.6.1
Kubernetes version: 1.7.0
```
I am running k8s in GKE, at version 1.7.0 (the latest supported as of writing) using the dashboard exactly as it comes configured out of the box (1.6.1 going by the image described in the pod in kube-system).

##### Steps to reproduce
1) Create a deployment (or just a pod) that uses a secret to populate an environment variable
```yaml
...
spec:
  containers:
    - env:
        name: SOME_NAME
        valueFrom:
          secretKeyRef:
            name: secret-name
            key: key-in-secret
...
```
2) View the pod details page for the pod created in the above step

##### Observed result
In the Environment Variables section, the secret is displayed

##### Expected result
The env var value is redacted in some way (links to the secret, just says "hidden", inlined "eye" toggle like on the secret page, etc)
