### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by bchanan03** [kubernetes/dashboard#2211]
##### Steps to reproduce
search any kubernetes objects - causes an internal error

##### Environment
```
Installation method: kubernetes create -f kubernetes-dashboard.yaml
Kubernetes version: v1.5.7
Dashboard version: v1.6.3
Commit: 5b3e0858b3c713052307f2ec83b06853b61fde84
```
kubernetes-dashboard.yaml file:
------------------------------------
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # Keep this file in sync with addons/dashboard/dashboard-controller.yaml
  name: kubernetes-dashboard
  namespace: kube-system
  labels:
    k8s-app: kubernetes-dashboard
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kubernetes-dashboard
  template:
    metadata:
      labels:
        k8s-app: kubernetes-dashboard
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kubernetes-dashboard
        image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 9090
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
```

kubernetes-service.yaml file:
-------------------------------
```
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
  labels:
    k8s-app: kubernetes-dashboard
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    k8s-app: kubernetes-dashboard
  ports:
  - port: 80
    targetPort: 9090
```

##### Observed result
Dashboard reported Not Found (404):
```
the server could not find the requested resource

```
