### ISSUE TITLE
Add option to enable/disable heapster integration from dashboard

### ISSUE THREAD

**Issue by mccormd** [kubernetes/dashboard#2251]
##### Environment
```
Dashboard version: 1.6.3
Kubernetes version: 1.7.3
Operating system: CoreOS
```

##### Steps to reproduce
When I start the dashboard with the workaround for heapster (it does not work without it): -
```
      - name: kubernetes-dashboard
        image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3
        args:
        - --heapster-host=http://heapster.kube-system
```
If heapster service comes up after the dashboard pods then the dashboard does not display any graphs.

##### Observed result
Kubernetes dashboard does not retry for heapster availability and so no graphs are displayed within the dashboard.

Forcing a redeployment/killing the dashboard pods once heapster is up brings back the graphs. 

##### Expected result
I don't want to have to start the dashboard after heapster as this is hard to orchestrate.
The dashboard should continue to check for heapster availability and start displaying graphs once it is available rather than checking once.
