### ISSUE TITLE
Environment variables defined using envFrom are not shown when viewing a pod's containers

### ISSUE THREAD

**Issue by frasern** [kubernetes/dashboard#2343]
##### Environment
```
Dashboard version: master
Kubernetes version: 1.7.2
Operating system: AWS/KOPS
```

##### Steps to reproduce
1. Create a deployment that uses `envFrom` to pull data from a ConfigMap, for example:
```
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: test
    labels:
      app: test
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: test
      spec:
        containers:
        - name: echoserver
          image: gcr.io/google_containers/echoserver:1.4
          envFrom:
          - configMapRef:
              name: my-config-map

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: my-config-map
  data:
    FOO: xxx
    BAR: yyy
```
2. View the pod in the Dashboard

##### Observed result
No environment variables are shown within the *Containers* card.

##### Expected result
I would have expected to see the environment variables listed, ideally with a link to the appropraite ConfigMap.

##### Comments
Environment variables specified explicitly using `env` are shown.

Furthermore, if `valueFrom`/`secretKeyRef` is used within `env` to reference a Secret value, then a link to the Secret is shown beside each such variable.

Looking at the JSON requested by the Dashboard from the API, I can see that no environment variables are returned:
```
   {
    "name": "echoserver",
    "image": "gcr.io/google_containers/echoserver:1.4",
    "env": [],
    "commands": null,
    "args": null
   }
```

If the API is simply not returning envFrom info, then this may well be an upstream issue.

**Comment by floreks** [comment]
This is probably because in this case there is a different way of getting those values. 

This is our test yaml:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: env-variables
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "sh", "-c"]
      args:
      - while true; do
          echo -en '\n';
          printenv MY_POD_NAME;
          printenv MY_MEM_REQUEST MY_MEM_LIMIT;
          printenv MY_CONST_VALUE;
          printenv MY_SECRET_VALUE;
          sleep 10;
        done;
      resources:
        requests:
          memory: "32Mi"
          cpu: "125m"
        limits:
          memory: "64Mi"
          cpu: "250m"
      env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_MEM_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: test-container
              resource: requests.memory
        - name: MY_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: test-container
              resource: limits.memory
        - name: MY_CONST_VALUE
          value: "test-const-value"
        - name: MY_SECRET_VALUE
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: username
  restartPolicy: Never
```

`kubectl describe pod env-variables`
```bash
...
Environment:
      MY_POD_NAME:	env-variables (v1:metadata.name)
      MY_MEM_REQUEST:	33554432 (requests.memory)
      MY_MEM_LIMIT:	67108864 (limits.memory)
      MY_CONST_VALUE:	test-const-value
      MY_SECRET_VALUE:	<set to the key 'username' in secret 'secret-env'>	Optional: false
...
```

`kubectl describe pod test-...`
```bash
...
Environment Variables from:
      my-config-map	ConfigMap	Optional: false
Environment:	<none>

...
```

Kubectl displays them a bit differently so I'm assuming they are stored in a different way. We currently support first way only.
