### ISSUE TITLE
Finish 1.7.1 release (update at core repo)

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#2395]
- [x] complete https://github.com/kubernetes/dashboard/releases
- [ ] update `/ui` redirect on core repo (https://github.com/kubernetes/kubernetes/pull/53046)
- [ ] update core to use 1.7.1 (https://github.com/kubernetes/kubernetes/pull/53046)
- [ ] migrate kubernetes/kubernetes SIG-UI tests to a separate folder (https://github.com/kubernetes/dashboard/issues/2128)
- [x] update minikube to use 1.7.1
- [x] update kops to use 1.7.1

**Comment by ilgizy** [comment]
Can't pull image gcr.io/google_containers/kubernetes-dashboard-amd64:v1.7.0
po/kubernetes-dashboard-4167803980-gjknf   0/1       Init:ImagePullBackOff

**Comment by floreks** [comment]
Images haven't been pushed yet. You have to wait.

**Comment by rf232** [comment]
should be there now

**Comment by cbdog94** [comment]
I have successfully installed  dashboard 1.7.0 through the file https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml. But when I wanted to configure Admin privileges mentioned in https://github.com/kubernetes/dashboard/wiki/Access-control#admin-privileges, I could't find the Official release code snippet. So I actually don't know how to configure Admin privileges mode through the current wiki.

**Comment by floreks** [comment]
As described in wiki just take take YAML snippet under Official release, create yaml file and use `kubectl create -f` to deploy it. That's it.

This snippet is there also.
```YAML
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard
  labels:
    k8s-app: kubernetes-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kube-system
```
