### ISSUE TITLE
403 Forbidden on Pod Detail Page because of "cannot list secrets"

### ISSUE THREAD

**Issue by marco-jantke** [kubernetes/dashboard#2403]
##### Environment
We are running Kubernetes with the google container engine (GKE). Because of security reasons we created an own service account for the dashboard and associated rights without secrets. A detailed info of the associated cluster role for the dashboard is below.

```
Dashboard version: 1.6.1 (image: eu.gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.1)
Kubernetes version: 1.7.5
Operating system: linux/amd64
Node.js version: not sure
Go version: 1.8.3
```

##### Steps to reproduce
Setup the serviceaccount, clusterrole and clusterrolebinding.

The clusterrole associated with the serviceaccount:
```yml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dust:dashboard
rules:
- apiGroups:
  - extensions
  resources:
  - replicasets
  - deployments
  - deployments/scale
  verbs:
  - update
  - patch
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - list
```

##### Observed result
 Navigate to the Dashboard and open the Pod Detail page of any Pod. The page will not be opened and in the browser console you can find the following error:

```
User "system:serviceaccount:kube-system:dashboard" cannot list secrets in the namespace "development".: "Unknown user \"system:serviceaccount:kube-system:dashboard\"" (get secrets)
```

##### Expected result
The Pod detail page should be shown normally.

##### Comments
Please let me know when you need more information from my side. Also, it might be interesting for you that this configuration was working normally for us with Kubernetes versions in 1.6.x. We are aware that with this configuration the `Secrets` page will not work, which is fine for us. Only cluster administrators should have it and they all can access it via `kubectl`.
