### ISSUE TITLE
Job pod status is not updated on failed / succeed

### ISSUE THREAD

**Issue by innovia** [kubernetes/dashboard#2459]
##### Environment
KOPS 1.7.8 - AWS
```
Dashboard version: 1.7.0 and 1.7.1
Kubernetes version: 1.7.8
Operating system: Debian 8
Node.js version: N/A
Go version: N/A
```

##### Steps to reproduce
Run a Job to completion using the settings:
```yaml
Parallelism:              1
Completions:              1
Active Deadline Seconds:  1200s
```
##### Observed result
Job runs until pod failed / succeeded,  status stays the same:
`Status 
  Pods: 0 active  0 succeeded  0 failed`

##### Expected result
When using `kubectl describe job some-job` you can clearly see that the job status is completed / failed
`Pods Statuses:            0 Running / 1 Succeeded / 0 Failed`

**Comment by floreks** [comment]
Could you share yaml used to create job? I could not reproduce it on Dashboard v1.7.1.
![zrzut ekranu z 2017-10-11 11-39-53](https://user-images.githubusercontent.com/2285385/31433247-04ecc2b8-ae79-11e7-84cb-213e255c2531.png)

**Comment by innovia** [comment]
I think it happens when the pod is cleaned up  but im not sure
maybe try to set the active deadline for less then a minute

![image](https://user-images.githubusercontent.com/112025/31436267-21d7861c-ae8b-11e7-84d8-32752fc56693.png)

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: ami-cin-test
spec:
  activeDeadlineSeconds: 1200
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: ami-cin-test
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: init
        image: "12345678.dkr.ecr.us-west-2.amazonaws.com/tensorflow:1.1-rc1.2"
        command:
        - "/bin/bash"
        - "-c"
        - |-
          exec &> >(tee -a /code/init_container.log)
          set -e
          set -o pipefail
          echo "Bootstrap started"
          echo "Setting up code base"
          aws s3 cp s3://some-bucket/code/5360153755b6ebea463566c4267abc4669061374.tar.gz /tmp/
          tar -zxf /tmp/5360153755b6ebea463566c4267abc4669061374.tar.gz -C /code
          rm /tmp/5360153755b6ebea463566c4267abc4669061374.tar.gz
          echo "Bootstrap completed."
        volumeMounts:
        - name: output
          mountPath: /output
        - name: code
          mountPath: /code
      containers:
      - image: "12345678.dkr.ecr.us-west-2.amazonaws.com/tensorflow:1.1-rc1.2"
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
            cpu: "2.0"
          requests:
            cpu: "2.0"
        workingDir: "/code"
        name: tensorflow-worker
        command:
        - "/bin/bash"
        - "-c"
        - |-
          exec &> >(tee -a /output/job.log)
          set -e
          set -o pipefail
          
          if [[ -f /code/requirements.txt ]]; then
            echo "Installing requirements.txt"
            pip install -r requirements.txt
          fi

          echo -e "Launching command:\n python3.5 Projects/style_transfer/conditional_instance_norm/cin/train.py 
          python3.5 Projects/style_transfer/conditional_instance_norm/cin/train.py
          echo "Job done"
        volumeMounts:
        - name: input
          mountPath: /input
          readOnly: true
        - name: output
          mountPath: /output
        - name: code
          mountPath: /code
        
      volumes:
      - name: input
        persistentVolumeClaim:
          claimName: ml-input-nfs-pvc
      - name: output
        persistentVolumeClaim:
          claimName: ml-output-nfs-pvc
      - name: code
        emptyDir: {}
```
