### ISSUE TITLE
What is going on with the ports in deploy/recommend/kubernetes-dashboard.yaml?

### ISSUE THREAD

**Issue by colemickens** [kubernetes/dashboard#2469]
https://github.com/kubernetes/dashboard/blob/fc210d094db7deec68e87b05816fbd1b6076da6e/src/deploy/recommended/kubernetes-dashboard.yaml

* Why is the Service pointed at 8443 instead of 9090?
* Why does the container/pod not declare the port that it's talking to?
* Why is the dashboard trying to serve over TLS anyway? How am I supposed to easily front the dashboard with Ingress (with an actual public-CA-signed TLS cert)?

**Comment by colemickens** [comment]
I guess I get it now... I should use the alternative ones since I'm running Ingress and my own TLS via Ingress.

**Comment by shavo007** [comment]
I got caught out with this too! Using my own ingress now to point to dashboard! 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dashboard
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: dashboard.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 80

```
