### ISSUE TITLE
Can‘t open web shell 

### ISSUE THREAD

**Issue by EvolveZy** [kubernetes/dashboard#2504]
##### Environment

```
Dashboard version:1.7.1
Kubernetes version:1.7.5
Operating system:CentOS7.2 1611
Node.js version:
Go version:
```

**Comment by EvolveZy** [comment]
shell
![image](https://user-images.githubusercontent.com/16017151/31809874-27d4c4a8-b5ac-11e7-8bbf-e42bb3c285a4.png)

**Comment by EvolveZy** [comment]
it's null

**Comment by floreks** [comment]
This screenshot doesn't really show us anything important. Check console tab for errors.

**Comment by EvolveZy** [comment]
Console not show any errors
![image](https://user-images.githubusercontent.com/16017151/31810710-5734e162-b5af-11e7-9ae8-a025ba641f91.png)
Con

**Comment by maciaszczykm** [comment]
@EvolveZy Does it crash on all resources? Can you send us resource (.yaml/.json file) that you are using to test?

**Comment by EvolveZy** [comment]
apiVersion: v1
kind: ReplicationController
metadata:
  name: xcstore-test
  namespace: xcstore
spec:
  replicas: 1
  selector:
    name: xcstore-test
  template:
    metadata:
      labels:
        name: xcstore-test
    spec:
      containers:
        - name: xcstore-test
          imagePullPolicy: Always
          image: nginx:latest

**Comment by EvolveZy** [comment]
[rc.zip](https://github.com/kubernetes/dashboard/files/1401180/rc.zip)

**Comment by EvolveZy** [comment]
i refresh  chorme  several times，it's working ，but i refresh again，it's not work

**Comment by EvolveZy** [comment]
i use Dashboard version:1.7.1 Kubernetes version:1.7.0 Operating system:CentOS7.2 1611 and same yaml file，it's ok

**Comment by floreks** [comment]
I have tried this yaml

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
name: xcstore-test
namespace: xcstore
spec:
replicas: 1
selector:
name: xcstore-test
template:
metadata:
labels:
name: xcstore-test
spec:
containers:
- name: xcstore-test
imagePullPolicy: Always
image: nginx:latest
```

and it works just fine for me (checked on Dashboard v1.7.1 and K8S v1.8.1). Maybe there is some networking issue (proxy?). There should be a timeout after some time and notification should be shown.
