### ISSUE TITLE
Settings improvements

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#2618]
- [x] add minimal RBAC create rights of config maps (workaround like in https://github.com/kubernetes/kubernetes/pull/53046)
- [x] disable settings editing if auth was skipped (#2639)
- [ ] enable global settings editing only for specific role/user
- [x] add user-specific settings (also remember sort, filter, namespace etc. after page refresh)
- [x] add language picker where user is able to switch between browser's locale and the one chosen by him (mentioned in #2240)
- [x] add color/theme picker where user is able to pick primary theme's color (mentioned in #1657)

Continuation from https://github.com/kubernetes/dashboard/issues/2417.

**Comment by rahuldhide** [comment]
@maciaszczykm When are we planning to start theme/color picker feature?

**Comment by maciaszczykm** [comment]
@rahuldhide It is a quite low priority for us at the moment.

**Comment by jurgenweber** [comment]
documentation on how to setup and ensure the page works? I get a 403 when accessing the 'settings' page right now and there is nothing in the docs (that I can find), I can see it makes/has made the 'kubernetes-dashboard-settings' configmap.. it has access to it... about it.

**Comment by maciaszczykm** [comment]
@jurgenweber Are you using this role with access privileges to access Dashboard?

**Comment by floreks** [comment]
If you want to be able to access settings page while using `Skip` option then u need to disable settings authorizer.

Check out Dashboard arguments:
https://github.com/kubernetes/dashboard/wiki/Dashboard-arguments

**Comment by sellers** [comment]
The disable-settings-authorizer does not seem to be a valid option in Dashboard 1.8.x?   

unknown flag: --disable-settings-authorizer

**Comment by jurgenweber** [comment]
works fine for me now that I have tried it.

```
      containers:
      - name: kubernetes-dashboard
        image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.8.2
        ports:
        - containerPort: 8443
          protocol: TCP
        args:
          - --auto-generate-certificates
          - --disable-settings-authorizer
```
