### ISSUE TITLE
Is it mandatory to grant full namespace list permission to a serviceaccount to create a resource via "CREATE AN APP" tab?

### ISSUE THREAD

**Issue by casevictor** [kubernetes/dashboard#2738]
##### Environment

```
Dashboard version: v1.9.0
Kubernetes version: v1.9.0 
Operating system: CentOS CE 7
Node.js version: -
Go version: 1.9.2
```

##### Steps to reproduce

1. Create a service account 

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {yourusername}-user
  namespace: kube-system
```

2. Attribute a role binding to the serviceaccount

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: admin-user
  namespace: {namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin // or admin
subjects:
- kind: ServiceAccount
  name: {yourusername}-user
  namespace: kube-system
```

3. Get de secret token and logged in into the web dashboard

4. Click on CREATE button and navigate to CREATE AN APP tab

5. Fill the form and try to DEPLOY

##### Observed result

The deploy button still unable even though the form is fulfilled

The kubctl logs on the dashboard pods shows

```
Non-critical error occurred during resource retrieval: namespaces is forbidden: User "system:serviceaccount:kube-system:learn-user" cannot list namespaces at the cluster scope
```

I guess it is ok because the service account does not have access to the others namespaces

I can create resources via TEXT or YAML, then I do not have permissions problems

##### Expected result

I expected to create a new resource via "CREATE AN APP" even though the user does not have full access to list the namespaces 

##### Comments

Cluster created via `kubadm` with RBAC rules enabled.
