### ISSUE TITLE
How to provide Dashboard Access to User created with openssl

### ISSUE THREAD

**Issue by ssubramanian123** [kubernetes/dashboard#2763]
Hi,
I have RBAC enabled cluster and deployed latest  Dashboard.  I need to create generic user account (like dev, qareadonly etc) with limited access to one or two namespaces. And the same user should able to access Dashboard. I dont want to share admin configs.

I have created user as below then with kubectl below user-context works fine. But I am not sure how to enable this config to dashboard. I tried with dashboard login with config, it does not work.  

(Note: I tried with Service Account, it works fine. But Service account is specific to one namespace, since I need to give access to more than one namespace not sure how to enable it)

Can anyone help me with the solution?

Here is the steps for creating user:

```kubectl create namespace office```

Create User :

```
openssl genrsa -out employee.key 2048
openssl req -new -key employee.key -out employee.csr -subj "/CN=employee/O=bitnami"
openssl x509 -req -in employee.csr -CA CA_LOCATION/ca.crt -CAkey CA_LOCATION/ca.key -CAcreateserial -out employee.crt -days 500
kubectl config set-credentials employee --client-certificate=/home/employee/.certs/employee.crt  --client-key=/home/employee/.certs/employee.key
kubectl config set-context employee-context --cluster=minikube --namespace=office --user=employee
kubectl --context=employee-context get pods
```

Created Role 

```
kind: Role
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    namespace: office
    name: deployment-manager
  rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["deployments", "replicasets", "pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]
```
RoleBinding

```
kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: deployment-manager-binding
    namespace: office
  subjects:
  - kind: User
    name: employee
    apiGroup: ""
  roleRef:
    kind: Role
    name: deployment-manager
    apiGroup: ""
```

With kubectl this works fine. 

```
kubectl --context=employee-context run --image bitnami/dokuwiki mydokuwiki
kubectl --context=employee-context get pods 
```
