### ISSUE TITLE
Raspberry Pi - kubernetes-dashboard-arm, ... is forbidden: User

### ISSUE THREAD

**Issue by jody-kpw** [kubernetes/dashboard#2783]
##### Environment
```
Raspberry Pi 3 Cluster
Dashboard version: kubernetes-dashboard-arm v1.8.2
Kubernetes version: 1.9.2
Operating system: Hypriot Version 1.7.1
```

##### Steps to reproduce
```
$ kubeadm init --apiserver-advertise-address=192.168.18.100
$ wget https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernetes-dashboard-arm.yaml
```

Edit kubernetes-dashboard-arm.yaml, change Dashboard Service added type: NodePort 

```
# ------------------- Dashboard Service ------------------- #

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9090
  selector:
    k8s-app: kubernetes-dashboard
```

```
$ kubectl -n kube-system get secret | grep kubernetes-dashboard-admin
```

kubernetes-dashboard-admin-token-kd4n2           kubernetes.io/service-account-token   3         12s
HypriotOS/armv7: pirate@rpi3-k8s-master01 in ~

```
$ kubectl describe -n kube-system secret/kubernetes-dashboard-admin-token-kd4n2
```

```
Name:         kubernetes-dashboard-admin-token-kd4n2
Namespace:    kube-system
Labels:       <none>
Annotations:  kubernetes.io/service-account.name=kubernetes-dashboard-admin
              kubernetes.io/service-account.uid=2e9e9337-fe66-11e7-9445-b827eb80ba1f

Type:  kubernetes.io/service-account-token

Data
====
ca.crt:     1025 bytes
namespace:  11 bytes
token:      xxxxxx.......
```

```
$ kubectl get svc --all-namespaces
```
Expose port: 30249

firefox:
192.168.18.100:30249/#!/login

##### Result
Success Logged In Dashboard But Error: 

http://192.168.18.100:30249/#!/overview?namespace=default
configmaps is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list configmaps in the namespace "default" 
....

http://192.168.18.100:30249/#!/cluster?namespace=default
namespaces is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list namespaces at the cluster scope
....
