### ISSUE TITLE
Secret environment variables are visible even when dashboard can only list secrets without reading their values

### ISSUE THREAD

**Issue by sjagoe** [kubernetes/dashboard#2798]
##### Environment

```
Dashboard version: 1.8.2
Kubernetes version: 1.8.7
Operating system: Debian Jessie
Node.js version:
Go version:
```

##### Steps to reproduce

1. Create a cluster role to allow the dashboard to list secrets, but not read them
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-cluster-resources
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-cluster-resources-binding
  labels:
    k8s-app: kubernetes-dashboard
subjects:
  - kind: ServiceAccount
    name: kubernetes-dashboard
    apiGroup: ""
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: list-cluster-resources
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dashboard-read
  labels:
    k8s-app: kubernetes-dashboard
subjects:
  - kind: ServiceAccount
    name: kubernetes-dashboard
    apiGroup: ""
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
```

2. Create a secret and a pod that uses it as an environment variable

```
apiVersion: v1
kind: Secret
metadata:
  name: very-secret-key
data:
  # echo -n security_key | base64
  security_key: c2VjdXJpdHlfa2V5
---
apiVersion: v1
kind: Pod
metadata:
  name: super-secret
  labels:
    name: super-secret
spec:
  containers:
    - name: super-secret
      image: busybox
      command:
        - /bin/sh
      args:
        - -c
        - while true; do date; sleep 60; done
      env:
        - name: SECURITY_KEY
          valueFrom:
            secretKeyRef:
              name: very-secret-key
              key: security_key
```

3. Visit the secrets list in the dashboard and confirm that the secret can be listed, but not read

4. Visit the pod in the dashboard, and click the eye icon next to the secret environment variable. The value is exposed.

##### Observed result

The value of secrets that the dashboard user does not have permission to read can be exposed through pod environment variables.

##### Expected result

Secret environment variables are only visible when the dashboard user is allowed to `get` secrets.
