### ISSUE TITLE
Signin with the kubeconfig created with gcloud container clusters get-credentials doesnt work

### ISSUE THREAD

**Issue by BoasE** [kubernetes/dashboard#2849]
##### Environment
I use a cluster which was created by the google container engine and has a preinstalled dashboard.
Since 1.8.x i need to prove a accesstoken or kubeconfig file via login maskl.

```
Dashboard version: v1.8.0 Git Commit:054916b8fbadebd32dc16d32108fdd3c9ccbf400
Kubernetes version1.8.7-gke.1
```

##### Steps to reproduce
I authenticated with ```gcloud container clusters get-credentials``` this creates a kubeconfig file with has this structure (I omitted the value)

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: ...
  name: ...
contexts:
- context:
    cluster: ...
    user: ...
  name: ...
current-context: ...
kind: Config
preferences: {}
users:
- name: ...
  user:
    auth-provider:
      config:
        access-token: ...
        cmd-args: config config-helper --format=json
        cmd-path: ...
        expiry: 2018-02-21T07:58:23Z
        expiry-key: ...
        token-key: ..
      name: gcp

```

##### Observed result
In the auth I select the created config file. auth does fail with : Not enough data to create auth info structure.

![image](https://user-images.githubusercontent.com/4619513/36468721-cffe7f7c-16e4-11e8-8c25-dea09dcd712f.png)

When i choose the accesstoken opton and copy and paste the accestoken from the file it works

##### Expected result
selecting the file that was created from get-credentials should work

**Comment by floreks** [comment]
Yep it won't work as below file structure is not currently supported.
```
auth-provider:
      config:
        access-token: ...
        cmd-args: config config-helper --format=json
        cmd-path: ...
        expiry: 2018-02-21T07:58:23Z
        expiry-key: ...
        token-key: ..
      name: gcp
```

We detect only simple token config in kubeconfig file:
```
- name: xxx
  user:
    token: xxx
```

**Comment by BoasE** [comment]
I tried to append the required syntax.
As a result i get   > found character that cannot start any token in the line where i placed token.

I assume i missunderstood the change that is needed

the section looks like this now:

```
users:
- name: [clustername]
  user:
	token: ...
- name: [clustername]
  user:
    auth-provider:
      config:
        access-token: ..
        expiry: 2018-02-21T09:15:02Z
        expiry-key: ..
        token-key: [value from access-token]
      name: gcp
```

could you show me how my configuration should be changed so it can be recognized?

**Comment by floreks** [comment]
Possibly apiserver processes `token` and `token-key` from `auth-provider` in a different way and it can not be used like that. It looks correct to me, but first token might be in a slightly different form then the other. That is why apiserver might not accept it this way.

**Comment by BoasE** [comment]
Do you think there is a realistic chance that the format will be supported soon ? Currently i could with copy and pasting the acceesstoken. So if in the future will be support this would be enough, at least for me

**Comment by floreks** [comment]
It is quite easy to add, however all feature work has been suspended during migration to Angular 5. We should have first beta version ready in a month, then we'll resume work on other issues. I'd say that at the moment we have migrated like 60% of app. If you are interested you can follow it in: https://github.com/kubernetes/dashboard/pull/2727#issuecomment-367277360.

**Comment by dermidgen** [comment]
@BoasE You _can_ use the token generated for you.  Take the `access-token` from the generated configuration and move it directly under `user` to `token`.  I recommend that you grab the cluster, context and user information and save it out to a new kubeconfig file to use for dashboard auth.

```
users:
- name: [clustername]
  user:
	token: [value from access-token]
- name: [clustername]
  user:
    auth-provider:
      config:
        access-token: ..
        expiry: 2018-02-21T09:15:02Z
        expiry-key: ..
        token-key: [value from access-token]
      name: gcp
```

becomes

```
users:
- name: [clustername]
  user:
	token: [value from access-token]
- name: [clustername]
  user:
    token: ...
```
