### ISSUE TITLE
Feature request / Resource quota namespace

### ISSUE THREAD

**Issue by Arslanbekov** [kubernetes/dashboard#2850]
I want to see through the dashboard how many quota resources are allocated to namespace. 
Let's add this information to the page with namespaces 👍

**Comment by floreks** [comment]
Such feature is already implemented.

Save it in a `quota.yaml` file.
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    pods: "4"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
```

Run:
`kubectl create -f quota.yaml --namespace=kube-public`

![zrzut ekranu z 2018-02-21 12-50-03](https://user-images.githubusercontent.com/2285385/36478648-ca8901c2-1705-11e8-8c99-d92d99108940.png)

`default` namespace with no quotas set:
![zrzut ekranu z 2018-02-21 12-50-10](https://user-images.githubusercontent.com/2285385/36478656-d444d506-1705-11e8-9493-154f28cab209.png)
