### ISSUE TITLE
Dashboard login does not authorize with valid config file

### ISSUE THREAD

**Issue by ssubramanian123** [kubernetes/dashboard#2874]
##### Environment
I have installed dashboard to my cluster using below URL.

kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

Now I am trying to login using my config file, but it is not allowing me to login and throws error as un-authrorized, attached screen shot with developer tool response.
![screen shot 2018-03-02 at 2 27 34 pm](https://user-images.githubusercontent.com/28627032/36922704-1c3c8a76-1e26-11e8-8931-7c4795b0042d.png)

My config file 

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {{certdata}}
    server: https://api.{mycluster_name}
  name: {mycluster_name}
contexts:
- context:
    cluster: {mycluster_name}
    user: {mycluster_name}
  name: {mycluster_name}
current-context: {mycluster_name}
kind: Config
preferences: {}
users:
- name: {mycluster_name}
  user:
    as-user-extra: {}
    client-certificate-data: {{certdata}}
    password: GlFP7KHi8KokfqFE3NNbsSnzUQil3f2F
    username: admin
- name: {mycluster_name}-basic-auth
  user:
    as-user-extra: {}
    password: GlFP7KHi8KokfqFE3NNbsSnzUQil3f2F
    username: admin

```
```
Dashboard version: 1.8 (latest version)
Kubernetes version:  1.8.8
Operating system: Mac
```

##### Steps to reproduce
Install latest dashboard and try login with valid config file

##### Observed result
Throws un-authorzied access error

##### Expected result
Login should works

##### Comments
Please let me know for any additional details.
