### ISSUE TITLE
UI main panel stuck with log view error for RBAC user who can't view logs

### ISSUE THREAD

**Issue by dsimonto** [kubernetes/dashboard#2913]
##### Environment
Dashboard is configured with TLS.
apiserver has RBAC enabled and a token file specified for authentication on startup
One token is for a user named "viewer"
The following role and role binding are applied to viewer:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: viewer-clusterrole
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  - storage.k8s.io
  resources:
  - deployments
  - pods
  - replicasets
  - statefulsets
  - services
  - configmaps
  - daemonsets
  - replicationcontrollers
  - jobs
  - namespaces
  - nodes
  - persistentvolumes
  - ingresses
  - events
  - persistentvolumeclaims
  - storageclasses
  verbs:
  - get
  - list
```

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: viewer-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: viewer-clusterrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: viewer
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: advanced
```
Dashboard version: 1.8
Kubernetes version: 1.7.4
Operating system: CentOS Linux release 7.4.1708 

##### Steps to reproduce
1. login as viewer using the viewer token
2. go to kube-system namespace
3. select logs on any pod
4. select namespace default now

##### Observed result
After selecting logs in step 3, the UI shows a message that viewing logs is not permitted for viewer, which is correct.  But changing namespace (step 4) from this state causes the UI to mess-up and the main content pane won't refresh; it keeps showing the log permission message no matter what you click on. There is not an easy way to get out of this state.

##### Expected result
Should be able to click on other items in the UI and have the display update.
