### ISSUE TITLE
does not show graph (heapster with dashboard)

### ISSUE THREAD

**Issue by Hokwang** [kubernetes/dashboard#3009]
##### Environment
all are latest version.
and I am in behind the proxy (enterprise).

Dashboard version:
1.8.3
$ kubectl version --short
Client Version: v1.10.2
Server Version: v1.10.2
Operating system: Ubuntu 16.04

##### Steps to reproduce
install heapster first,

$ git clone https://github.com/kubernetes/heapster.git
$ cd heapster/
$ kubectl create -f deploy/kube-config/influxdb/
$ kubectl create -f deploy/kube-config/rbac/heapster-rbac.yaml

and then install dashboard,
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernetes-dashboard.yaml

$ vi dashboard-admin.yaml
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard
  labels:
    k8s-app: kubernetes-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kube-system
```
$ kubectl create -f dashboard-admin.yaml
$ kubectl edit service kubernetes-dashboard -n kube-system
(change type to NodePort)

$ kubectl describe pod kubernetes-dashboard -n kube-system
(find out which node used and IP)

$ kubectl get services kubernetes-dashboard -n kube-system
(find out which port used)

I can access dashboard successfully http://{ip for node}:{port}
but, I can not see graphs.
(maybe heapster or dashboard has problem)

##### Observed result
$ kubectl logs kubernetes-dashboard-5c469b58b8-vg96b -n kube-system | tail
<snip>
2018/05/09 08:09:53 Metric client health check failed: an error on the server ("Error: 'EOF'\nTrying to reach: 'http://10.244.2.53:8082/healthz'") has prevented the request from succeeding (get services heapster). Retrying in 30 seconds.

##### Comments
I guess this is related proxy env.
and should I change type for heapster to NodePort ?
