### ISSUE TITLE
Cannot see md-icons from remote side by nodeport

### ISSUE THREAD

**Issue by sword-huang** [kubernetes/dashboard#3144]
##### Environment

```
Dashboard Version: v1.8.3 Git Commit: ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c 
Kubernetes version: v1.11.0
Operating system: Ubuntu 16.04
Node.js version: N/A
Go version: N/A
```

##### Steps to reproduce

1.run kubernetes dashboard: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
2.modify ClusterIp to NodePort: kubectl -n kube-system edit service kubernetes-dashboard
3.Open Firefox and go to https://10.32.25.96:30080/

##### Observed result

I cannot see the md-icons.
![The md-icons are not loading](https://upload.cc/i1/2018/07/16/qCoBEe.png)

##### Expected result

![The md-icons are loaded](https://upload.cc/i1/2018/07/16/CyzdG7.png)

##### Comments

If I use browser in kubernetes dashboard server to connect to the URL, I can see those icons.

**Comment by floreks** [comment]
Honestly, it is very hard to pin down this issue. It is most likely a networking or cluster issue and not Dashboard itself.

**Comment by chaosky** [comment]
This is a [chrome bug][chromium/issues#627143] that has not been fixed yet. This bug affects [material-design-icons](https://github.com/google/material-design-icons/blob/224895a86501195e7a7ff3dde18e39f00b8e3d5a/iconfont/material-icons.css), but currently material-design-icons seems to have been [abandoned](https://github.com/google/material-design-icons/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+chrome) and has not been updated for a long time.

You can modify [this css](https://github.com/google/material-design-icons/blob/224895a86501195e7a7ff3dde18e39f00b8e3d5a/iconfont/material-icons.css#L6-L7) file 
```css
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(MaterialIcons-Regular.eot); /* For IE6-8 */
  src: local('Material Icons'),
       local('MaterialIcons-Regular'),
       url(MaterialIcons-Regular.woff2) format('woff2'),
       url(MaterialIcons-Regular.woff) format('woff'),
       url(MaterialIcons-Regular.ttf) format('truetype');
}
```
to (just delete line 6 - 7)
```css
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(MaterialIcons-Regular.eot); /* For IE6-8 */
  src: 
       url(MaterialIcons-Regular.woff2) format('woff2'),
       url(MaterialIcons-Regular.woff) format('woff'),
       url(MaterialIcons-Regular.ttf) format('truetype');
}
```

After modification, both Chrome 75.0.3770.142 and Firefox 68.0.1 can be rendered ok for me (Ubuntu 18.04).

[chromium/issues#627143]:https://bugs.chromium.org/p/chromium/issues/detail?id=627143 "Issue 627143: @font-face src: local() should take *font face* name, not *family* name"

ref:
[dashboard angular.json](https://github.com/kubernetes/dashboard/blob/master/angular.json#L28)
[material icons self hosting](http://google.github.io/material-design-icons/#setup-method-2-self-hosting)
