### ISSUE TITLE
Getting pod metrics the server could not find the requested resource (get daemonsets.extensions)

### ISSUE THREAD

**Issue by kairatbmstu** [kubernetes/dashboard#3236]
```
Dashboard version: 1.1.0
Kubernetes version: 1.1.0
Operating system: Linux Centos 7
Go version: go version go1.10.3 linux/amd64
```
Hello!

We have kubernetes version 1.1.0, it's old version but it's running ok. 
I installed kubernets dashboard version 1.1.0.

```
kind: List
apiVersion: v1
items:
- kind: ReplicationController
  apiVersion: v1
  metadata:
    labels:
      app: kubernetes-dashboard-canary
      version: canary
    name: kubernetes-dashboard-canary
    namespace: kube-system
  spec:
    replicas: 1
    selector:
      app: kubernetes-dashboard-canary
      version: canary
    template:
      metadata:
        labels:
          app: kubernetes-dashboard-canary
          version: canary
      spec:
        containers:
        - name: kubernetes-dashboard-canary
          image: gcr.io/google_containers/kubernetes-dashboard-amd64:canary
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            protocol: TCP
          args:
            # Uncomment the following line to manually specify Kubernetes API server Host
            # If not specified, Dashboard will attempt to auto discover the API server and connect
            # to it. Uncomment only if the default does not work.
            - --apiserver-host=http://10.1.108.10:8080
          livenessProbe:
            httpGet:
              path: /
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: kubernetes-dashboard-canary
    name: dashboard-canary
    namespace: kube-system
  spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 9090
    selector:
      app: kubernetes-dashboard-canary

```

Dashboard is running, everything ok, except this error:
"Getting pod metrics the server could not find the requested resource (get daemonsets.extensions)"
Pod metrics is that stuff i need,  Cpu and Memory metrics do not work.

Should We update version of the kubernetes to make metrics work?  Or is  there  other ways to fix these problems?
Does kubernetes v1.1.0  support  cpu and memory metrics for dashboard?
