### ISSUE TITLE
Dashboard error: "proto: wrong wireType = 2 for field ShareProcessNamespace" when using limits in deployment

### ISSUE THREAD

**Issue by Tarik-M** [kubernetes/dashboard#3262]
##### Steps to reproduce

Installed nvidia-docker2 and all that follows.
Created yml file for cuda test:
```
apiVersion: apps/v1beta1  
kind: Deployment  
metadata:
  name: gpu-pod
  labels:
    name: gpu-pod
spec:
  selector:
    matchLabels:
      app: gpu-pod
  template:
    metadata:
      labels:
        app: gpu-pod
    spec:
      containers:
        - name: cuda-container
          image: nvidia/cuda:9.0-devel
          command: ["sleep"]
          args: ["100000"]
          resources: <-- This is the issue
            limits: <-- This is the issue
              nvidia.com/gpu: "1" <-- This is the issue
      nodeSelector:
        worker: worker1
```
`$kubectl create -f gpu-deployment.yml`

```
NAME                          READY     STATUS    RESTARTS   AGE       IP            NODE
gpu-pod-7574f55ffd-zq4c7      1/1       Running   0          9m 
```

##### Environment
```
Installation method: cli
Kubernetes version: 

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"df8604005af01c5f4b7d739d2cad61678d7582d2", GitTreeState:"clean", BuildDate:"2018-06-15T22:39:30Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"df8604005af01c5f4b7d739d2cad61678d7582d2", GitTreeState:"clean", BuildDate:"2018-06-15T22:39:30Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Dashboard version: v1.10.0
Commit: aa1b6c0c31c4b3b703e16e554a15ed2a019aad47
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
proto: wrong wireType = 2 for field ShareProcessNamespace

```

##### Comments

If I remove the resources.limits.nvidia.com/gpu: 1, The deployment works fine. The problem is that I need the runnning deployment use the limits otherwise the gpu won't be selected on a running pod. The deployment works fine otherwise but stops the dashboard from working.
