### ISSUE TITLE
ServiceAccount restricted to one namespace has access to all

### ISSUE THREAD

**Issue by AWKIF** [kubernetes/dashboard#3311]
##### Environment
```
Dashboard version: 1.10.0
Kubernetes version: 1.10.3
Operating system: debian 9
```

##### Steps to reproduce
Create a serviceaccount, ie:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredata
  namespace: coredata
```
Create a role and roleBinding with right to only one namespace, ie:
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: coredata
  namespace: coredata
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coredata
  namespace: coredata
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coredata
subjects:
- kind: ServiceAccount
  name: coredata
  namespace: coredata
```

Then i login to the dashboard through the token created by my serviceAccount "coredata", but i can list/access all ressources on all namespaces.

##### Expected result
Be able to list ressources only on specified namespace

##### Comments
I've been struggling for some times now. I guess read permissions are somewhere else and linked somehow to my serviceAccount but i don't see how.

Thanks a lot for any help
