### ISSUE TITLE
Secrets are still visible in kube-system namespace

### ISSUE THREAD

**Issue by asos-leslielintott** [kubernetes/dashboard#3325]
```
Dashboard version: 1.8.3
Kubernetes version: 1.11.2
Operating system: Ubuntu 16.04.5 LTS
Node.js version:
Go version:
```

With the following:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dashboard-user
rules:
- apiGroups: ["","extensions","apps","batch","storage.k8s.io","rbac.authorization.k8s.io"]
  resources: ["pods","services","deployments","namespaces","daemonsets","persistentvolumes","persistentvolumeclaims","configmaps","ingresses","cronjobs","jobs","replicasets","replicationcontrollers","statefulsets","storageclasses","events","roles","clusterroles"]
  verbs: ["get","list"]
```

and 

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dashboard-user
subjects:
  - kind: ServiceAccount
    name: kubernetes-dashboard
    namespace: kube-system
```

### Steps to reproduce
Deploy the above configurations and ensure that the kubernetes-dashboard service account is deployed and that the Dashboard deployment is running under the kubernetes-dashboard service account

### Observed result
I am still able to list and view secrets in the kube-system namespace.  I cannot list or view any secrets in any other namespaces

### Expected result
I should not be able to list or view any secrets in any namespace

### Comments
Is this because Dashboard needs access to its own namespace secrets in order to run?

**Comment by maciaszczykm** [comment]
This is an issue that we are aware of and has a high priority. Thank you for reporting anyways.

**Comment by jeefy** [comment]
Is this an RBAC issue in disguise?

From a clean slate (minikube) here's what I've done:

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
```

Create a file called perms.yaml
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-client
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dashboard-client
rules:
- apiGroups: ["","extensions","apps","batch","storage.k8s.io","rbac.authorization.k8s.io"]
  resources: ["pods","services","deployments","namespaces","daemonsets","persistentvolumes","persistentvolumeclaims","configmaps","ingresses","cronjobs","jobs","replicasets","replicationcontrollers","statefulsets","storageclasses","events","roles","clusterroles"]
  verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard-client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dashboard-client
subjects:
  - kind: ServiceAccount
    name: dashboard-client
    namespace: kube-system
```

Create the new User/Perms
```
kubectl apply -f perms.yaml
```

Copy the user's token, then start the proxy

```
kubectl -n kube-system describe secrets dashboard-client-token-xxxxx

kubectl proxy
```

From there, visit `http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/.` and supply the copied token.

<img width="1416" alt="screen shot 2018-11-13 at 11 47 55 pm" src="https://user-images.githubusercontent.com/1394552/48460798-a68e6900-e79e-11e8-9fc4-ce89fad71e3e.png">

If you're logging into the dashboard with admin rights, you're going to see everything. Or am I missing something obvious?
