### ISSUE TITLE
use groups provided by openid connect token instead of user

### ISSUE THREAD

**Issue by falcoriss** [kubernetes/dashboard#3395]
##### Environment

```
Dashboard version: 1.10
Kubernetes version: 1.12
Operating system: ubuntu 16.04
Node.js version: The one in the container i guess, I wanted to check but can't seem to attach the pod since there's no /bin/bash or /bin/sh
Go version: The one in the container i guess, I wanted to check but can't seem to attach the pod since there's no /bin/bash or /bin/sh

```

##### Steps to reproduce
    Have a working OpenID Connect set up (keycloak in my case)
    Get it working with kubectl with RBACs using groups
    Log in using token

##### Observed result
 configmaps is forbidden: User "https://keycloak.example.com/auth/realms/myrealm#my.user" cannot list resource "configmaps" in API group "" in the namespace "example" 

##### Expected result
Dashboard should use groups that are roledbound, not only user

##### Comments
Here are my RBAC : 
```
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: Group
  name: oidc_k8s-admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-dev
  namespace: example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: Group
  name: oidc_devs
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-readonly
  namespace: example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  name: oidc_others

```
