### ISSUE TITLE
Dashboard 1.10.1 breaks local kubeconfig

### ISSUE THREAD

**Issue by johnbyrneio** [kubernetes/dashboard#3438]
```
Dashboard version: 1.10.1
Kubernetes version: 1.10.9-gke.7
Kubectl version: 1.10.7
Operating system: 
- Cluster: Unknown, these are GKE nodes
- Client: Ubuntu 16.04
```

##### Steps to reproduce

1. Run `kubectl proxy`
2. Open Dashboard UI

##### Observed result
Active kubeconfig file has some configuration data removed

##### Expected result
Active kubeconfig file should be left alone

##### Comments

I installed dashboard version 1.10.1 on a GKE 1.10.9 cluster. I then started `kubectl proxy`. At that point, everything is fine. But as soon as I open the Dashboard in my browser, several lines of my active kubeconfig are removed.

- BEOFRE -

```
kind: Config
preferences: {}
users:
- name: gke_REDACTED_us-west2-a_cluster-1
  user:
    auth-provider:
      config:
        access-token: REDACTED
        cmd-args: config config-helper --format=json
        cmd-path: /home/ubuntu/google-cloud-sdk/bin/gcloud
        expiry: 2018-12-19T21:30:18Z
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

- AFTER -

```
kind: Config
preferences: {}
users:
- name: gke_REDACTED_us-west2-a_cluster-1
  user:
    auth-provider:
      config: {}
      name: gcp
```
