### ISSUE TITLE
Dashboard Fails to Read OIDC Tokens from Kubeconfig

### ISSUE THREAD

**Issue by ali-essam** [kubernetes/dashboard#3587]
Dashboard fails to detect OpenID Connect token in kubeconfig files while it allows logging in with `id-token` using the Token login method

##### Environment

```
Installation method: Helm
Kubernetes version: 1.13.3
Dashboard version: 1.10.1
```

##### Steps to reproduce
- Enable OIDC in Kube API
- Generate kubeconfig for a user (using kuberos for example)
- Configure RBAC for that user
- Try to login using the generated kubeconfig file

##### Observed result
Dashboard fails to login with error
```
Not enough data to create auth info structure.
```
![screenshot from 2019-02-20 12-25-30](https://user-images.githubusercontent.com/5252681/53085254-21d48900-350b-11e9-89c5-233af9640e29.png)

##### Expected result
Dashboard should be able to detect the `users[].auth-provider.config.id-token` and try to login with it. As it allows logging in with that same token using the Token login method

##### Comments
Sample `kubecfg.yaml`

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: REDACTED
  name: kube-dev.cluster.k8s.local
contexts:
- context:
    cluster: kube-dev.cluster.k8s.local
    user: REDACTED
  name: kube-dev.cluster.k8s.local
current-context: kube-dev.cluster.k8s.local
kind: Config
preferences: {}
users:
- name: REDACTED
  user:
    auth-provider:
      config:
        client-id: REDACTED.apps.googleusercontent.com
        client-secret: REDACTED
        id-token: REDACTED
        idp-issuer-url: https://accounts.google.com
        refresh-token: REDACTED
      name: oidc
```
