### ISSUE TITLE
Status of a job / reason why a job failed is missing in description

### ISSUE THREAD

**Issue by thomaspeitz** [kubernetes/dashboard#3648]
##### What would you like to be added
Currently dashboard shows the status of a job only in list view. This makes it out of UX perspective hard to find the reason why a job was not running.

Hovering the mouse over the "!" shows the reason. But this is hard to find and it was luck that i hovered it. Did not expect the reason there.
![image](https://user-images.githubusercontent.com/8327755/54201234-67aebc80-44cd-11e9-8fc8-f942e24d2f15.png)

I would expect the reason written down here as well:
![image](https://user-images.githubusercontent.com/8327755/54201288-8b720280-44cd-11e9-9d92-e54741af7655.png)

This shows a get job via yaml output:
```
status:
  conditions:
  - lastProbeTime: "2019-03-07T20:37:08Z"
    lastTransitionTime: "2019-03-07T20:37:08Z"
    message: Job was active longer than specified deadline
    reason: DeadlineExceeded
    status: "True"
    type: Failed
  startTime: "2019-03-07T20:30:08Z"
```

Those informations are missing from my perspective and should be added.

##### Why is this needed
Our developer use the dashboard to debug why a job was not running properly and fix it afterwards. It is hard to teach all devs to hover the icon to find out the reason why a cronjob failed.

##### Comments
I would like to contribute this by myself. Let me see if i get this done in a PR. If not I would ask for help here.
