### ISSUE TITLE
Dashboard Not Accessible Without Trailing Slash Ingress Subpath

### ISSUE THREAD

**Issue by Queuecumber** [kubernetes/dashboard#3888]
##### Environment

```
Installation method: kubeadm
Kubernetes version: 1.14.1
Dashboard version: 1.10.1
Operating system: Ubuntu
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce
Using any ingress, expose the dashboard to a non-root path e.g. example.com/dashboard

##### Observed result
Using any kind of ingress, exposing the dashboard on a subpath causes it to not work unless a trailing slash is manually prepended to the URL either by the user or with a rewrite rule.

##### Expected result
As with other applications, it should work with or without the trailing slash

##### Comments
Please don't close, I know this is claimed to be solved in several other contexts e.g. proxy and apiserver (by having them solve the problem), but it still isnt solved for ingress. 

I have this problem with both nginx-ingress and traefik so it isn't on their end. Workarounds for nginx are well documented (for example https://github.com/kubernetes/ingress-nginx/issues/683) but I haven't seen anything solving it for other ingresses and I've been unable to find a good solution for traefik. 

Since this problem occurs regardless of how the dashboard is getting accessed (apiserver, proxy, ingress), and other applications work fine on subpaths, this has to be a problem on the dashboard side. 

Please let me know what other information I can provide to assist in solving this bug, once and for all, and at the source.

**Comment by floreks** [comment]
I think it should be fairly easy to add. We are missing rewrite rule in our backend from `""` to `"/"`. Are you willing to work on that?

**Comment by Queuecumber** [comment]
Yeah I can probably do it, can you give me a tip on where to start looking?

**Comment by JayceCao** [comment]
Any progress on this? 🤔

**Comment by floreks** [comment]
Can you test on latest `v2.0.0-beta1`?

**Comment by JayceCao** [comment]
Deploy `v2.0.0-beta1` with official deployment yaml and then create a ingress-nginx with the following:
``` yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8sui-ingress
  namespace: kubernetes-dashboard
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    #nginx.ingress.kubernetes.io/configuration-snippet: rewrite ^(/k8s)$ $1/ permanent;
    #nginx.ingress.kubernetes.io/secure-backends: "true"
    #nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
  - hosts:
    - mydomain.com
    secretName: mydomain-com
  rules:
  - host: mydomain.com
    http:
      paths:
      - path: /k8s(/|$)(.*)
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 443
```
Everything works well :)
Here is the doc about the part of ingress-nginx configuration: https://kubernetes.github.io/ingress-nginx/examples/rewrite/

**Comment by Queuecumber** [comment]
I haven't investigated this fully yet but it is still a potential problem that you need to have that weird regex in the path field and the rewrite to $2. Other services work fine with a rewrite to / and a path like

```
path: /k8s
```

@floreks Did anyone add the missing rewrite to dashboard yet? I'm still waiting for a pointer on where the existing handlers are it wasn't obvious from a quick look at the code

**Comment by floreks** [comment]
@Queuecumber base handler that serves the application is created [here](https://github.com/kubernetes/dashboard/blob/master/src/app/backend/dashboard.go#L171). Probably, we would have to add rewrite rule from `''` to `'/'`.

**Comment by Queuecumber** [comment]
OK got it

**Comment by Queuecumber** [comment]
I did a bunch more investigation on this and I came to the conclusion that it's not actually your issue. First off, I switched to nginx-ingress and the rules seem to work fine, it turns out that a rule like

```
      http:
        paths:
          - path: /dash/?(.*)
            backend:
              serviceName: kubernetes-dashboard
              servicePort: http
```

is actually just what is required in nginx-ingress now, traefik still doesn't work but in my opinion if nginx-ingress works and it works the same way as other applications then its not you guys that are in the wrong its them. 

So I'm going to close this, sorry for the mistake
