### ISSUE TITLE
Problems with first login on kubernetes dashboard

### ISSUE THREAD

**Issue by kevingoos** [kubernetes/dashboard#3958]
##### Environment
```
Installation method: kubeadm
Kubernetes version: 1.14.3
Dashboard version: 1.10.1
Operating system: Debian 9.9.0
```

##### Steps to reproduce
**Install**
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/heapster.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/influxdb.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/rbac/heapster-rbac.yaml
```
**Setup the admin-user (following the wiki: https://github.com/kubernetes/dashboard/wiki/Creating-sample-user)** 

`vim dashboard-adminuser.yaml`
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kube-system
```
`vim dashboard-admin-binding.yaml`
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kube-system
```
**Apply user config:**
```
kubectl apply -f dashboard-adminuser.yaml
apply -f dashboard-admin-binding.yaml
```

**Get the token**
`kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep admin-user | awk '{print $1}')`

**Setup proxy for external hosts (because this runs on a server without GUI)**
`kubectl proxy --address 0.0.0.0 --accept-hosts='^.*$'`

##### Observed result

![image](https://user-images.githubusercontent.com/1328773/59962416-84538b00-94e5-11e9-819f-7f714e7335c1.png)

But the sign in button doesn't do anything...
Also I don't see a skip button like in the wiki!

##### Expected result
Possible to sign in an see the dashboard!
Also do I need to use this token everytime to login? Or is this only the first time?

##### Comments
I am not yet an export with kubernetes (still learning). This is the first cluster I am setting up! For now only 1 node (master node), and when this works properly I will add two extra nodes
