### ISSUE TITLE
Metrics not displaying in dashboard [v2 betas or master]

### ISSUE THREAD

**Issue by silverbackdan** [kubernetes/dashboard#4104]
##### Environment

Installation method: recommended methods with kubectl apply -f <url> - IO also then configure ingress with traefik and a dashboard user with ClusterRoleBinding
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-user
  namespace: kubernetes-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: dashboard-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: dashboard-user
    namespace: kubernetes-dashboard
```

Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

Dashboard version: tried with v2 beta1, beta2 and master
Operating system:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

Node.js version ('node --version' output): v8.10.0 (this was not installed but I've added it now restarted kubernetes dashboard and metrics scraper and still the same error)
Go version ('go version' output): same as node, this was not installed as it had not been listed as a requirements in the dashboard but I have now installed.  `go version go1.12.7 linux/amd64`

##### Steps to reproduce
install as recommended:
`kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta1/aio/deploy/recommended.yaml` (or beta2 or master)

ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-dashboard-ingress
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: kubernetes.silverbackwebapps.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 443
```

ClusterRoleBinding as provided above using kubectl appliy -f kube-dashboard-role-binding.yaml

##### Observed result
I have no errors in the metrics service pods but in the dashboard pod I get this error:
```
2019/07/22 09:18:13 Getting pod metrics
2019/07/22 09:18:13 Skipping metrics because of error: Received invalid number of resources from sidecar. Expected 2 received 0
```
I see a dash in the columns where the CPU Usage and Memory Usage should appear

##### Expected result
Information on CPU and memory usage should appear in the dashboard

##### Comments
I'm new to Kubernetes and if there are logs or information that may be useful that is missing, I'm happy to provide it. I imagine this is something to do with the migration from using Heapster or something and the fact I am using a non-release version but hopefully it will be solvable. Thanks for your time.
