### ISSUE TITLE
500 error  when use dashboard 

### ISSUE THREAD

**Issue by mysterytree** [kubernetes/dashboard#415]
![image](https://cloud.githubusercontent.com/assets/6166794/13247619/8033f7b0-da55-11e5-8c4e-88019e7bd839.png)
![image](https://cloud.githubusercontent.com/assets/6166794/13247623/884025dc-da55-11e5-82f8-6941ef563129.png)

and the rc.yaml
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: kubedash
  namespace: kube-system
  labels:
    k8s-app: kubernetes-dashboard 
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kubernetes-dashboard
  template:
    metadata:
      labels:
        k8s-app: kubernetes-dashboard
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kubernetes-dashboard
        image: gcr.io/google_containers/kubernetes-dashboard:canary
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 9090
        livenessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 5
```
service:
```
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
  labels:
    k8s-app: kubernetes-dashboard
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    k8s-app: kubernetes-dashboard 
  ports:
  - port: 50071
    targetPort: 9090
  type: LoadBalancer
  externalIPs:
  -  10.4.5.62
```
