### ISSUE TITLE
Internal Server Error (500)  connection refused

### ISSUE THREAD

**Issue by gemoya** [kubernetes/dashboard#418]
#### Issue details
Hi I deployed but I get error 500, 
namespace is setted as default beacause is the only namespace with default installation of kubenertes by yum on RHEL7
All of kubernetes is installed by yum.
##### Environment
All run by systemd using systemctl start service

```
Dashboard version: 1.0.0-beta1
Kubernetes version: kubernetes-1.2.0-0.6.alpha1.git8632732.el7.x86_64
Operating system: Red Hat Enterprise Linux Server release 7.2
Node.js version:
Go version:
```

##### Steps to reproduce

- Edit src/deploy/kubernetes-dashboard-canary.yaml  and change:
namespace to default and   externalIPs: - some_ip

##### Observed result

from dashboard 
`Internal Server Error (500)
Get http://localhost:8080/api/v1/replicationcontrollers: dial tcp [::1]:8080: getsockopt: connection refused`

but 
`curl http://localhost:8080
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/healthz",
    "/healthz/ping",
    "/logs/",
    "/metrics",
    "/resetMetrics",
    "/swaggerapi/",
    "/version"
  ]
`

##### Expected result

A default dashboard page

##### Comments

`KUBE_API_ADDRESS="--insecure-bind-address=127.0.0.1"

KUBE_API_PORT="--port=8080"

KUBE_ETCD_SERVERS="--etcd-servers=http://127.0.0.1:2379"

KUBE_SERVICE_ADDRESSES="--service-cluster-ip-range=10.254.0.0/16"

KUBE_API_ARGS="--secure-port=0"
KUBE_ADMISSION_CONTROL="--admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ResourceQuota"`

I am not sure if my case is a kubernetes api problem or dashboard problem.

Thanks.

**Comment by mysterytree** [comment]
https://github.com/kubernetes/dashboard/issues/415#issuecomment-188058386
may help you？

**Comment by gemoya** [comment]
I can't start canary service
my yaml:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-dashboard-canary
  name: dashboard-canary
#  namespace: kube-system
  namespace: default
spec:
  externalIPs:
  - 10.200.67.105
  ports:
  - port: 80
    targetPort: 9090
  selector:
    app: kubernetes-dashboard-canary
args:
  - --port=9090
  - --apiserver-host=10.254.0.1:8080
  command:
  - /dashboard
  - --port=9090
  - --apiserver-host=10.254.0.1:8080
```
and I got:
`yaml: line 54: did not find expected '-' indicator` 
where line 54 is - --apiserver-host=10.254.0.1:8080

**Comment by bryk** [comment]
@gemoya 

You should add `args: ["hello","world"]` to the ReplicationController part of the YAML file: https://github.com/kubernetes/dashboard/blob/master/src/deploy/kubernetes-dashboard-canary.yaml

**Comment by gemoya** [comment]
this makes an error for me:
`yaml: line 36: did not find expected key`
I think I am doing something wrong.

Thanks for patience and help

**Comment by bryk** [comment]
You need to specify apiserver-host param like this: 

```
kind: List
apiVersion: v1
items:
- kind: ReplicationController
  apiVersion: v1
  metadata:
    labels:
      app: kubernetes-dashboard-canary
      version: canary
    name: kubernetes-dashboard-canary
    namespace: kube-system
  spec:
    replicas: 1
    selector:
      app: kubernetes-dashboard-canary
      version: canary
    template:
      metadata:
        labels:
          app: kubernetes-dashboard-canary
          version: canary
      spec:
        containers:
        - name: kubernetes-dashboard-canary
          image: gcr.io/google_containers/kubernetes-dashboard-amd64:canary
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            protocol: TCP
          args:
            - --apiserver-host=http://foo.bar.baz:1234 
          livenessProbe:
            httpGet:
              path: /
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: kubernetes-dashboard-canary
    name: dashboard-canary
    namespace: kube-system
  spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 9090
    selector:
      app: kubernetes-dashboard-canary
```
