### ISSUE TITLE
Have a Warning Icon on a StatefulSet if the Pods can't be created

### ISSUE THREAD

**Issue by kimwnasptd** [kubernetes/dashboard#4205]
##### What would you like to be added
Have a warning icon instead of the green circle check for `StatefulSets` if the Pods cannot be created.

For example, if I create a `StatefulSet` with a non existent `ServiceAccount`, then the `StatefulSet` controller will not be able to create the Pod to the API Server. The problem is that the `StatefulSet`'s Status doesn't reflect that error and only shows `replicas: 0`. But, we can get this info by looking at the StatefulSet's `Events`.

##### Why is this needed
If the StatefulSet controller can't create the Pods, then the UI will show a green check which implies that the STS is OK. 

Althought, on the card it shows that there are 0/1 Pods available and I can see what is wrong if I click on the STS and see its Events. But I think it would be useful if the icon would be a warning to indicate that something is wrong.

##### Comments

You can check this behavior by creating this StatefulSet
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  replicas: 1
  serviceName: "nginx"
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: nonexistent-service-account-test
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
```
