### ISSUE TITLE
Container selectbox is reset in Log page after log is shown.

### ISSUE THREAD

**Issue by f-higashi** [kubernetes/dashboard#454]
#### Issue details

Although container selectbox has been changed, container selectbox is set to first value.

##### Environment

Dashboard version: cffd34a90ae4a2334db4f062202f3a00fdf73dc6 ( I used gulp serve:product)
Kubernetes version: v1.1.2
Operating system: Ubuntu 14.0.4
Node.js version: v5.2.0
Go version: 1.5.2
Browser: IE, chrome, firefox

##### Steps to reproduce

1. Create app which has mulit container in pod
    ex) upload from file which content the following

    ```
    apiVersion: v1
    kind: ReplicationController
    metadata:
    name: multiccontainer
    spec:
    replicas: 1
    template:
        metadata:
        labels:
            app: multiccontainer
        spec:
        containers:
        - name: nginx
            image: nginx
            resources:
            requests:
                cpu: 100m
                memory: 100Mi
        - name: jenkins
            image: jenkins
            resources:
            requests:
                cpu: 100m
                memory: 100Mi
        - name: gb-redisslave
            image: gcr.io/google_samples/gb-redisslave:v1
            resources:
            requests:
                cpu: 100m
                memory: 100Mi
    ```
2. Open log page of the pod
3. Change Conatiner to "jenkins" 

##### Observed result

Container selectbox is reset to the first container "nginx" after the "jenkins" log is shown.

##### Expected result

Container selectbox is set to "jenkins" when "jenkins" log is shown.
