### ISSUE TITLE
Dashboard 404 error

### ISSUE THREAD

**Issue by silverlight** [kubernetes/dashboard#4668]
##### Environment

```
Installation method: recommend
Kubernetes version: 16.3
Dashboard version: latest
Operating system: centOS
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce

I use ingress to expose dashborad service. I got a 404 error when I access the domain which point to dashboard service.
This is account yaml
```

apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kube-system

```
dashboard service and pod are up and healthy
##### Observed result

![image](https://user-images.githubusercontent.com/18061452/70897846-70b95500-202e-11ea-92d0-dff7aae1b892.png)

##### Comments
The log were keep printing this kind of message
![image](https://user-images.githubusercontent.com/18061452/70897921-98102200-202e-11ea-9a83-f4c3c1ee706c.png)
