### ISSUE TITLE
Change metrics graph duration and resolution

### ISSUE THREAD

**Issue by jonas27** [kubernetes/dashboard#4673]
<!-- Please use this template while reporting a bug and provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner. Thanks!-->

##### Environment
<!-- Describe your setup. Versions of Node.js, Go etc. are needed only from developers. -->

```
Installation method: kubeadm
Kubernetes version: 1.15.2
Dashboard version: Current Master
Operating system: Ubuntu 19.04
Node.js version ('node --version' output):
Go version ('go version' output): 1.12
```

##### Steps to reproduce
- install dashboard
- change the metric scraper args to

Flag | New values
-- | --
metric-resolution | `4m`
metric-duration | `60m`

with 
```
template:
  - spec:
    containers:
      - args:                                                                                                                                                                                                                                        
         - metric-resolution=4                                                                                                                                                                                                                        
         - metric-duration=60
```

##### Observed result
Dashboard still shows 15min time window for metrics with 1 min resolution

##### Expected result
60m time window with 4 min resolution.

##### Comments
Not sure if I have to change something in the dashboard deployment, but couldn't find any https://github.com/kubernetes/dashboard/blob/master/docs/common/dashboard-arguments.md
