### ISSUE TITLE
RBAC Not working as Expected. 

### ISSUE THREAD

**Issue by vishal8k** [kubernetes/dashboard#4678]
```
Kubernetes version: 1.14.8
Dashboard version: v2.0.0-beta6+0.g3175ce8
Operating system: Ubuntu
```

##### Steps to reproduce

Setup the dashboard using the following link:
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/
Creating Service Accounts, Roles and Role Binding for RBAC testing:
https://docs.giantswarm.io/guides/install-kubernetes-dashboard/

###### Observed result

I'm able to access all the resources when I login with token of the service account that the role is binded to. (The role provides read access only to pods)
##### Expected result
I should be displayed with an access denied or some kind of error when I try to access resources that is not defined in my role.

##### Comments

Below are my YAML files used to create roles,bindings, SA. 
**SERVICEACCOUNT.YAML**
```
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: kubernetes-dashboard
  name: rbacsa
```
**ROLE.YAML**
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbacrole
rules:
- apiGroups: [""] # core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

```
**BINDING.YAML**
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbacrolebinding
  namespace: kubernetes-dashboard
subjects:
  - kind: ServiceAccount
    name: rbacsa
    namespace: kubernetes-dashboard
roleRef:
  kind: ClusterRole
  name: rbacrole
  apiGroup: rbac.authorization.k8s.io

```
I've also posted this on stackoverflow but no progress there. Below is the link for the question.
https://stackoverflow.com/questions/59353819/how-to-bind-roles-with-service-accounts-kubernetes/59357208?noredirect=1#comment104934324_59357208
