### ISSUE TITLE
Pod logs became monochrome in v2.0.0-beta6

### ISSUE THREAD

**Issue by driusha** [kubernetes/dashboard#4714]
##### Environment

```
Installation method: our custom template based on https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta6/aio/deploy/recommended.yaml
Kubernetes version: v1.15.4
Dashboard version: v2.0.0-beta6
```

##### Steps to reproduce
1. Deploy Deployment with colored logs:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: color
spec:
  selector:
    matchLabels:
      app: color
  template:
    metadata:
      labels:
        app: color
    spec:
      containers:
      - image: ubuntu
        name: color
        command: ["/bin/bash", "-c", 'while true; do echo -e "Meet the \e[92mcucumber!"; sleep 1; done']
```
2. Go to pod logs and see monochrome logs with artifacts. 

##### Observed result
Monochrome logs:
![image](https://user-images.githubusercontent.com/18152319/71451597-c3131800-278a-11ea-93e6-76930814f5f7.png)

##### Expected result
Colored logs. As in dashboard v1.10.1:
![image](https://user-images.githubusercontent.com/18152319/71451602-d0300700-278a-11ea-8dcb-c26ee69903fb.png)
