### ISSUE TITLE
Service of type ExternalName shows as pending indefinitely

### ISSUE THREAD

**Issue by nielsbasjes** [kubernetes/dashboard#4736]
##### Environment

```
Installation method: Applied this yaml https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta8/aio/deploy/recommended.yaml
Kubernetes version: 1.17.0
Dashboard version: 2.0.0-beta8
Operating system: CentOS 7
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce
Create file pending-externalname.yaml with this content
```
apiVersion: v1
kind: Service
metadata:
  name: externalname-stays-pending
spec:
  externalName: niels.basjes.nl
  type: ExternalName
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
```

```
$ kubectl apply -f  pending-externalname.yaml 
service/externalname-stays-pending created
```

```
$ kubectl get svc externalname-stays-pending -o wide
NAME                         TYPE           CLUSTER-IP   EXTERNAL-IP       PORT(S)   AGE   SELECTOR
externalname-stays-pending   ExternalName   <none>       niels.basjes.nl   443/TCP   35s   <none>
```

##### Observed result
![image](https://user-images.githubusercontent.com/240096/71968745-ca640800-3205-11ea-9009-f64328cc9734.png)

The icon on the left shows as 'pending' (i.e. the grey incomplete circle) indefinitely.

##### Expected result

After the startup (which should be really really fast in this case) the icon changes to a green check.

![image](https://user-images.githubusercontent.com/240096/71969010-2af34500-3206-11ea-962a-66c8426eab14.png)

##### Comments

I suspect this has to do with the fact that an ExternalName will NOT get a ClusterIP at all.
