### ISSUE TITLE
Not able to login with token

### ISSUE THREAD

**Issue by devopstales** [kubernetes/dashboard#4983]
When I try to login with token I get: Unauthorized (401): Invalid credentials provided 

I see the following logs:
```
2020/03/08 15:03:32 [2020-03-08T15:03:32Z] Incoming HTTP/1.1 GET /api/v1/csrftoken/login request from 10.0.2.15:51242: { conte
nts hidden }
2020/03/08 15:03:32 [2020-03-08T15:03:32Z] Outcoming response to 10.0.2.15:51242 with 200 status code
2020/03/08 15:03:32 [2020-03-08T15:03:32Z] Incoming HTTP/1.1 POST /api/v1/login request from 10.0.2.15:51242: { contents hidde
n }
2020/03/08 15:03:32 Non-critical error occurred during resource retrieval: the server has asked for the client to provide cred
entials
2020/03/08 15:03:32 [2020-03-08T15:03:32Z] Outcoming response to 10.0.2.15:51242 with 200 status code
```

```
Installation method:
Based on this: https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta8/aio/deploy/recommended.yaml
Kubernetes version:
v1.16.1
Dashboard version:
v2.0.0-beta8
```

Only change in namespace:
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    fluxcd.io/ignore: "false"
    linkerd.io/inject: enabled
  name: kubernetes-dashboard
```

User:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kubernetes-dashboard

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kubernetes-dashboard
```

I am connecting trouth ingress with https:
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: ca-issuer
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
spec:
  tls:
    - hosts:
        - dashboard.k8s.intra
      secretName: kubernetes-dashboard-tls
  rules:
    - host: dashboard.k8s.intra
      http:
        paths:
          - backend:
             serviceName: kubernetes-dashboard
             servicePort: 443
```
