### ISSUE TITLE
Proxying the dashboard on a sub path broken

### ISSUE THREAD

**Issue by bashofmann** [kubernetes/dashboard#5017]
##### Environment

```
Installation method: Deployment in Kubernetes, behind an NGINX proxy
Kubernetes version: 1.17.4
Dashboard version: 2.0.0-rc6
```

##### Steps to reproduce
Deploy the dashboard and expose it with an nginx that proxies to that dashboard on a sub path, so that the dashboard can be reached by a URL like `https://some-host-name/kubernetes-dashboard`.

Sample nginx config:

```
server {
          listen 80;
          server_name some-host-name;

	  location = /kubernetes-dashboard {
		  return 302 https://$server_name/kubernetes-dashboard/;
	  }
	  location /kubernetes-dashboard/ {
		  set $upstream "kubernetes-dashboard.syseleven-kubernetes-dashboard.svc.cluster.local:80";
		  rewrite ^/kubernetes-dashboard(/.*) $1 break;
		  proxy_pass http://$upstream$uri$is_args$args;
		  proxy_http_version 1.1;
		  proxy_pass_request_headers on;
		  proxy_set_header Upgrade $http_upgrade;
		  proxy_set_header Connection $connection_upgrade;
	  }
}
```

##### Observed result
The dashboard should be proxied and load correctly.

##### Expected result
The main HTML can be loaded, but all CSS and JS files can't be loaded because their href is `https://some-host-name/some.css` instead of `https://some-host-name/kubernetes-dashboard/some.css`.

##### Comments
This used to work in 2.0.0-rc5, but started to break in 2.0.0-rc6, because the main HTML of 2.0.0-rc6 contains an additional `<base href="/">` tag, which was not present in 2.0.0-rc5. This is likely related to the Angular 9 upgrade.
With a bit of digging I was only able to change the base tag on built time, not on runtime. And I was not able to remove it completely again.
It's likely though that I overlooked an option :).

**Comment by floreks** [comment]
It might be related to the angular upgrade. Nothing related to that was changed by us intentionally. If it does not work then something had to change internally on the angular side.

**Comment by bashofmann** [comment]
It's definitely set in the `angular.json` now since this commit: https://github.com/kubernetes/dashboard/commit/4cab78cec824446427e7e3128dd713579d97f0ce#diff-24e9645f54bc8704f0daa8780c492a3fR13

**Comment by floreks** [comment]
It's interesting because kubectl proxy seems to have a way to override base href.

![Zrzut ekranu z 2020-03-19 18-14-59](https://user-images.githubusercontent.com/2285385/77095053-aabf3c00-6a0d-11ea-8c27-e2437067f819.png)

**Comment by bashofmann** [comment]
If I remember correctly `kubectl proxy` has some logic to rewrite all links, hrefs etc.

**Comment by floreks** [comment]
Maybe nginx also offers a way to do that. It might be tricky to change that on our side, as localization framework that angular offers has changed significantly in v9 and it is responsible for this change. We have to find out if we can somehow omit `baseHref` and still be able to rely only on `Accept-Language` header.

**Comment by bashofmann** [comment]
Yes, something like this is also possible with nginx (https://nginx.org/en/docs/http/ngx_http_sub_module.html).

**Comment by universam1** [comment]
We can confirm that with `RC-6` the `baseHref = /` breaks the possiblity to move to a subpath.
With RC-5 however it does work. 
Guess we should consider this a bug?

**Comment by floreks** [comment]
I would not consider this a bug just yet. It depends if angular offers a way to handle locale like it was done in v8, without specifying `baseHref`. If this change was intentional and `baseHref` is required now, then there is nothing we can do. You'll have to handle that on your side. Most proxies should offer a way to do that.

**Comment by vutny** [comment]
It is a pity that we need to apply weird workarounds for simple URL rewriting.
I managed to get it working on `/dashboard` path with Nginx Ingress by following manifest:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-dashboard
  labels:
    app.kubernetes.io/name: kubernetes-dashboard  
  annotations:
    kubernetes.io/ingress.class: nginx
    # Add https backend protocol support for ingress-nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Accept-Encoding "";
      sub_filter '<base href="/">' '<base href="/dashboard/">';
      sub_filter_once on;
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: my.example.com
      http:
        paths:
          - path: /dashboard(/|$)(.*)
            backend:
              serviceName: kubernetes-dashboard
              servicePort: 443
```

**Comment by floreks** [comment]
I have created an issue on angular side: https://github.com/angular/angular-cli/issues/17260

Let's see if this behavior can be improved. After checking cli code, I do not see a way to omit this logic. `<base>` tag is always added to the `index.html` if localization framework is used. I would like to avoid that, or have a way to configure it somehow and use relative paths.

**Comment by yonatankahana** [comment]
update to @vutny, for kubernetes >=1.19 use:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingresscat
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
  labels:
    app.kubernetes.io/name: kubernetes-dashboard
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Accept-Encoding "";
      sub_filter '<base href="/">' '<base href="/dashboard/">';
      sub_filter_once on;
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /dashboard(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 443
```

**Comment by jjournet** [comment]
Hi @floreks , I see that there is a fix for this issue (March 2020...) but how do you configure it ? I went through the doc, github and the fix , and couldn't find the right way to configure it.

thanks @yonatankahana and @vutny  for the work around

**Comment by usersina** [comment]
Also note that the order of `nginx.ingress.kubernetes.io/rewrite-target` and `nginx.ingress.kubernetes.io/configuration-snippet` matters for anyone bumping their head ^^'

**Comment by usefss** [comment]
> update to @vutny, for kubernetes >=1.19 use:
> 
> ```yaml
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   name: kubernetes-dashboard
>   namespace: kubernetes-dashboard
>   labels:
>     app.kubernetes.io/name: kubernetes-dashboard
>   annotations:
>     nginx.ingress.kubernetes.io/backend-protocol: HTTPS
>     nginx.ingress.kubernetes.io/configuration-snippet: |
>       proxy_set_header Accept-Encoding "";
>       sub_filter '<base href="/">' '<base href="/dashboard/">';
>       sub_filter_once on;
>     nginx.ingress.kubernetes.io/rewrite-target: /$2
> spec:
>   ingressClassName: nginx
>   rules:
>     - http:
>         paths:
>           - path: /dashboard(/|$)(.*)
>             pathType: Prefix
>             backend:
>               service:
>                 name: kubernetes-dashboard
>                 port:
>                   number: 443
> ```

How exactly does this work?
It supposed to add a base href /dashboard tag to the raw base html??

**Comment by webcoderz** [comment]
tried this a bunch of different ways in my nginx reverse proxy but still to no avail :(
```
        location ~ /k8s/dash/ {
                set $backend    "http://kubernetes-dashboard.kubernetes-dashboard.svc.cluster.local/";
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            rewrite ^/k8s/dash(/.*) /$2 break;
            proxy_set_header Accept-Encoding "";
            sub_filter '<base href="/">' '<base href="http://kubernetes-dashboard.kubernetes-dashboard.svc.cluster.local/">';
            sub_filter_once off;
            rewrite ^/k8s/dash/(.*\.(js|css|png|gif|svg|ttf|eot|woff|woff2))$ /$2 last; 
            include       /etc/nginx/mime.types;
            proxy_pass $backend;
        }
  
```

**Comment by webcoderz** [comment]
> tried this a bunch of different ways in my nginx reverse proxy but still to no avail :(
> 
> ```
>         location ~ /k8s/dash/ {
>             set $backend    "http://kubernetes-dashboard.kubernetes-dashboard.svc.cluster.local/";
>             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>             proxy_set_header X-Real-IP $remote_addr;
>             proxy_set_header Host $http_host;
>             proxy_set_header Upgrade $http_upgrade;
>             proxy_set_header Connection "upgrade";
>             rewrite ^/k8s/dash(/.*) /$2 break;
>             proxy_set_header Accept-Encoding "";
>             sub_filter '<base href="/">' '<base href="http://kubernetes-dashboard.kubernetes-dashboard.svc.cluster.local/">';
>             sub_filter_once off;
>             rewrite ^/k8s/dash/(.*\.(js|css|png|gif|svg|ttf|eot|woff|woff2))$ /$2 last; 
>             include       /etc/nginx/mime.types;
>             proxy_pass $backend;
>         }
>   
> ```

after hours of tinkering i figured it out:

```
location ~* "^/k8s/dashboard(/|$)(.*)" {
            proxy_set_header Accept-Encoding "";
            sub_filter '<base href="">' '<base href="/k8s/dashboard/">';
            sub_filter_once on;
            rewrite "(?i)/k8s/dashboard(/|$)(.*)" /$2 break;
            proxy_pass $backend;
            proxy_redirect off;
        }
```

how i figured it out : launched the ingress for it and then looked at the /etc/nginx/nginx.conf of the ingress controller and then took the ingress specific stuff out

**Comment by luchillo17** [comment]
I know this is an old issue, but I'm wondering how the `sub_filter` approach compares to a rewrite redirect? https://github.com/kubernetes/dashboard/issues/7616#issuecomment-1573320650

**Comment by imranrazakhan** [comment]
> update to @vutny, for kubernetes >=1.19 use:
> 
> ```yaml
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   name: kubernetes-dashboard
>   namespace: kubernetes-dashboard
>   labels:
>     app.kubernetes.io/name: kubernetes-dashboard
>   annotations:
>     nginx.ingress.kubernetes.io/backend-protocol: HTTPS
>     nginx.ingress.kubernetes.io/configuration-snippet: |
>       proxy_set_header Accept-Encoding "";
>       sub_filter '<base href="/">' '<base href="/dashboard/">';
>       sub_filter_once on;
>     nginx.ingress.kubernetes.io/rewrite-target: /$2
> spec:
>   ingressClassName: nginx
>   rules:
>     - http:
>         paths:
>           - path: /dashboard(/|$)(.*)
>             pathType: Prefix
>             backend:
>               service:
>                 name: kubernetes-dashboard
>                 port:
>                   number: 443
> ```

With Azure Ingress Controller you can fix subpath issue like below

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-dashboard
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
spec:
  rules:
    - http:
        paths:
          - path: /dashboard/*
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 9090       
```
