### ISSUE TITLE
Pod ip doesn't match endpoint ip

### ISSUE THREAD

**Issue by duylong** [kubernetes/dashboard#5052]
Hi,

I have a issue with a dualstack cluster:
```
E0406 09:30:08.733846       1 rest.go:534] Address {fd00:10:255:x:x:x:x:x 0xc00f8e6150 0xc00f37af50} isn't valid (pod ip doesn't match endpoint ip, skipping: 10.255.x.x vs fd00:10:255:x:x:x:x:x (kubernetes-dashboard/dashboard-metrics-scraper-7b56dfc754-4qmn7))
E0406 09:30:08.733872       1 rest.go:544] Failed to find a valid address, skipping subset: &{[{fd00:10:255:x:x:x:x:x  0xc00f8e6150 0xc00f37af50}] [] [{ 8000 TCP <nil>}]}
```

My service:
```
kubernetes-dashboard   dashboard-metrics-scraper    ClusterIP      fd00:10:96::x <none>                           8000/TCP                        3d1h    k8s-app=dashboard-metrics-scraper
kubernetes-dashboard   kubernetes-dashboard         LoadBalancer   fd00:10:96::x <none> 8001:32685/TCP                  3d1h    k8s-app=kubernetes-dashboard
```

However, I configured the correct ipv6 family:
```
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: dashboard-metrics-scraper
  name: dashboard-metrics-scraper
  namespace: kubernetes-dashboard
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    k8s-app: dashboard-metrics-scraper
  ipFamily: IPv6
```

```
Kubernetes version: 1.18
```

Do you have also this issue?
