### ISSUE TITLE
Create from file support a github yaml file url

### ISSUE THREAD

**Issue by cifc** [kubernetes/dashboard#5079]
##### What would you like to be added
Create from file support a github yaml file url

**Comment by maciaszczykm** [comment]
This is a very low priority in my opinion. You can always copy whole file and paste it into input. Also, there are other pages with resource YAMLs.

**Comment by floreks** [comment]
Also, many clusters have restricted access to the internet or are fully hosted inside a private network without access to the outside at all. The current options will always work for everyone.

**Comment by shu-mutou** [comment]
We can load files from internet on browser. How about adding `Load` button into yaml editor on dashboard. It's easier than getting file from inside cluster. Also, it would enable to edit yaml immediately.

**Comment by willzhang** [comment]
it can be a local network url, and sometimes some easy app just have one yaml file ,like calico ,flannel.

and you also can just put all contents in one yaml file,like this ,run a demo app quickly:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-app
spec:
  selector:
    matchLabels:
      run: my-nginx-app
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx-app
    spec:
      containers:
      - name: my-nginx-app
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-app
  labels:
    run: my-nginx-app
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targatePort: 80
    nodePort: 30080
  selector:
    run: my-nginx-app
```

and you will see there are many example at official website

https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/controllers/nginx-deployment.yaml
