### ISSUE TITLE
Pod is not show up in the dashboard if deploy via YAML file

### ISSUE THREAD

**Issue by gembin** [kubernetes/dashboard#523]
#### Issue details

Pod is not  show up in the dashboard if deploy via YAML file.

There are two ways to deploy a Containerized App using dashboard

* Specify app details below
    Pod is running, and shows in the dashboard (work as expected)

* Upload a YAML or JSON file
    Pod is running, but *NOT* shows in the dashboard (not work as expected)

##### Environment
```
Dashboard version:  gcr.io/google_containers/kubernetes-dashboard-amd64:canary
Kubernetes version: v1.1.8
Operating system: CoreOS 976.0.0
```

##### Steps to reproduce

Deploy a app by uploading a YAML.
hello.yaml
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  restartPolicy: Always
  containers:
  - name: hello
    image: "gliderlabs/alpine:3.3"
    command: ["/bin/sleep","9000"]
```

The pod is running, but not show in the dashboard
```bash
kubectl get pods
NAME           READY     STATUS    RESTARTS   AGE
hello-pod      1/1       Running   0          17m
```

I'm new to k8s, not sure if I missed something.
