### ISSUE TITLE
Readonly Dashboard permission still has edit access

### ISSUE THREAD

**Issue by Sjnahak** [kubernetes/dashboard#5271]
```
Installation method: Via Kubeadam
Kubernetes version: v1.18.0
Dashboard version: 2.0.0
Operating system: Rhel 7
```
##### Comments
Readonly Permission  for kubernetes dashboard  does not work as expected

I have created readonly cluster role but still the service account has edit access to the resources.
Modified existing Cluster role to test but still it has edit access.
Please find the sample below
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
rules:
  # Allow Metrics Scraper to get metrics from the Metrics server
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs: ["get", "list", "watch"]
```

![Readonly-issue](https://user-images.githubusercontent.com/33506659/84844498-1a25e580-b068-11ea-8dfe-6cd8520d77c2.PNG)
