### ISSUE TITLE
Restore Helm CI jobs

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#5280]
Most of the build pipeline has been migrated to the Github Workflows. The only things left are helm linting and repo generation.

Old code from `.travis.yml`
```yaml
 - name: "Helm linting"
      cache: false
      install:
        - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        - wget https://github.com/garethr/kubeval/releases/download/0.14.0/kubeval-linux-amd64.tar.gz
        - mkdir kubeval
        - tar xf kubeval-linux-amd64.tar.gz -C kubeval
        - export PATH="$PATH:$(pwd)/kubeval"
      before_script: skip  # We don't need Docker nor Go
      script:
        - aio/scripts/helm-lint.sh
...
    # Manual step for now since it requires to add a GitHub Token to Travis which would be a security issue
    # - name: "Helm repository generation"
    #   cache: false
    #   install:
    #     - curl -L https://git.io/get_helm.sh | bash && helm init --skip-refresh --client-only
    #     - git remote set-branches origin '*' && git fetch --unshallow
    #     # GTHUB_WRITE_TOKEN is a travis secret variable that is generated from https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
    #     - git remote set-url origin https://x-access-token:${GITHUB_WRITE_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
    #   before_script: skip  # We don't need Docker nor Go
    #   script:
    #     - sh ./aio/scripts/
```
