### ISSUE TITLE
kubernetes-dashboard CrashLoopBackOff on Centos 7.8

### ISSUE THREAD

**Issue by tonymmm1** [kubernetes/dashboard#5322]
##### Environment

```
Installation method: Manual
Kubernetes version:  1.18.5
Dashboard version: 2.03
Operating system: Centos 7.8 
Kernel: 3.10.0-1127.13.1.el7.x86_64
```

##### Steps to reproduce

1. Installing manual method for kubernetes and cli tools.
2. wget https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.3/aio/deploy/recommended.yaml
3. Edit recommended.yaml to allow for NodePort operation 
```
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 8443
      nodePort: 31950
  selector:
    k8s-app: kubernetes-dashboard
```
4. kubectl apply -f recommended.yaml
5. kubectl get deployments -n kubernetes-dashboard
```
NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
dashboard-metrics-scraper   1/1     1            1           9m44s
kubernetes-dashboard        0/1     1            0           9m44s
```
##### Observed result

kubectl get pods -A -o wide
```
kubernetes-dashboard   dashboard-metrics-scraper-6b4884c9d5-rtbtl   1/1     Running            0          10m     10.244.1.9    k8s-2   <none>           <none>
kubernetes-dashboard   kubernetes-dashboard-7f99b75bf4-rhmzr        0/1     CrashLoopBackOff   6          10m     10.244.2.10   k8s-1   <none>           <none>
```

kubernetes-dashboard error CrashLoopBackOff
##### Expected result

The dashboard should be running as state in the documentation about the NodePort.
##### Comments

If there is any configuration issue or anything pertaining to Kubernetes or Centos 7.8, feedback or help would be appreciated.
