### ISSUE TITLE
ConfigMap settings are hidden by default

### ISSUE THREAD

**Issue by WoLpH** [kubernetes/dashboard#5351]
##### Environment

Kubernetes running on Digitalocean

```
Installation method: `kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.3/aio/deploy/recommended.yaml`
Kubernetes version: 1.18.3-do.0
Dashboard version: v2.0.0+0.g1f66b1c
```

##### Steps to reproduce

1. Configure a pod using a configmap, something like this:

```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  namespace: default
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu
    envFrom:
      - configMapRef:
          name: some-config-map
```

2. Go to Kubernetes Dashboard and look at the environment variables:

![image](https://user-images.githubusercontent.com/270571/87104688-f4e85980-c258-11ea-8f1d-f311844b050e.png)

Since configmaps as opposed to secrets aren't supposed to be secret they shouldn't be hidden.

##### Observed result

Hidden variables

##### Expected result

Plainly visible variables
