### ISSUE TITLE
when login  the plugin/config response is 401

### ISSUE THREAD

**Issue by yunsonbai** [kubernetes/dashboard#5378]
1. kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml

2. kubectl get pods -A:
kubernetes-dashboard   dashboard-metrics-scraper-6b4884c9d5-7df49                          1/1     Running   0          27m
kubernetes-dashboard   kubernetes-dashboard-7b544877d5-kshb7                               1/1     Running   0          27m

3. edit  dashboard-adminuser.yaml

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kubernetes-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kubernetes-dashboard
```

4. kubectl apply -f dashboard-adminuser.yaml

5. kubectl proxy --disable-filter=true --address=0.0.0.0

6. in chrome I input http://xx.xx.xx.xx:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login

7. kubectl -n kubernetes-dashboard describe secret $(kubectl -n kubernetes-dashboard get secret | grep admin-user | awk '{print $1}')

```
token:      eyJhbGciOiJSUzI1NiIsImtpZCI6InRHQzNCT29ncjA3Q0VMV1FcmV0Lm5hbWUiOiJhZG1pbi11c2VyLXRva2VuLW1ieGxmIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFkbWluLXVzZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjbQGsJIRbe_A3VudC51aWQiOiI2Mzk4YzcyNS1hZjRhLTQwMjgtOWVlNS01YWI2MDcwZWVmN2QiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZXJuZXRlcy1kYXNoYm9hcmQ6YWRtaW4tdXNlciJ9.L6D9RVHXXiEHjLdY_By-HsO9t60ysf2xim73p_fV5WL4SZbie-rqsKD8EePZ5Eug1xC9DRf4nURbfVg9P-7yO-qXArqhf9TpG5FznN_AECNYuYZy_GdHsFrfacz8Yr3ViOyUF07phZXzlYUHdkMHVZM0F3clh3em1fREVBblRTLTQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjpEnBtIpqz8uNZRdvKapQ0d50k1oLF0aBzrWbfZXN-FGeQ3zS5XeVTor6uoEEIZSP6UwpPHKePN0v2UsqkEjze-7VLevomJlTIDM-vj_4rMIl1TK4nejzms3l5AnxDqjVbovR41UHKeDnz6IxJE3eOFrxjmHzS13cuzYaj3-6VwkGap0SkSunAhstREq2TiAl4Pw
```

8. input token to chrome

```
eyJhbGciOiJSUzI1NiIsImtpZCI6InRHQzNCT29ncjA3Q0VMV1FcmV0Lm5hbWUiOiJhZG1pbi11c2VyLXRva2VuLW1ieGxmIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFkbWluLXVzZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjbQGsJIRbe_A3VudC51aWQiOiI2Mzk4YzcyNS1hZjRhLTQwMjgtOWVlNS01YWI2MDcwZWVmN2QiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZXJuZXRlcy1kYXNoYm9hcmQ6YWRtaW4tdXNlciJ9.L6D9RVHXXiEHjLdY_By-HsO9t60ysf2xim73p_fV5WL4SZbie-rqsKD8EePZ5Eug1xC9DRf4nURbfVg9P-7yO-qXArqhf9TpG5FznN_AECNYuYZy_GdHsFrfacz8Yr3ViOyUF07phZXzlYUHdkMHVZM0F3clh3em1fREVBblRTLTQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjpEnBtIpqz8uNZRdvKapQ0d50k1oLF0aBzrWbfZXN-FGeQ3zS5XeVTor6uoEEIZSP6UwpPHKePN0v2UsqkEjze-7VLevomJlTIDM-vj_4rMIl1TK4nejzms3l5AnxDqjVbovR41UHKeDnz6IxJE3eOFrxjmHzS13cuzYaj3-6VwkGap0SkSunAhstREq2TiAl4Pw
```

but i get this（How to solve ?）:
<img width="1428" alt="a" src="https://user-images.githubusercontent.com/9428337/87795952-51600000-c87b-11ea-8e8c-066493ef0e08.png">
