### ISSUE TITLE
istio: Metric client health check failed: the server is currently unable to handle the request (get services dashboard-metrics-scraper). Retrying in 30 seconds.

### ISSUE THREAD

**Issue by toonsevrin** [kubernetes/dashboard#5440]
After enabling istio on the kubernetes-dashboard namespace I receive the following error:
```
2020/08/16 20:00:58 Metric client health check failed: the server is currently unable to handle the request (get services dashboard-metrics-scraper). Retrying in 30 seconds.
```

**dashboard version**: 2.0.3 (note that I was running an older version and the error was also present there)
**kubernetes distribution**: k3s (shouldn't be relevant)

I've rebuilt dashboard with an alpine image and kubectl works nicely within the container. I can run `kubectl get services` without a problem and the dashboard-metrics-scraper pods are in `ready` state.

Note that the apiserver is explicitly defined as a virtualservice. If I remove this resource, dashboard is not able to access the kubernetes API at all for some reason (neither is kubectl).

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kubernetes
spec:
  hosts:
  - kubernetes.default.svc.cluster.local
  tls:
  - match:
    - port: 443
      sniHosts: 
      - kubernetes.default.svc.cluster.local
    route:
    - destination:
        host: kubernetes.default.svc.cluster.local
```

My apoligies if istio-related issues are not discussed here! I'm willing to run any debug steps you provide, thanks in advance :)
