### ISSUE TITLE
value of "filedpath" in environment variables is empty in kubernetes dashboard

### ISSUE THREAD

**Issue by irniaxsep** [kubernetes/dashboard#5443]
The pod template:

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busybox
  namespace: kube-system
  labels:
    k8s-app: busybox
spec:
  selector:
    matchLabels:
      name: busybox
  template:
    metadata:
      labels:
        name: busybox
    spec:
      containers: 
      - name: busybox
        image: k8s.gcr.io/busybox
        env:
          **- name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP**

However, on kubernetes dashboard the value is empty:
![image](https://user-images.githubusercontent.com/9164629/90491601-b6f12600-e172-11ea-8073-43d48572aecb.png)

Will the host IP displayed on the dashboard.

**Comment by floreks** [comment]
If it's empty, then it means... well, that it is empty.

Try this test pod and see that `fieldPath` is displayed properly.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: env-variables
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "sh", "-c"]
      args:
      - while true; do
          echo -en '\n';
          printenv MY_POD_NAME;
          printenv MY_MEM_REQUEST MY_MEM_LIMIT;
          printenv MY_CONST_VALUE;
          printenv MY_SECRET_VALUE;
          sleep 10;
        done;
      resources:
        requests:
          memory: "32Mi"
          cpu: "125m"
        limits:
          memory: "64Mi"
          cpu: "250m"
      env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_MEM_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: test-container
              resource: requests.memory
        - name: MY_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: test-container
              resource: limits.memory
```
