### ISSUE TITLE
On plain HTTP settings the metrics-server's readiness/liveness probe fails

### ISSUE THREAD

**Issue by zzvara** [kubernetes/dashboard#5472]
##### Environment

```
Installation method: HelmRelease
Kubernetes version: 1.17.0
Dashboard version: Helm Chart version 2.3.0
Operating system: CoreOS latest
Node.js version ('node --version' output): -
Go version ('go version' output): -
```

##### Steps to reproduce

1. Install with HelmRelease using the following settings:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  chart:
    repository: https://kubernetes.github.io/dashboard/
    name: kubernetes-dashboard
    version: 2.3.0
  releaseName: kubernetes-dashboard
  values:
    protocolHttp: true
    metricsScraper:
      enabled: true
    metrics-server:
      enabled: true
    service:
      externalPort: 9090
    extraArgs:
      - '--enable-insecure-login'
      - '--namespace=kube-system'
      - '--token-ttl=864000'
      - '--insecure-bind-address=0.0.0.0'
      - '--insecure-port=9090'
```

##### Observed result

1. Then Kubernetes dashboard may be exposed through Traefik. Traefik provides TLS termination. It works.
2. kubernetes-dashboard-metrics-server Pod fails with "Readiness probe failed: HTTP probe failed with statuscode: 500"
Logs indicate it serves on SSL, but HTTP probe is used: 
`I0826 12:24:50.313284       1 secure_serving.go:116] Serving securely on [::]:844`

##### Expected result

kubernetes-dashboard-metrics-server Pod probes should succeed
