### ISSUE TITLE
Secrets are accessible even when RBAC for secrets is not allowed

### ISSUE THREAD

**Issue by JakubJecminek** [kubernetes/dashboard#5494]
##### Environment

```
Installation method: 
Kubernetes version:  1.14
Dashboard version: 2.0.3
Operating system: Amazon Linux
```

##### Steps to reproduce
Create service account that is mapped to role with following RBAC settings:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-role
rules:
  - apiGroups:
      - ""
      - apps
      - core
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
    resources:
      - componentstatuses
      - configmaps
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
      - services/proxy
    verbs:
      - "get"
      - "list"
      - "watch"
      - "head"
  - nonResourceURLs: ["*"]
    verbs:
      - get
      - watch
      - list
```

##### Observed result
**Notice that secrets are not listed in resources section.**
With such role when trying to access secrets through kubectl I correctly receive error:
`Error from server (Forbidden): secrets is forbidden: User "developer:xxx" cannot list resource "secrets" in API group "" in the namespace "default"`

Assigning this role to service account and accessing dashboard using this account (bearer token added to authorization header) will result in read-only access, which is correct. But I can still access (list) secrets and also see individual secrets values.

##### Expected result
Accessing secrets sections of dashboard should not be possible (honouring RBAC of assigned role) and also accessing and reading individual secret values should also not be possible.
