### ISSUE TITLE
Helm chart - pinnedCRDs has no effect on UI sidemenu

### ISSUE THREAD

**Issue by Jimmy-Newtron** [kubernetes/dashboard#5753]
##### Environment

```
Installation method: Helm3
Kubernetes version: 1.19
Dashboard version (v1.x is not supported. Use v2.0 or later.): v2.1.0
```
Installation as per https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard/4.0.0

##### Steps to reproduce

Use minikube
Add a CRD resource (ie Prometheus)
Install chart with Helm3 and a values.yaml setting pinnedCRDs to the previous deployed CRD

##### Observed result

No pinned CRD into sidebar

##### Expected result

CRD pinned in the sidebar

##### Comment

Add an example in the Helm installation doc

**Comment by floreks** [comment]
Please provider your values yaml file.

**Comment by Jimmy-Newtron** [comment]
```yaml
pinnedCRDs:
  - kind: customresourcedefinition
    name: gitrepositories.source.toolkit.fluxcd.io
  - kind: customresourcedefinition
    name: helmrepositories.source.toolkit.fluxcd.io
  - kind: customresourcedefinition
    name: kustomizations.kustomize.toolkit.fluxcd.io
  - kind: customresourcedefinition
    name: helmreleases.helm.toolkit.fluxcd.io
  - kind: customresourcedefinition
    name: helmcharts.source.toolkit.fluxcd.io
  - kind: customresourcedefinition
    name: prometheuses.monitoring.coreos.com
  - kind: customresourcedefinition
    name: podmonitors.monitoring.coreos.com
  - kind: customresourcedefinition
    name: servicemonitors.monitoring.coreos.com
  - kind: customresourcedefinition
    name: prometheusrules.monitoring.coreos.com
```
