### ISSUE TITLE
How to externally access the kubernetes dashboards

### ISSUE THREAD

**Issue by kaykhancheckpoint** [kubernetes/dashboard#6019]
Hi friends, i would like to externally access the kubernetes dashboard on my domain using `k8s.acme.com` rather than connecting to it locally using `kubectl proxy`. Is this possible?

I have tried changing the service `kubernetes-dashboard` to a node port and then using an ingress to expose the service. 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-ingress
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: <redacted>
    alb.ingress.kubernetes.io/tags: Environment=staging,Team=dev
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '300'
spec:
  rules:
    - host: k8s.acme.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: kubernetes-dashboard
              servicePort: 443

```

But whenever i navgiate to `http://k8s.acme.com` in the browser on firefox i get the following error:

> Client sent an HTTP request to an HTTPS server.

When i navigate to `https://k8s.acme.com` i get bad request
