### ISSUE TITLE
Second pass of `helm upgrade --install` fails: Secret "X" in namespace "Y" exists and cannot be imported into the current release

### ISSUE THREAD

**Issue by KIVagant** [kubernetes/dashboard#6028]
##### Environment

```
Helm version: 3.4.2
Installation method: Helm chart
Kubernetes version: v1.19.6-eks
Dashboard version (v1.x is not supported. Use v2.0 or later.): 2.2.0
Operating system: not applicable
Node.js version ('node --version' output): not applicable
Go version ('go version' output): not applicable
```

##### Steps to reproduce

```
$ helm package --app-version=2b365cd-dev ./kubernetes-dashboard/ -d ./
Successfully packaged chart and saved it to: kubernetes-dashboard-4.0.3-0927d9b.tgz

$ helm install --debug --dry-run kubernetes-dashboard ./kubernetes-dashboard-4.0.3-2b365cd.tgz --namespace kube-system -f ./values/kubernetes-dashboard/values.yaml

...
Get the Kubernetes Dashboard URL by running:
  export SERVICE_IP=$(kubectl get svc -n kube-system kubernetes-dashboard -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  echo https://$SERVICE_IP/

$ helm upgrade --install --namespace=kube-system --values  ./values/kubernetes-dashboard/values.yaml kubernetes-dashboard ./kubernetes-dashboard-4.0.3-2b365cd.tgz
Release "kubernetes-dashboard" does not exist. Installing it now.

...
Get the Kubernetes Dashboard URL by running:
  export SERVICE_IP=$(kubectl get svc -n kube-system kubernetes-dashboard -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  echo https://$SERVICE_IP/
...

```

##### Observed result

After the first installation succeeded, all subsequent installations fail.

```
$ helm install --debug --dry-run kubernetes-dashboard ./kubernetes-dashboard-4.0.3-2b365cd.tgz --namespace kube-system -f ./values/kubernetes-dashboard/values.yaml
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /......../kubernetes-dashboard-4.0.3-2b365cd.tgz

Error: rendered manifests contain a resource that already exists. Unable to continue with install: Secret "kubernetes-dashboard-key-holder" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "kubernetes-dashboard"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"
helm.go:81: [debug] Secret "kubernetes-dashboard-key-holder" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "kubernetes-dashboard"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"
rendered manifests contain a resource that already exists. Unable to continue with install
helm.sh/helm/v3/pkg/action.(*Install).Run
	/home/circleci/helm.sh/helm/pkg/action/install.go:276
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:242
main.newInstallCmd.func2
	/home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
```

##### Expected result

Second installation should result in no change or do a rolling restart.

##### Comments

Our CI process is based on cached version of Helm charts and before doing the actual installation we always do `helm package` and `helm install --dry-run` first to make sure that the chart is still buildable with current values.

As a workaround, I can remove secrets created by the first installation and then the next one work again.

I checked how secrets look after the first successful dry-run installation in the output of the helm command and they have the metadata:

```yaml
# Source: kubernetes-dashboard/templates/secret.yaml
# kubernetes-dashboard-key-holder
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-dashboard
    helm.sh/chart: kubernetes-dashboard-4.0.3-2b365cd
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/managed-by: Helm
  name: kubernetes-dashboard-key-holder
type: Opaque
```

But, when the secret is installed with `helm upgrade --install` command, the _actual_ secret data in Kubernetes returns zero labels:

```yaml
apiVersion: v1
data:
  priv: ...
  pub: ...
kind: Secret
metadata:
  creationTimestamp: "2021-04-26T21:47:04Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:type: {}
    manager: Go-http-client
    operation: Update
    time: "2021-04-26T21:47:04Z"
  - apiVersion: v1
    fieldsType: FieldsV1
...
    manager: dashboard
    operation: Update
    time: "2021-04-26T21:47:20Z"
  name: kubernetes-dashboard-key-holder
  namespace: kube-system
...
type: Opaque
```

**Comment by floreks** [comment]
@desaintmartin is there a way to avoid this if we have to use predefined names for some resources? This looks like helm has some issues if the name cannot be partially generated by the helm.

**Comment by desaintmartin** [comment]
I can't reproduce the issue. Is the creation date of the created secret consistent with the `helm install` date? Do you see it created when you install? Do you have the same issue by using the recommended installation way (i.e using the actual package built in this repo? What is the content of the values.yaml?

**Comment by KIVagant** [comment]
The values:

```yaml
---
replicaCount: 1
labels:
  environment: "staging"
  kubernetes.io/name: "staging-kubernetes"
extraArgs:
  - --enable-skip-login=true
  - --token-ttl=0
  - --system-banner="Staging Kubernetes"

resources:
  requests:
    cpu: 10m
    memory: 128Mi
    ephemeral-storage: 64Mi
  limits:
    cpu: 100m
    memory: 256Mi
    ephemeral-storage: 512Mi

service:
  type: LoadBalancer
  externalPort: 443
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "0"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "TCP"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    external-dns.alpha.kubernetes.io/hostname: k8s-dashboard.xxxxx
  labels:
    kubernetes.io/name: "staging-kubernetes"

ingress:
  enabled: false

rbac:
  create: true
  clusterRoleMetrics: true
  clusterReadOnlyRole: true

serviceAccount:
  create: true
  name: kubernetes-dashboard
```

>  Is the creation date of the created secret consistent with the helm install date?

I am not sure I got the question. How could it be not consistent with the date?

I don't know why but I can delete all of the secrets:
```
kubernetes-dashboard-certs                            Opaque                                0      70s
kubernetes-dashboard-csrf                             Opaque                                1      70s
kubernetes-dashboard-key-holder                       Opaque                                2      70s
kubernetes-dashboard-token-9pw4p                      kubernetes.io/service-account-token   3      109s
```

..and than deploy the chart once again and new secrets will be created without any metadata. I feel like it is not the Helm chart problem, but something is wrong either with the Helm itself or with the Kubernetes version we have.
