### ISSUE TITLE
Run kubernetes dashboard with only apiserver

### ISSUE THREAD

**Issue by vaspahomov** [kubernetes/dashboard#6148]
Hi! 

I want to run kubernetes dashboard with only apiserver. I do not want to run scheduler and controllers in my configuration. 
I did not find any docs about how to run dashboard without them. 
 
I'm trying to run this configuration:
```
apiVersion: v1
kind: Pod
metadata:
  name: static-dashboard
  labels:
    role: myrole
    deployment: kubernetes-dashboard
spec:
  nodeName: my-external-hostname
  hostNetwork: true
  containers:
    - name: dashboard
      image: kubernetesui/dashboard:v2.2.0
      args:
        - --apiserver-host=https://my-external-hostname:6443/
        - -v=10
      securityContext:
        privileged: true
```

But I do not know how to deliver certificates in this pod. Can you suggest right solution how to run dashboard in my case?
