### ISSUE TITLE
Previous and next is not working under logs

### ISSUE THREAD

**Issue by johnr84** [kubernetes/dashboard#6223]
Installation method:
Kubernetes version: 1.21.1
Dashboard version: 2.3.1 
Operating system: Ubuntu 20.04.2

Steps to reproduce
Deploy Deployment with colored logs:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color
spec:
  selector:
    matchLabels:
      app: color
  template:
    metadata:
      labels:
        app: color
    spec:
      containers:
      - image: ubuntu
        name: color
        command: ["/bin/bash", "-c", 'while true; do echo -e "Meet the \e[92mcucumber!"; sleep 1; done']
```

Go to pod logs. Click "<" or ">" button. It will show error as "The selected container has not logged any messages yet".

Observed result
![image](https://user-images.githubusercontent.com/53331533/124158135-d696f180-da99-11eb-810a-f93d377e55e2.png)

Expected result
Both the next and previous buttons shows the respective logs
