### ISSUE TITLE
secret decode - Using JavaScript's atob decoder Base64 can't decode UTF-8 strings correctly

### ISSUE THREAD

**Issue by DuC-cnZj** [kubernetes/dashboard#6233]
```
Dashboard version: v2.3.1+0.g8d9f8e76c
```

##### Steps to reproduce

test-secret.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test
stringData:
  username: "哈哈"
  password: "123456"
```

##### Observed result

username incorrect

<img width="1180" alt="image-20210707101342498" src="https://user-images.githubusercontent.com/23514869/124690316-935ed780-df0c-11eb-9367-6a0b78dd28bd.png">

##### Expected result

username: 哈哈

##### Comments

ref: https://github.com/kubernetes/dashboard/blob/a4deef48f50ff9eb975fe574c9f776b22632fbd0/src/app/frontend/resource/config/secret/detail/component.ts#L72
