### ISSUE TITLE
Helm chart: All tables stay empty, but total numbers and metrics are showing up

### ISSUE THREAD

**Issue by trallnag** [kubernetes/dashboard#6282]
##### Environment

```
Installation method: Helm chart + additional resources
Chart version: 4.3.1
Kubernetes version: v1.21
Dashboard version (v1.x is not supported. Use v2.0 or later.): v2.3.1
```

I use additional stuff for ingress, auth, and so on. But that is irrelevant (I think) because the issue also comes up when I access the dashboard via kubectl proxy.

##### Steps to reproduce

Install Kubernetes Dashboard via the Helm chart with the values provided below. Also install the additional resources. Open the dashboard via kubectl proxy.

<http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/kubernetes-dashboard:http/proxy>

##### Observed result

Metrics like CPU and memory are showing up correctly. Also the number of resources is shown correctly. But the tables themselves stay empty.

![image](https://user-images.githubusercontent.com/24834206/126882402-7b780007-cfd3-477e-b977-e727ab0da4fb.png)

##### Expected result

Tables should not be empty

##### Comments

Ansible task that installs the chart

```yaml
- name: Install chart kubernetes-dashboard
  kubernetes.core.helm:
    name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    chart_ref: kubernetes-dashboard/kubernetes-dashboard
    chart_version: 4.3.1
    values: "{{ lookup('template', 'helm-chart-kubernetes-dashboard-values.yaml.jinja') | from_yaml }}"
```

Values provided

```yaml
image:
  tag: v2.3.1

extraArgs:
  - --enable-skip-login
  - --enable-insecure-login

protocolHttp: true

settings:
  clusterName: "Bismarck's Kubernetes"

metricsScraper:
  enabled: true

service:
  externalPort: 80

resources:
  requests:
    cpu: 50m
    memory: 50Mi
  limits:
    cpu: 2
    memory: 200Mi
```

Additional resources installed:

```yaml
{% set common_labels -%}
app.kubernetes.io/name: kubernetes-dashboard
app.kubernetes.io/instance: kubernetes-dashboard
app.kubernetes.io/managed-by: ansible
{%- endset %}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard
  labels:
    {{ common_labels | indent(4) }}
  annotations:
    description: >
      Gives the serviceaccount used by kubernetes-dashboard full cluster
      admin privileges. This should only be used in a private cluster.
      It is unsecure. For usage `--enable-skip-login` must be set.
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kubernetes-dashboard
    namespace: kubernetes-dashboard
```
