### ISSUE TITLE
Pod Detail Screen hangs with Javascript error when tcpSocket liveness or readiness checks specified

### ISSUE THREAD

**Issue by mowings** [kubernetes/dashboard#6306]
Installation method: helm chart version 4.3.1
Kubernetes version: v1.19.8-eks
Dashboard version  v2.3.0+0.gccb45d8ca

Browser versions affected

Chrome Version 92.0.4515.107 (Official Build) (x86_64)
Safari Version 14.1.1 (15611.2.7.1.6, 15611)

Summary: 

The pod detail screen appears to hang when trying to view any pod with a tcpSocket liveness or readiness probe configured. All other probe types appear to work as expected -- only the tcpSocket probe causes the issue. The error in the console is:

`TypeError: undefined is not an object (evaluating 'e.probe.httpGet.port')`

Reproducing:

This issue can be easily reproduced with the following test deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels:
    app: nginx-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
```

Attempting to view the pods created in the k8s-dashboard will cause the dashboard to hang with the error noted above. Changing the probe type to any other supported type (or removing it altogether) eliminates the error.

The dashboard itself is configured as a read-only dashboard with login disabled.
