### ISSUE TITLE
Kubernetes dashboard is editable in Read Only mode

### ISSUE THREAD

**Issue by mayankkhullar** [kubernetes/dashboard#6489]
Hi ,

Tried deploying K8s dashboard in AKS cluster in which RBAC is already enabled.
Can not see dashboard in Read only mode after creating Read only user with service account and cluster role and clusterrolebinding.
Tried following this tutorial https://support.platform9.com/hc/en-us/articles/360051772693-How-to-Grant-Read-Only-Access-to-the-Kubernetes-Dashboard

I can see edit button , i can edit the depoyment and i can scale up the replicas.

Even after this i am able to create the deployment , edit it, seeing the secrets and much more

Please help!!!!!

**Comment by mayankkhullar** [comment]
@bryk

**Comment by aardbol** [comment]
I can confirm after having it deployed by helm and having readonly enabled:

```
rbac:
  clusterReadOnlyRole: true
```

**Comment by mayankkhullar** [comment]
@aardbol 

Tried as per the version mentioned above but still same.

my-dashboard                               	default  	1       	2021-10-03 19:41:03.046515 +0530 IST	deployed	kubernetes-dashboard-4.0.3             	2.2.0      


I can Scale up the deployment with below parameters as well with k8s 1.18 version now as well.

rbac:
  create: true

    clusterRoleMetrics: true

    clusterReadOnlyRole: true

**Comment by floreks** [comment]
1. Always use the latest Dashboard version.
2. `clusterReadOnlyRole` is for something completely different. Read the related comment carefully. This is purely about Dashboard app privileges, not the user that is used to log in.
https://github.com/kubernetes/dashboard/blob/529ab1f51ecac8a9fbefb7a850675a732d4ddd8c/aio/deploy/helm-chart/kubernetes-dashboard/values.yaml#L257-L270
3. Always use official documentation. There is a `pod-reader` example role there: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-and-clusterrole
Based on that you can create your own ServiceAccount based role that can be used in Dashboard.
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader
  namespace: default
subjects:
- kind: ServiceAccount
  name: pod-reader
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
```

Tested everything on a v1.21 kind-based cluster and the latest helm chart (v5.0.1). Privileges work as expected.
![image](https://user-images.githubusercontent.com/2285385/135996979-9110f211-22cd-43dd-8709-9071ebc2a49e.png)


/close
