### ISSUE TITLE
404 error with the server could not find the requested resource

### ISSUE THREAD

**Issue by arasHi87** [kubernetes/dashboard#6858]
##### Environment

```
Installation method: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.4.0/aio/deploy/recommended.yaml
Kubernetes version: v1.21.10
Dashboard version (v1.x is not supported. Use v2.0 or later.): kubernetesui/dashboard:v2.4.0
Operating System: CentOS Stream 8
Architecture: x86-64
Node.js version ('node --version' output):
Go version ('go version' output): go1.16.14
```

##### Steps to reproduce

* Install by command `kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.4.0/aio/deploy/recommended.yaml`
* Set ingress by traefik with following yaml
<details>
  <summary>k8s-dashboard-ingress.yaml</summary>

  ```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: k8s-dashboard
  namespace: kubernetes-dashboard
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`k8s-dashboard.scist.org`)
      kind: Rule
      services:
        - name: kubernetes-dashboard
          port: 443
  tls:
    secretName: k8s-dashboard.scist.org
  ```
</details>

* Generate token by following yaml
<details>
  <summary>k8s-dashboard-admin.yaml</summary>

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kubernetes-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kubernetes-dashboard
```
</details>

* Use the generated token to login

##### Observed result

It successfully logged in but kept throwing a 404 error (the Chinese above means this), and it will auto redirect after 3 seconds.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/33758217/155989743-c05f651b-cb78-473c-b87a-dc7212cad26d.png">

##### Expected result

It was supposed to log in successfully, but failed. See next for more detail.

##### Comments

Although the ingress route failed, I found that some people on other issues provide a way to use NodePort and it will succeed. What's even more strange is that while waiting for the three seconds to redirect, just click any option on the menu and it will be normal, but it happens randomly, sometimes it will return to normal, but sometimes it will fall into an infinite error loop.
