### ISSUE TITLE
Run Kubernetes-Dashboard on a sub-path with Istio

### ISSUE THREAD

**Issue by Madaditya** [kubernetes/dashboard#6965]
##### What would you like to be added

Run Kubernetes-Dashboard in a sub-path with Istio virtual service

##### Why is this needed
e.g. if Istio gateway is hosted on mydomain.com , we should be able to run kubernetes dashboard on 
https://mydomain.com/k8s-dashboard.
There are nginx scripts that help us rewrite urls , but this isn't possible when using Istio. 
This can be configured by a simple ENV variable like URI_PREFIX=k8s-dashboard 

sample Istio Virtual service that should work with k8s dashboard:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: k8s-dashboard
spec:
  gateways:
  - namespace/my-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        exact: /k8s-dashboard
    - uri:
        prefix: /k8s-dashboard/
    rewrite:
      uri: /
    route:
    - destination:
        host: k8s-kubernetes-dashboard.monitoring.svc.cluster.local
        port:
          number: 443
```

**Comment by floreks** [comment]
In our case, it's not as simple as adding a prefix variable. Due to how our localization is handled and how angular itself works with the i18n framework `<base href...>` is always omitted. Our backend fully handles which translation directory should be served based on the selected language without changing the URL.

If Istio does not allow simple URL rewrite then I can only recommend using a different proxy/traffic manager or ask them to provide this basic functionality.

**Comment by floreks** [comment]
Unfortunately, this is not so simple. Part of the configuration is inside the `angular.json` that is used during the build. Possibly the main `index.html` would have to be also changed and for sure our backend would have to be altered in some way also. Without looking into this I can't really provide all the required changes. It is for sure a bit more complicated than it might seem on the surface.

**Comment by zzguang520** [comment]
@Madaditya Would you like share me the detaill for Run Kubernetes-Dashboard in a sub-path with Istio virtual service? I have create it, but failed:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: k8s-dashboard-gateway
  namespace: kube-dashboard
spec:
  selector:
    istio: ingress # use istio default controller
  servers:
  - port:
      number: 443
      name: https-kube-dashboard
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: my-secret
    hosts:
    - "kube-dashboard.cloud.dalian.cn.ibm.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kube-dashboard-vs
  namespace: kube-dashboard
spec:
  hosts:
  - "kube-dashboard.cloud.dalian.cn.ibm.com"
  gateways:
  - kube-dashboard-gateway
  http:
  - route:
    - destination:
        host: kubernetes-dashboard.kube-dashboard.svc.cluster.local
        port:
          number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kube-dashboard-dr
  namespace: kube-dashboard
spec:
  host: kubernetes-dashboard.kube-dashboard.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
```

**Comment by donRumatta** [comment]
> I was able to get this working. Attaching steps for users with the same issue.
> 
> **Enable the below in Kubernetes Dashboard HELM chart:** (make sure your istio gateway has valid SSL certs)
> 
> ```
> protocolHttp: true
> 
> extraArgs:
>   - --enable-insecure-login
> ```
> 
> **Istio Virtual Service**
> 
> ```
> apiVersion: networking.istio.io/v1alpha3
> kind: VirtualService
> metadata:
>     name: k8s-dashboard-vs
>     namespace: monitoring
> spec:
>   gateways:
>   - kubeflow/kubeflow-gateway
>   hosts:
>   - '*'
>   http:
>   - headers:
>       request:
>         add:
>           x-forwarded-prefix: /k8s-dashboard
>     match:
>     - uri:
>         prefix: /k8s-dashboard/
>     rewrite:
>       uri: /
>     route:
>     - destination:
>         host: kubernetes-dashboard.monitoring.svc.cluster.local
>         port:
>           number: 443
> ```

@Madaditya, thank you, I've used your approach to deal with error "Client sent an HTTP request to an HTTPS server."
But now when the page is loaded I get 404 for requests that are loading static resources like js, css and images, because they are situated under additional "/k8s-dashboard" path. Html does not contain any "<base href="/">". I'm using version 6.0.8 of dashboard. Is there any BASE_PATH parameter to be set for dashboard k8s-deployment?

**Comment by sivanagireddyb** [comment]
> > I was able to get this working. Attaching steps for users with the same issue.
> > **Enable the below in Kubernetes Dashboard HELM chart:** (make sure your istio gateway has valid SSL certs)
> > ```
> > protocolHttp: true
> > 
> > extraArgs:
> >   - --enable-insecure-login
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Istio Virtual Service**
> > ```
> > apiVersion: networking.istio.io/v1alpha3
> > kind: VirtualService
> > metadata:
> >     name: k8s-dashboard-vs
> >     namespace: monitoring
> > spec:
> >   gateways:
> >   - kubeflow/kubeflow-gateway
> >   hosts:
> >   - '*'
> >   http:
> >   - headers:
> >       request:
> >         add:
> >           x-forwarded-prefix: /k8s-dashboard
> >     match:
> >     - uri:
> >         prefix: /k8s-dashboard/
> >     rewrite:
> >       uri: /
> >     route:
> >     - destination:
> >         host: kubernetes-dashboard.monitoring.svc.cluster.local
> >         port:
> >           number: 443
> > ```
> 
> @Madaditya, thank you, I've used your approach to deal with error "Client sent an HTTP request to an HTTPS server." But now when the page is loaded I get 404 for requests that are loading static resources like js, css and images, because they are situated under additional "/k8s-dashboard" path. Html does not contain any "". I'm using version 6.0.8 of dashboard. Is there any BASE_PATH parameter to be set for dashboard k8s-deployment?

How to enable `protocolHttp: true`. I don't see any option for this in values. 
I am using Helm chart version 7.5.0.
I am getting below error in browser after using this .
`Unknown error (200): Http failure during parsing for https://dev.com/k8s-dashboard/api/v1/csrftoken/login`

**Comment by Zvezdoreel** [comment]
> > > I was able to get this working. Attaching steps for users with the same issue.
> > > **Enable the below in Kubernetes Dashboard HELM chart:** (make sure your istio gateway has valid SSL certs)
> > > ```
> > > protocolHttp: true
> > > 
> > > extraArgs:
> > >   - --enable-insecure-login
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **Istio Virtual Service**
> > > ```
> > > apiVersion: networking.istio.io/v1alpha3
> > > kind: VirtualService
> > > metadata:
> > >     name: k8s-dashboard-vs
> > >     namespace: monitoring
> > > spec:
> > >   gateways:
> > >   - kubeflow/kubeflow-gateway
> > >   hosts:
> > >   - '*'
> > >   http:
> > >   - headers:
> > >       request:
> > >         add:
> > >           x-forwarded-prefix: /k8s-dashboard
> > >     match:
> > >     - uri:
> > >         prefix: /k8s-dashboard/
> > >     rewrite:
> > >       uri: /
> > >     route:
> > >     - destination:
> > >         host: kubernetes-dashboard.monitoring.svc.cluster.local
> > >         port:
> > >           number: 443
> > > ```
> > 
> > 
> > [@Madaditya](https://github.com/Madaditya), thank you, I've used your approach to deal with error "Client sent an HTTP request to an HTTPS server." But now when the page is loaded I get 404 for requests that are loading static resources like js, css and images, because they are situated under additional "/k8s-dashboard" path. Html does not contain any "". I'm using version 6.0.8 of dashboard. Is there any BASE_PATH parameter to be set for dashboard k8s-deployment?
> 
> How to enable `protocolHttp: true`. I don't see any option for this in values. I am using Helm chart version 7.5.0. I am getting below error in browser after using this . `Unknown error (200): Http failure during parsing for https://dev.com/k8s-dashboard/api/v1/csrftoken/login`



Ive managed to do it by setting:

```yaml
  kong:
    enabled: true
    proxy:
      type: ClusterIP
      http:
        enabled: true
```

In the values.yaml
