### ISSUE TITLE
Exec into pod does not work reliable when dashboard replicas

### ISSUE THREAD

**Issue by davidroth** [kubernetes/dashboard#7114]
### What happened?

When deploying kubernetes dashboard with e.g. 2 replicas, I cannot reliable exec into a pod.
I often see only a blank shell which hangs forever. I have to reload the shell exec and then after several retries it works.

## Black shell without prompt:

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/338856/168983997-ea5ef3e7-ea32-42d1-ad37-05cfd1478a3a.png">

## After reloading / retry:

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/338856/168984040-55296eb0-c18e-4ffc-ac7b-47a0369f4365.png">

### What did you expect to happen?

Shell exec works reliable even when dashboard has replicas.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy the dashboard with replicas (e.g. 2). Navigiate to a pod and try to shell-exec into it. You will see that this sometimes works, and sometimes you will just see a black shell with no prompt. After some retries it works.

### What browsers are you seeing the problem on?

All browsers

### Kubernetes Dashboard version

Dashboard v2.5.1+0

### Kubernetes version

1.22

**Comment by cloud-66** [comment]
It is not dashboard problem. Because terminal uses websocket ( stateful protocol),  you need to add sticky session. I use this  annotation to stick session by cookie. It works great with 3 dashboard replicas
```
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "86400"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "86400"
```
