### ISSUE TITLE
Nginx ingress 400 Bad request

### ISSUE THREAD

**Issue by Rahulsharma0810** [kubernetes/dashboard#7201]
### What happened?

Kuberetes dashboard ingress returns

```
❯ curl -I https://kubedash.labs.example.com
HTTP/1.1 400 Bad Request
Server: nginx/1.21.6
Date: Mon, 20 Jun 2022 17:00:35 GMT
Connection: keep-alive
```

### What did you expect to happen?

Nginx 200 response on https://kubedash.labs.example.com

### How can we reproduce it (as minimally and precisely as possible)?

```
ingress:
  enabled: true
  paths:
    - /
  hosts:
    - kubedash.labs.example.com
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  tls:
    - secretName: ca-wildcard-example-cert-secret
      hosts:
        - kubedash.labs.example.com
  metricsScraper:
    enabled: true
  metrics-server:
    enabled: true
## Additional container arguments
##
extraArgs:
  - --enable-skip-login
  - --enable-insecure-login
  # - --system-banner="Welcome to Kubernetes"

```

```helm install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard -f values.yaml -n kube-dash```

### Anything else we need to know?

Using metallb on bare metal Kubernetes cluster.

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

2.6.0

### Kubernetes version

1.24.1

**Comment by malmiteria** [comment]
i have the same issue on a bare metal installation.

went through ```kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.6.0/aio/deploy/recommended.yaml
```

and added my own nginx ingress to it


if that helps, here's a verbose curl call
```> curl -Iv <my-adress>
*   Trying <my-ip>:443...
* Connected to <my-adress> (<my-ip>) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=<my-adress>
*  start date: Jun 22 06:38:53 2022 GMT
*  expire date: Sep 20 06:38:52 2022 GMT
*  subjectAltName: host "<my-adress>" matched cert's "<my-adress>"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5557caf89cc0)
> HEAD / HTTP/2
> Host:  <my-adress>
> user-agent: curl/7.74.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 400 
HTTP/2 400 
< date: Wed, 22 Jun 2022 07:41:04 GMT
date: Wed, 22 Jun 2022 07:41:04 GMT
< strict-transport-security: max-age=15724800; includeSubDomains
strict-transport-security: max-age=15724800; includeSubDomains

< 
* Connection #0 to host <my-adress> left intact
```


accessing the page on chrome simply gives the same 400 error

**Comment by floreks** [comment]
This is clearly a configuration issue, not the Dashboard itself. I have been using Dashboard with reverse proxies for a long time now and with proper configuration, it works fine. 

You'd have to debug your networking, check nginx logs, and check if the request even reaches the Dashboard pod or when and where it is being dropped. Depending on the Kubernetes setup (GCP, AWS, bare-metal, etc.) nginx configuration can be very very different.

I don't think this issue is directly related to the Dashboard.

**Comment by malmiteria** [comment]
> This is clearly a configuration issue, not the Dashboard itself. I have been using Dashboard with reverse proxies for a long time now and with proper configuration, it works fine.

Would you care to provide an example of such a proper configuration? I can't seem to find one in the doc.

> You'd have to debug your networking, check nginx logs, and check if the request even reaches the Dashboard pod or when and where it is being dropped. Depending on the Kubernetes setup (GCP, AWS, bare-metal, etc.) nginx configuration can be very very different.

I did, and as far as I can tell, my reverse proxy isn't the source of the issue. I get ``` recv() failed (104: Connection reset by peer) while reading upstream``` which to me indicates that the ingress itself is not the issue, as it is not the one closing the connection.
However i'm still kinda new to k8s, so I'm perfectly willing to accept that i misunderstand something here

> I don't think this issue is directly related to the Dashboard.

Well, it doesn't work out of the box, not with reverse proxies at least. Perhaps it's just a gap in the documentation?
the doc for ingress access to dashboard is very limited, simply refering to the ingress doc, which leaves to the user to guess how to plug / edit the dashboard conf to any ingress : https://github.com/kubernetes/dashboard/blob/master/docs/user/accessing-dashboard/README.md#ingress

====

I managed to make it work with the alternative installation, which according to the doc isn't fully secured. But oh well, i need it to work and like that i can make it work with some ingress to secure it on my end.

On this setup i had to fight my way through other security walls that prevented dashboard access to the data it is supposed to access, the doc is unclear as if this is one of the security concern of that setup or not.

I am unclear as to why those access are limited (to that extent) in the first place, dashboard is explicitely used to access those informations / resources, I'm pretty sure any dashboard user is gonna have to work around those security wall, rendering them useless? Am I missing something?

=====

Overall, i feel like i need to underline that i *failed* to follow through the recommended install, and had to revert to a less secure alternative :/

This is either due to a gap in the documentation, or an actual issue with dashboard recomended install itself, combined with my limited experience in k8s.

Either way, a more complete documentation for ingress setup, with an example ingress setup, and the steps to follow to edit the provide configuration to work under an ingress would be appreciated

**Comment by floreks** [comment]
> Would you care to provide an example of such a proper configuration? I can't seem to find one in the doc.

We do not provide any example ingress configurations for a very simple reason. There are too many Kubernetes providers, proxies, and other tools out there. We do not want to maintain dozens of configurations for GCP, AWS, bare-metal using nginx, haproxy, traefik with additional OIDC configurations using dex, keycloak, etc. There are too many possible configurations for us to provide a single one that would work for everyone. Depending on the provider, DNS configurations might look different or you might need to execute additional steps directly on the GCP, AWS side to make it work. We simply do not have the time or resources to maintain all that. 

In general exposing Dashboard is the same as exposing any web application running inside the Kubernetes. That is why in our documentation we are forwarding you directly to the [Kubernetes documentation](https://kubernetes.io/docs/concepts/services-networking/ingress/). There are no hidden steps required in order to expose Dashboard. It works the same as any other app. The key here is to have some understanding of how Kubernetes, Ingresses, proxies, etc. work.

> recv() failed (104: Connection reset by peer)

This error is usually thrown when you have an invalid HTTPS forwarding configuration for your ingress/proxy. The `recommended` setup by default uses auto-generated certificates. Most proxies require some additional cert configuration to allow HTTPS forwarding. It is destined for beginners to simply install it and run `kubectl proxy` and then just access the Dashboard locally. 

This is not the case for the `alternative` setup since it exposes Dashboard over HTTP by default. It is best to use this configuration with the reverse proxy and make the reverse proxy use the HTTPS with some valid certificate. The "not fully secure" wording is meant only if you would want to directly expose Dashboard over HTTP to the outside world, not through the secure reverse proxy.

**Comment by malmiteria** [comment]
> We simply do not have the time or resources to maintain all that.

Understandable.

> > recv() failed (104: Connection reset by peer)
> 
> This error is usually thrown when you have an invalid HTTPS forwarding configuration for your ingress/proxy. The `recommended` setup by default uses auto-generated certificates. Most proxies require some additional cert configuration to allow HTTPS forwarding. It is destined for beginners to simply install it and run `kubectl proxy` and then just access the Dashboard locally.
> 
> This is not the case for the `alternative` setup since it exposes Dashboard over HTTP by default. It is best to use this configuration with the reverse proxy and make the reverse proxy use the HTTPS with some valid certificate. The "not fully secure" wording is meant only if you would want to directly expose Dashboard over HTTP to the outside world, not through the secure reverse proxy.

Super clear, thanks

**Comment by Rahulsharma0810** [comment]
Adding 

```
extraArgs:
  # - --enable-skip-login
  - --enable-insecure-login
  # - --system-banner="Welcome to Kubernetes"
```

Resolved it.

**Comment by younsl** [comment]
## Environment

```bash
user --https(443)--> NLB(service) --http(80)--> service(ingress-nginx) --http--> pods(ingress-nginx) --> ingress --> service(grafana) --> pods (grafana)
```

- EKS v1.29
- ingress-nginx v1.10.0 (chart version 4.10.0)

## Problem

curl calling to grafana deployed by kube-prometheus-stack chart in EKS cluster:

```bash
$ curl -v https://grafana.doge.net/
*   Trying 13.125.119.168:443...
* Connected to grafana.doge.net (13.x.x.x) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=coinfra.net
...
* using HTTP/1.x
> GET / HTTP/1.1
> Host: grafana.doge.net
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Date: Tue, 14 May 2024 09:25:04 GMT
< Content-Type: text/html
< Content-Length: 248
< Connection: close
<
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>
* Closing connection
* TLSv1.2 (IN), TLS alert, close notify (256):
* TLSv1.2 (OUT), TLS alert, close notify (256):
```

Return `HTTP/1.1 400 Bad Request` error.

## Solution

I just lost an entire day troubleshooting, too. this and it turned out to be the ports configuration in the Service created by `ingress-nginx` helm chart.

The `targetPort` in the https configuration needs to be `http` (TCP/80) instead of the reference `https` (TCP/443).

Ingress for grafana deployed by kube-prometheus-stack chart:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: monitoring
    nginx.ingress.kubernetes.io/rewrite-target: /
  creationTimestamp: "2024-05-14T07:39:33Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 10.4.1
    helm.sh/chart: grafana-7.3.9
  name: kube-prometheus-stack-grafana
  namespace: monitoring
  resourceVersion: "231151113"
  uid: 7f72f082-7706-402b-b21f-52d6f3b5ccb6
spec:
  ingressClassName: nginx
  rules:
  - host: grafana.doge.net
    http:
      paths:
      - backend:
          service:
            name: kube-prometheus-stack-grafana
            port:
              number: 80
        path: /
        pathType: Prefix
```

Diff targetPort in ingress-nginx chart:

```diff
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
-     targetPort: https
+     targetPort: http
```

Then upgrade `ingress-nginx` chart using `helm upgrade` command to modify ingress-nginx-controller service.

```bash
$ k get svc -n ingress-nginx
NAME                                 TYPE           CLUSTER-IP      EXTERNAL-IP                                                                     PORT(S)                      AGE
ingress-nginx-controller             LoadBalancer   172.20.11.118   <REDACTED>.elb.ap-northeast-2.amazonaws.com   80:30948/TCP,443:30608/TCP   138m
ingress-nginx-controller-admission   ClusterIP      172.20.154.40   <none>                                                                          443/TCP                      4h17m
```

ingress-nginx chart value:

```yaml
controller:
  service:
    # -- Enable controller services or not. This does not influence the creation of either the admission webhook or the metrics service.
    enabled: true
    external:
      # -- Enable the external controller service or not. Useful for internal-only deployments.
      enabled: true
    # -- Annotations to be added to the external controller service. See `controller.service.internal.annotations` for annotations to be added to the internal controller service.
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-name: <REDACTED>-pub-nginx-ingress-nlb
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:ap-northeast-2:<REDACTED>:certificate/<REDACTED>"
      service.beta.kubernetes.io/aws-load-balancer-security-groups: <REDACTED>
      service.beta.kubernetes.io/aws-load-balancer-attributes: deletion_protection.enabled=true
```

I observed working properly for network flow.

## Reference

[kubernetes ingress-controller `400 Bad request - plain HTTP request sent to HTTPS port`](https://stackoverflow.com/questions/70733110/kubernetes-ingress-controller-400-bad-request-plain-http-request-sent-to-http) at stack overflow
