### ISSUE TITLE
ownerReferences missing in Jobs metadata created by triggering CronJob via dashboard

### ISSUE THREAD

**Issue by gerasym** [kubernetes/dashboard#7251]
### What happened?

When you press play button to trigger CronJob manually, it creates a Job, which does not have ownerReferences field in metadata pointing to parent CronJob.

### What did you expect to happen?

Similarly to 
`kubectl create job --from=cronjobname jobname` i expect to have 

```
metadata:
  ownerReferences:
  - apiVersion: batch/v1beta1
    kind: CronJob
    name: cronjobname
    uid: 2314d42e-fab3-49b6-8fab-098072c499d1
```
in created Job object

### How can we reproduce it (as minimally and precisely as possible)?

Press play button to trigger CronJob manually. Check if  Job object has metadata.ownerReferences field.

### Kubernetes Dashboard version

2.6.0, 2.4.0 and below

### Kubernetes version

1.20.15
