### ISSUE TITLE
HTTP Headers on liveness/readiness probes not rendering correctly

### ISSUE THREAD

**Issue by jnoordsij** [kubernetes/dashboard#7310]
### What happened?

When showing the HTTP Headers of the probes on my Pod, instead of a human-readable output, the display shown is:
```
HTTP Headers
[object Object]
[object Object]
```

### What did you expect to happen?

An output like e.g.:
```
HTTP Headers
<name>: <value>
<name2>: <value2>
```

### How can we reproduce it (as minimally and precisely as possible)?

Create a Pod with custom headers on the probe, e.g.
```
livenessProbe:
  httpGet:
    path: /
    port: 80
    scheme: HTTP

    httpHeaders:
      - name: Host
        value: www.example.com
      - name: X-Forwarded-Proto
        value: https
```

### What browsers are you seeing the problem on?

Chrome, Firefox

### Kubernetes Dashboard version

2.6.0

### Kubernetes version

1.24.2
