### ISSUE TITLE
permission escape

### ISSUE THREAD

**Issue by sbwfnhn** [kubernetes/dashboard#7497]
### What happened?

No namespace display is configured, and there is no option in the menu, but it can be returned directly with a url request.
https://172.16.22.160:31001/#/deployment?namespace=_all
```
#- apiGroups:
#  - ""
#  resources:
#  - namespaces
#  verbs:
#  - get
#  - list
#  - watch
```

account.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-readonly
  namespace: kube-system

---

apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: dashboard-readonly
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: "dashboard-readonly"



---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dashboard-viewonly

rules:
#- apiGroups:
#  - ""
#  resources:
#  - pods
#  verbs:
#  - get
#  - list
#  - watch
#  - delete
- apiGroups:
  - ""
  resources:
  - endpoints
  - replicationcontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - bindings
  - events
  - namespaces/status
  - pods/log
  - pods/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
#here bugs?????
#- apiGroups:
#  - ""
#  resources:
#  - namespaces
#  verbs:
#  - get
#  - list
#  - watch



---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard-readonly
  labels:
    k8s-app: kubernetes-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dashboard-viewonly
subjects:
- kind: ServiceAccount
  name: dashboard-readonly
  namespace: kube-system


---


apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader-orDelete
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dashboard-viewonly-orDelete
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader-orDelete
subjects:
- kind: ServiceAccount
  name: dashboard-readonly
  namespace: kube-system

```

![bug1](https://user-images.githubusercontent.com/21355165/194991597-a946ec9a-faff-4f74-8c13-854fed8f75bb.png)

### What did you expect to happen?

should refuse to return all namespaces.

### How can we reproduce it (as minimally and precisely as possible)?

kubectl apply -f account.yaml
request url https://172.16.22.160:31001/#/deployment?namespace=_all
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-readonly
  namespace: kube-system

---

apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: dashboard-readonly
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: "dashboard-readonly"



---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dashboard-viewonly

rules:
#- apiGroups:
#  - ""
#  resources:
#  - pods
#  verbs:
#  - get
#  - list
#  - watch
#  - delete
- apiGroups:
  - ""
  resources:
  - endpoints
  - replicationcontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - bindings
  - events
  - namespaces/status
  - pods/log
  - pods/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
#here bugs?????
#- apiGroups:
#  - ""
#  resources:
#  - namespaces
#  verbs:
#  - get
#  - list
#  - watch



---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard-readonly
  labels:
    k8s-app: kubernetes-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dashboard-viewonly
subjects:
- kind: ServiceAccount
  name: dashboard-readonly
  namespace: kube-system


---


apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader-orDelete
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dashboard-viewonly-orDelete
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader-orDelete
subjects:
- kind: ServiceAccount
  name: dashboard-readonly
  namespace: kube-system
```

### Kubernetes Dashboard version

Dashboard v2.6.1+0.g2ce9133f7

### Kubernetes version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version. Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:38:15Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
