### ISSUE TITLE
kubernetes dashboard via ingress always gives 404

### ISSUE THREAD

**Issue by pranavnateri** [kubernetes/dashboard#7616]
### What happened?

1. I installed kubernetes dashboard via helm chart
2. However, i wanted expose the dashboard via ingress option. 
3. Hence, i made ingress.enabled=true and  added the annotations in the values.yaml file and upgraded the helm chart

However, i always get 404 not found page

### What did you expect to happen?

It Should open the kubernetes dashboard

### How can we reproduce it (as minimally and precisely as possible)?

1. Install the kubernetes dashboard via helm chart.
2. Modified the below values in values.yaml file as below.

```
service:
  type: NodePort

ingress:
  enabled: true

  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    
  hosts:
    - hellodash.xpressplay.net
```` 
    
3. Upgraded the helm chart.
4. I can see the ingress created. The below DNS is also created in our R53 DNS so its resolvable as well.

```
pnateri@C02G70NAMD6M customizations % kubectl get ingress -A                                                                                                            
NAMESPACE     NAME                        CLASS    HOSTS                      ADDRESS                                                                  PORTS   AGE
kube-system   helm-kubernetes-dashboard   <none>   hellodash.xpressplay.net   a6e9ebb0174f943538ebe52bac1f0238-371946555.eu-west-1.elb.amazonaws.com   80      10m
```
    

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/48081553/217779504-17714e73-1d27-4ae8-920e-f43c8e93fe82.png">

5. Dashboard service is also up and running without any issues

`pnateri@C02G70NAMD6M customizations % kubectl get svc -n kube-system | grep -i dashboard
helm-kubernetes-dashboard                      NodePort    10.100.170.51    <none>        443:30195/TCP   25m
`
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/48081553/217779590-ad7993df-d490-4b42-b228-0120651d8d58.png">

However, everytime i hit hellodash.xpressplay.net it always gives me 404 not found, instead of opening the kubernetes dashboard page

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/48081553/217779413-6626c313-a1d8-40a8-8628-b4fa481209a4.png">

### Kubernetes Dashboard version

v2.7.0

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:47:25Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-ffeb93d", GitCommit:"f76e2b475d1433cdb6bd546e9e8f129fde938fb7", GitTreeState:"clean", BuildDate:"2022-11-29T18:41:00Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by floreks** [comment]
This is a configuration issue, not a bug in the Dashboard itself. You can expose Dashboard like any other Kubernetes app. Unfortunately, we do not provide K8S support here. I'd recommend asking on Kubernetes slack.

/close

**Comment by pranavnateri** [comment]
Why dont you suggest where is the configuration issue?

Regards,
Pranav

**Comment by floreks** [comment]
I actually don't know from the top of my head. I don't have any running configuration using ingress with dashboard. There are just too many potential issues to consider like proper forwarding, certificates, overlay networks, and more.

**Comment by pranavnateri** [comment]
okay no problem @floreks . 
Let me just tell you my requirement then. It is very simple.

All i wanted to do is just install kubernetes dashboard but wanted to expose the dashboard with TLS cert manager so that the certificates are automanaged.

How would you go about it if you have to do the same using this kubernetes dashboard repo?

Regards,
Pranav

**Comment by luchillo17** [comment]
@pranavnateri I got mine to work, however, the ingress resource was a pain given the docs do not cover how to do this:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/kubernetes\-dashboard)$ $1/ redirect;
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /kubernetes-dashboard(/|$)(.*)
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 443
```

Please note the rewrite & redirect stuff, also this probably is not production ready, my setup was very specific, Win 10 WSL2 Ubuntu, docker desktop, and a Kind cluster with multiple nodes, here's what the kind config looks like in case it helps anyone else:
```yaml
# three node (two workers) cluster config with Ingress support https://kind.sigs.k8s.io/docs/user/ingress
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP
  - role: worker
  - role: worker
  - role: worker
```
