### ISSUE TITLE
Using restricted Read Only User token ignored. Actions like DELETE POD can still be performed

### ISSUE THREAD

**Issue by nicc777** [kubernetes/dashboard#7632]
### What happened?

We recently upgraded to Kubernetes 1.24 (AWS EKS). Previously we were running Kubernetes 1.21, so yes - this was a fairly large jump given all that has changed with tokens etc.

Kubernetes Dashboard was upgraded to 2.6.1 which showed as compatible in the release section of this repo.

I have created a Read Only user Service Account and related artifacts as can be seen below:

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ro-user
  namespace: kubernetes-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dashboard-viewonly
rules:
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - replicationcontrollers
  - pods
  - replicationcontrollers/scale
  - serviceaccounts
  - services
  - nodes
  - persistentvolumeclaims
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - bindings
  - events
  - limitranges
  - namespaces/status
  - pods/log
  - pods/status
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/scale
  - ingresses
  - networkpolicies
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  - volumeattachments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - roles
  - rolebindings
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ro-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dashboard-viewonly
subjects:
- kind: ServiceAccount
  name: ro-user
  namespace: kubernetes-dashboard
---
apiVersion: v1
kind: Secret
metadata:
  name: ro-user-secret
  annotations:
    kubernetes.io/service-account.name: ro-user
type: kubernetes.io/service-account-token
```

Afterwards I fetch the token with the following command:

```shell
kubectl get secrets/ro-user-secret -n kubernetes-dashboard -o go-template="{{.data.token | base64decode}}"
```

Here is the partially censored decoded JWT payload:

```json
{
  "iss": "kubernetes/serviceaccount",
  "kubernetes.io/serviceaccount/namespace": "kubernetes-dashboard",
  "kubernetes.io/serviceaccount/secret.name": "ro-user-secret",
  "kubernetes.io/serviceaccount/service-account.name": "ro-user",
  "kubernetes.io/serviceaccount/service-account.uid": "xxxxxxxx-xxxx-xxxx-xxxx-591d75a67404",
  "sub": "system:serviceaccount:kubernetes-dashboard:ro-user"
}
```

I use this JWT token to sign into Kubernetes Dashboard.

### What did you expect to happen?

When logging in with this token, my expectation was that I will not be able to delete resources like Pods (as an example) since I have not granted that permission in the `ClusterRole`

However, I am still able to delete Pods.

In the previous version of Kubernetes, it all worked as expected.

### How can we reproduce it (as minimally and precisely as possible)?

Apply the manifest as listed above and run the command to obtain the token.

Log into the Kubernetes dashboard using the JWT token.

Select a random (but safe - like a test pod) pod to delete and try to delete it.

### Anything else we need to know?

Perhaps I am missing something. I have read the following pages and I am pretty sure I am doing what I am suppose to do:

* https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets
* https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token
* https://www.programmingwithwolfgang.com/use-the-tokenrequest-api-to-create-tokens-in-kubernetes/

### Kubernetes Dashboard version

2.6.1

### Kubernetes version

1.2.4
