### ISSUE TITLE
(helm) Network Policy Egress

### ISSUE THREAD

**Issue by jcpunk** [kubernetes/dashboard#7659]
### What would you like to be added?

Extend `networkpolicy.yaml` to include a default block for egress traffic.

### Why is this needed?

With the ability to review and deploy so many objects inside kubernetes, having a policy to block any method of exfiltrating data could be handy for auditors.

**Comment by jcpunk** [comment]
Something like:

```yaml
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
```
maybe?
