### ISSUE TITLE
Migrate from PodSecurityPolicy to the Built-In PodSecurity Admission Controller

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#7719]
### What would you like to be added?

Until now our Helm chart was using PodSecurityPolicy, we should migrate to the Built-In PodSecurity Admission Controller: https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/

### Why is this needed?

PodSecurityPolicy was removed in v1.25.

**Comment by maciaszczykm** [comment]
Old PSP config:

```yaml
  { { if .Values.podSecurityPolicy.enabled - } }
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: { { template "kubernetes-dashboard.fullname" . } }-psp
  labels:
    {{- include "kubernetes-dashboard.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
    { { - if .Values.commonAnnotations } }
    { { - include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 } }
    { { - end } }
spec:
  privileged: false
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  runAsGroup:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - 'configMap'
    - 'secret'
    - 'emptyDir'
  allowPrivilegeEscalation: false
  hostNetwork: false
  hostIPC: false
  hostPID: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: { { template "kubernetes-dashboard.fullname" . } }-psp
  labels:
  { { include "kubernetes-dashboard.labels" . | nindent 4 } }
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: { { template "kubernetes-dashboard.fullname" . } }-psp
subjects:
  - kind: ServiceAccount
    name: { { template "kubernetes-dashboard.serviceAccountName" . } }
    namespace: { { .Release.Namespace } }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: { { template "kubernetes-dashboard.fullname" . } }-psp
  labels:
  { { include "kubernetes-dashboard.labels" . | nindent 4 } }
rules:
  - apiGroups:
      - extensions
      - policy/v1beta1
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - { { template "kubernetes-dashboard.fullname" . } }-psp
  { { - end - } }
```
