### ISSUE TITLE
Problem with values.yaml in Helm Chart

### ISSUE THREAD

**Issue by mihirsamdarshi** [kubernetes/dashboard#8020]
### What happened?

I was trying to deploy the new Helm chart, and I copied the new `values.yaml` in order to deploy it in my existing cluster. 

I already have cert-manager, metrics-server, and nginx in my cluster, so I set them all to `false`. I then installed the chart, and started getting the following error:
```
Helm install failed: rendered manifests contain a resource that already exists. Unable to continue with install: IngressClass "nginx" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "kubernetes-dashboard": current value is "ingress-nginx"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "monitoring": current value is "networking"
```
I used `helm template` in order to render out the templates and noticed that nginx was still being deployed. 

I'm not really sure how helm templates work, but I noticed that in the `values.yaml` was called `nginx`

https://github.com/kubernetes/dashboard/blob/ddbe9ea29a202da1d8658efb5f8fad28f685ec0d/charts/helm-chart/kubernetes-dashboard/values.yaml#L281

but in `Chart.yaml` the nginx chart was enabled based on `nginx-ingress.enabled`

https://github.com/kubernetes/dashboard/blob/ddbe9ea29a202da1d8658efb5f8fad28f685ec0d/charts/helm-chart/kubernetes-dashboard/Chart.yaml#L34-L38

I changed my `values.yaml` like the following 

```yaml
-    nginx:
+    nginx-ingress:
       enabled: false
```

and my helm install succeeded

### What did you expect to happen?

values.yaml should be 

```yaml
nginx-ingress:
  enabled: true
```
instead of:
```yaml
nginx:
  enabled: true
```

### How can we reproduce it (as minimally and precisely as possible)?

Use the following values.yaml in a cluster with `cert-manager`, `metrics-server`, and `nginx-ingress-controller` already installed:

```yaml
app:
  settings:
  ingress:
    className: nginx
    issuer: letsencrypt-production
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - "kubernetes.mydomain.com"
    tls:
      - hosts:
          - "kubernetes.mydomain.com"
        secretName: kubernetes-dashboard-tls

metrics-server:
  enabled: false

cert-manager:
  enabled: false
  installCRDs: false

nginx-ingress:
  enabled: false

```

### Kubernetes Dashboard version

3.0.0

### Kubernetes version

1.27.3
