### ISSUE TITLE
Ingress uses deprecated `kubernetes.io/ingress.class` annotation instead of `ingressClassName` field 

### ISSUE THREAD

**Issue by PortableProgrammer** [kubernetes/dashboard#8022]
### What happened?

The Helm-generated `kubernetes-dashboard` ingress uses the deprecated [`kubernetes.io/ingress.class`](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation) annotation instead of the recommended `ingressClassName` field.

https://github.com/kubernetes/dashboard/blob/ddbe9ea29a202da1d8658efb5f8fad28f685ec0d/charts/helm-chart/kubernetes-dashboard/templates/networking/ingress.yaml#L25

<details><summary>
Generated ingress
</summary>

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    meta.helm.sh/release-name: kubernetes-dashboard
    meta.helm.sh/release-namespace: kubernetes-dashboard
  labels:
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubernetes-dashboard
    helm.sh/chart: kubernetes-dashboard-7.0.0
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  rules:
  - host: dashboard.domain.com
    http:
      paths:
      - backend:
          service:
            name: kubernetes-dashboard-web
            port:
              name: web
        path: /
        pathType: ImplementationSpecific
      - backend:
          service:
            name: kubernetes-dashboard-api
            port:
              name: api
        path: /api
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - dashboard.domain.com
    secretName: kubernetes-dashboard-letsencrypt-cert
```
</details>

### What did you expect to happen?

Formalized `ingressClassName` field should be used, with the annotation formally deprecated.

The Helm install [docs](https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard) list the supported Kubernetes versions as `>=1.21.0-0`. The `ingressClassName` field was introduced in `v1.18`, so all supported versions should understand it.

This is confusing to users, as the Helm value `ingressClassName` exactly matches the Ingress `ingressClassName` field in use since Kubernetes `v1.18`. For any end user on a supported Kubernetes version, this would be the expected behavior rather than the annotation, which has been deprecated. This would be especially confusing if  a user intentionally configured a value that was different than the default IngressClass, only to have their selection populated in the annotation, which may not be recognized or honored by their chosen IngressClass.

### How can we reproduce it (as minimally and precisely as possible)?

Installing with the defaults via Helm.

### Kubernetes Dashboard version

Helm v7.0.0, Dashboard v3.0.0-alpha0

### Kubernetes version

v1.27.3+k3s1
