### ISSUE TITLE
[helm] v3 NetworkPolicy not working

### ISSUE THREAD

**Issue by PatrickSpies** [kubernetes/dashboard#8045]
### What happened?

When deploying the helm-chart v7 with `app.security.networkPolicy.enabled = true`, the NetworkPolicy is created with hardcoded port https:
```yaml
  ingress:
    - ports:
      - port: https
        protocol: TCP
```
Source: https://github.com/kubernetes/dashboard/blob/master/charts/helm-chart/kubernetes-dashboard/templates/security/networkpolicy.yaml#L37

This Networkpolicy is not working, as the default-ports for the applications are `api` and `web`:
```yaml
            - containerPort: 9000
              name: api
              protocol: TCP
```
```yaml
            - containerPort: 8000
              name: web
              protocol: TCP
```

This leads to not being able to access the dashboard.

### What did you expect to happen?

The Networkpolicy should contain the correct ports.

### How can we reproduce it (as minimally and precisely as possible)?

Template or deploy the current v7 of the helm-chart with `app.security.networkPolicy.enabled = true`.

### Anything else we need to know?

Same issue seems to exist for the ServiceMonitor, see https://github.com/kubernetes/dashboard/blob/master/charts/helm-chart/kubernetes-dashboard/templates/extras/servicemonitor.yaml#L34

### Kubernetes Dashboard version

helm-chart v7.0.2

### Kubernetes version

Server Version: v1.26.3
