### ISSUE TITLE
Accessing behind a reverse proxy

### ISSUE THREAD

**Issue by mbaykara** [kubernetes/dashboard#8053]
### What happened?

I deployed the latest helm chart with following my-values.yaml. I want to access the dashboard via `http://IP/`
```yaml
nginx:
  enabled: false 
cert-manager:
  enabled: false 
metrics-server:
  enabled: false 
metricsScraper:
  enabled: false
```

And Traefik is running in my cluster as reverse proxy. 

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kubernetes-dashboard-ingressroutes
  namespace: kubernetes-dashboard
spec:
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: kubernetes-dashboard-web 
          namespace: kubernetes-dashboard
          port: 8000
```
I am getting White Browser screen.
Beside this, with
```bash
k port-forward svc/kubernetes-dashboard-web 8000 
```
getting same issue.

### What did you expect to happen?

If I go to http://NODE_IP/ be able to see Kubernetes Dashboard UI

### How can we reproduce it (as minimally and precisely as possible)?

Deploy with values above and try to access UI.

### What browsers are you seeing the problem on?

Chrome, Safari

### Kubernetes Dashboard version

v7.0.0

### Kubernetes version

1.26.0

**Comment by floreks** [comment]
Where is the api service path mapping? UI won't work without access to the API.

**Comment by mbaykara** [comment]
Okay, I enabled api path then it is working but still interesting implementation. 
* Why forcing to create ingress?
* Why forcing to expose /api endpoint?

**Comment by mbaykara** [comment]
I've successfully enabled the API path, and it appears to be functioning, although the implementation is quite intriguing. I'm curious about a couple of things:

Why is it necessary to create an ingress forcefully?
Why is there a requirement to expose the /api endpoint?
Why forcefully some issuer? Either forcing using selfsigned or some dummy values in order to not create resources.
The new helm chart seems to have unnecessary complexity due to the layered subdirectories. These changes have introduced more challenges rather than improvements.

**Comment by floreks** [comment]
> Why is it necessary to create an ingress forcefully?

We will update helm deployment to allow disabling ingress and configuring custom software that will take care of exposing Dashboard. Right now ingress is used in order to expose api/web containers together on a single domain, otherwise UI won't be able to access the API. We will also look into hiding the API in the future, but solving this via configuration was the easiest approach at this time.

> Why is there a requirement to expose the /api endpoint?

This is a technical limitation of how web container works. We would need to get rid of our scratch base image and run a forwarding proxy inside the web container in order to hide the API. Right now UI expects that API will be exposed and accessible under the same domain on `/api` path.

> Why forcefully some issuer? Either forcing using selfsigned or some dummy values in order to not create resources.

We are using selfsigned cert generated by cert-manager as the default. It was just easier to rely on third-party software to provide certificates that can be used to expose Dashboard. It can be also easily adapted to generate real certificates. We will add an option to disable cert-manager and provide a custom certificate. It will be up to the user to decide how to do this in the end.

> The new helm chart seems to have more complexity due to the layered subdirectories. These changes have introduced more challenges rather compare the previous versions.

The complexity of the whole installation has changed due to architecture changes in the Dashboard itself. If we want to be able to scale and properly support big clusters we need to do that. In the future, we want to add support for GQL API, informers and split API itself into more dedicated services. All of that will increase the complexity even further.

**Comment by kladiv** [comment]
@mbaykara I configured like below in my environment (with a shared domain + different prefixes for microservices):

```yaml
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: kubernetes-dashboard-stripprefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - "/k8s"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kubernetes-dashboard
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`site.example.org`) && PathPrefix(`/k8s`)
      kind: Rule
      services:
        - name: kubernetes-dashboard-web
          port: 8000
      middlewares:
        - name: kubernetes-dashboard-replacepathregex
    - match: Host(`site.example.org`) && PathPrefix(`/k8s/api`)
      kind: Rule
      services:
        - name: kubernetes-dashboard-api
          port: 9000
      middlewares:
        - name: kubernetes-dashboard-replacepathregex
```

I guess it could work with config below too (if a dedicated domain is used):

```yaml
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kubernetes-dashboard
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kube.example.org`)
      kind: Rule
      services:
        - name: kubernetes-dashboard-web
          port: 8000
    - match: Host(`kube.example.org`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: kubernetes-dashboard-api
          port: 9000
```

**Comment by mbaykara** [comment]
@kladiv In my specific use case, I have to configure without DNS. I have done as follows:

```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: dashboard-middleware
  namespace: kubernetes-dashboard
spec:
  replacePathRegex:
    regex: "^/dashboard(/|$)(.*)"
    replacement: "/${2}"
--- 
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kubernetes-dashboard-ingressroutes
  namespace: kubernetes-dashboard
spec:
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: dashboard-middleware
          namespace: kubernetes-dashboard
      services:
        - name: kubernetes-dashboard
          namespace: kubernetes-dashboard
          port: 8080
```

**Comment by irreleph4nt** [comment]
I am not an expert for ingress, but the following is working for me using `v3.0.0-alpha0` behind `ingress.nginx` together with a cluster issuer for certificates. I serve the dashboard on subpath `/k3s`. It should be rather easy to asapt this to serve the dashboard on a dedicated subdomain.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header Accept-Encoding "";
        sub_filter '<base href="">' '<base href="/k3s/">';
        sub_filter_once on;
        rewrite ^(/k3s)$ \$1/ redirect;
        rewrite "(?i)/k3s(/|$)(.*)" /\$2 break;
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - my.tld
    secretName: my.tld-cert
  rules:
  - host: my.tld
    http:
        paths:
          - path: /k3s(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: kubernetes-dashboard-web
                port:
                  number: 8000
          - path: /k3s/api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: kubernetes-dashboard-api
                port:
                  number: 9000
```

**Comment by georglauterbach** [comment]
I was running into the same issue today. This is quite unexpected, and seem unwarranted to me really. It'd be awesome to have the option that lets the web service access the API inside the cluster (pod-to-pod).

---

For those using Traefik, this is what a minimal configuration for the Helm chart `v7.0.0-alpha1` could look like (running inside the namespace `kubernetes-dashboard`):

```yaml
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: kubernetes-dashboard

spec:
  entryPoints: [websecure]

  routes:
    - match: Host(`dashboard.domain.test`)
      kind: Rule

      services:
        - name: kubernetes-dashboard-web
          namespace: kubernetes-dashboard
          port: web
          scheme: http

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: kubernetes-dashboard-api

spec:
  entryPoints: [websecure]

  routes:
    - match: Host(`dashboard.domain.test`) && PathPrefix(`/api`)
      kind: Rule

      services:
        - name: kubernetes-dashboard-api
          namespace: kubernetes-dashboard
          port: api
          scheme: http

```

**Comment by georglauterbach** [comment]
This is still a problem.

/remove-lifecycle stale

**Comment by floreks** [comment]
Dynamic angular app base href will be covered by #8735. It will be enough now to only rewrite target in your ingress using i.e. `nginx.ingress.kubernetes.io/rewrite-target: /$2` annotation and `/<path>(/|$)(.*)` as the path. Configuration snippet will no longer be needed.

**Comment by georglauterbach** [comment]
How is this related to not requiring a dedicated ingress at all? We need is for the traffic to stay cluster-internal, without a second ingress route required.

**Comment by floreks** [comment]
With the gateway in front of our containers that is configured to route requests based on request path to specific containers having a first-party support for subpath would be extremely complicated now. I think being able to avoid configuration snippets and relying on simple target rewrite in ingress is a good middle-ground.

@georglauterbach can you explain your use case? It should still be possible to solve via configuration.

**Comment by georglauterbach** [comment]
No, I think that's not what I meant, really:

> It'd be awesome to have the option that lets the web service access the API inside the cluster (pod-to-pod).

Is this solved? As far as I understand, it is not - we're just talking about some rewrites for the ingress, but I want to get rid of the ingress for the API completely. We need the option for pod-to-pod communication between the web and API pod.

What just came to my mind: rewriting DNS queries to have traffic remain internal to the cluster could probably be done as well? I will see whether that works.

**Comment by floreks** [comment]
Ingress for API is no longer needed as of the latest release. We now use the gateway to route the traffic and it exposes the whole Dashboard as it would be a single container. 

Having pod-to-pod heavily complicates the whole setup since we now have more than just API and Web and it would require too much effort to maintain both web and frontend compatibility with other containers.

**Comment by georglauterbach** [comment]
> We now use the gateway to route the traffic and it exposes the whole Dashboard as it would be a single container.

Which gateway - do you mean the Gateway API?

**Comment by Genmutant** [comment]
I tried the new version with a traefik IngressRoute to the kong proxy, but I only get a 500 error and no dashboard at all anymore. Are there more configrution options I didn't set correctly? Also I'm quite new to traefik so I might have made an error in my Router.

```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kubdashboard-ingressroute
  namespace: kubernetes-dashboard
spec:
  entryPoints: [websecure]
  routes:
    - kind: Rule
      match: PathPrefix(`/kubernetes-dashboard`)
      services:
      - kind: Service
        name: apache-kong-proxy
        namespace: kubernetes-dashboard
        port: kong-proxy-tls
      middlewares:
      - name: stripkubdashboard
        namespace: kubernetes-dashboard

---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripkubdashboard
  namespace: kubernetes-dashboard
spec:
  stripPrefix:
    prefixes:
      - "/kubernetes-dashboard"
    forceSlash: true

```
