### ISSUE TITLE
Helm Chart v7.0.3 ServiceMonitor is Invalid

### ISSUE THREAD

**Issue by matthenry87** [kubernetes/dashboard#8142]
### What happened?

Generated ServiceMonitor's spec.endpoints[0].path is placed at spec.path instead causing it to be missing when applied with helm, and unable to create when synchronized with ArgoCD.

### What did you expect to happen?

ServiceMonitor should place path in correct spot.

### How can we reproduce it (as minimally and precisely as possible)?

Template out the chart with ServiceMonitor enabled and inspect:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-dashboard-kubernetes-dashboard
  labels:
    helm.sh/chart: kubernetes-dashboard-7.0.3
    app.kubernetes.io/instance: k8s-dashboard
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubernetes-dashboard
  annotations:
spec:
  endpoints:
    - port: https
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  path: /metrics
  selector:
    matchLabels:

      helm.sh/chart: kubernetes-dashboard-7.0.3
      app.kubernetes.io/instance: k8s-dashboard
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kubernetes-dashboard
```

### Kubernetes Dashboard version

v3.0.0-alpha0, chart v7.0.3

### Kubernetes version

1.27
