### ISSUE TITLE
Logged in with auth header but unauthorized 

### ISSUE THREAD

**Issue by teceP** [kubernetes/dashboard#8261]
### What happened?

To log in, I use a oauth2-proxy and keycloak, which has a client configured.

I get authenticated with this ingress annotations:
```      annotations:
        nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
        nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
        nginx.ingress.kubernetes.io/auth-response-headers: "Authorization"
        nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
```

Afterwards, I get automatically redirected to my kubernetes dashboard UI.
The Login Status says "Logged in with auth header" and keycloak has an active session for my user.

Now I cannot see any ressource and I get a "Unauthorized" notification.
<img width="1067" alt="image" src="https://github.com/kubernetes/dashboard/assets/44495947/e99bf276-c119-4520-b707-4cfed0654157">

I do have the admin RBACs installed in my cluster:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kubernetes-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kubernetes-dashboard
```

### What did you expect to happen?

See all ressources in the dashboard.

My user is in group "/admin". Do I need any corrosponding RBAC? Is the Dashboard looking for any special claim in the JWT?

### How can we reproduce it (as minimally and precisely as possible)?

1.
2.
3.

### Anything else we need to know?

- oauth2-proxy:6.16.1 from Helm Artifacts
- kubernetes-dashboard:7.0.0-alpha0 from Helm Artifacts
- ingress-nginx:4.7.1 from Helm Artifacts
- keycloak:16.1.1 From Helm Bitnami Artifacts
- kuberntes:1.26.4-4

### What browsers are you seeing the problem on?

Chrome, Firefox

### Kubernetes Dashboard version

7.0.0-alpha0

### Kubernetes version

1.26.4-4
