### ISSUE TITLE
Problem with connecting another cluster to Kubernetes Dashboard

### ISSUE THREAD

**Issue by codeRuslan** [kubernetes/dashboard#8422]
### What happened?

I have one Kubernetes cluster with a Kubernetes dashboard, and I have another Kubernetes Cluster Which I want to monitor with deployed dashboard-metrics-scraper, I have tried to use kubeconfig, which I use with no problems usually to access my cluster that have credentials to my cluster, 

```
apiVersion: v1
kind: Config
clusters:
  - name: <censored>
    cluster:
      server: <censored>
      certificate-authority-data: >-
       <censored>
users:
  - name:<censored>
    user:
      token: >-
        <censored>
contexts:
  - name: <censored>
    context:
      user: <censored>
      cluster: <censored>
      namespace: <censored>
current-context: <censored>
```
with credentials to cluster but I got the following error on login page:

Unauthorized (401): Invalid credentials provided

I was trying to do find any other issues, maybe someone have any instruction or thoughts on creating connection to another cluster, which would be accessible from Kubernetes Dashboard

### What did you expect to happen?

Getting access to monitor my another Kubernetes cluster

### How can we reproduce it (as minimally and precisely as possible)?

Just trying to login with your own kubeconfig file for another cluster

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

2.7.0

### Kubernetes version

1.26.2
