### ISSUE TITLE
[Multi-Tenant Auth] Ability to customize the namespaces dropdown behavior/contents

### ISSUE THREAD

**Issue by mecampbellsoup** [kubernetes/dashboard#8496]
### What would you like to be added?

We run a multi-tenant k8s cluster and use namespaces to segregate customers from one another.

I've setup the k8s dashboard UI to proxy auth to the logged-in user and use its credentials. This part is working as expected.

The remaining glaring issue with rolling this out to customers is that I don't have the ability to configure or customize the behavior of the namespaces dropdown list:

<img width="1420" alt="image" src="https://github.com/kubernetes/dashboard/assets/2043821/6484f8e3-07b1-42c2-93af-43a76ec7b3bf">

`default` is confusing here and that namespace is most definitely not something our customers will be able to access.

We worked with kubeapps team and [implemented a fallback mechanism](https://github.com/vmware-tanzu/kubeapps/blob/main/chart/kubeapps/values.yaml#L1614-L1626) there for something similar - would something like this be possible in k8s dashboard UI? Or is there some existing mechanism by which we can configure or even _disable_ the namespaces dropdown?

### Why is this needed?

For better multi-tenant cluster support, we need the ability to configure some sort of fallback so that our customers can rely on the UI's namespaces dropdown to contain the list of namespaces they are able to access.

This feature is necessary for multi-tenant clusters in which isolation is done via namespaces (i.e. customer A has namespace `tenant-a`, customer B has namespace `tenant-b`, etc., and neither has much cluster-scoped RBAC as it is a shared cluster).

Here is how the api namespace endpoint currently responds in e.g. a shared cluster where users' namespaces are segregated (and those users do not have list namespaces RBAC in the cluster):

```json
{
 "listMeta": {
  "totalItems": 0
 },
 "namespaces": [],
 "errors": [
  {
   "ErrStatus": {
    "metadata": {},
    "status": "Failure",
    "message": "namespaces is forbidden: User \"mcampbell+dev+11-16-2023@coreweave.com\" cannot list resource \"namespaces\" in API group \"\" at the cluster scope",
    "reason": "Forbidden",
    "details": {
     "kind": "namespaces"
    },
    "code": 403
   }
  }
 ]
}
```
With this response, the user sees the following namespace dropdown:
![image](https://github.com/kubernetes/dashboard/assets/2043821/1a7bebd2-a855-48c9-9fca-86ef9c795d58)

So in summary: in clusters where users do not have RBAC to list namespaces, there needs to be a programmatic way to modify the list of namespaces returned by `/api/v1/namespace` endpoint to answer the question "what namespaces does this [auth proxied] user have access to?" An acceptable fallback alternative would be to make the [namespaces list setting](https://github.com/kubernetes/dashboard/blob/master/modules/api/pkg/settings/api/types.go#L126) dynamic and/or configurable per-user as well.

Kubeapps has implemented something similar (we worked w/ them on it) where you can configure a values `trustedNamespaces.headerName` and `trustedNamespaces.headerPattern` that allow the backend API to extract "valid" accessible namespaces from another proxied request header. For kube dashboard, since you already support proxying the `Impersonate-*` k8s request headers, one of those could probably be used; or we could implement something similar to kubeapps where the proxied header name is entirely configurable.

https://github.com/vmware-tanzu/kubeapps/blob/main/chart/kubeapps/values.yaml#L1614-L1626

**Comment by mlbiam** [comment]
Happy to help on a PR for this.

**Comment by floreks** [comment]
You can specify the fallback namespace list and default namespace via settings page or directly via config map that stores settings.

**Comment by mlbiam** [comment]
> You can specify the fallback namespace list and default namespace via settings page or directly via config map that stores settings.

this doesn't really help in a multi tenant environment because it's static.  User's access is going to be different based on the logged in user, so having a static list doesn't solve the UX issue this feature request does.

**Comment by floreks** [comment]
Using a custom header seems to be the only viable solution to me. It should not be hard to add on the backend side. Unfortunately, I have almost no free time lately to work on the Dashboard. The feature work would have to be contributed by someone else. I could give some pointers if needed though.

**Comment by mlbiam** [comment]
@floreks would it need to be against the 3.0.0 branch?  I don't know how close that is to release.

**Comment by floreks** [comment]
> @floreks would it need to be against the 3.0.0 branch?  I don't know how close that is to release.  

Ye, it would have to be a PR to the main branch. It is marked alpha just because the helm chart configuration might not be flexible enough to work for most users. Other than that api and frontend didn't really change. They were just split into separate containers.

**Comment by mecampbellsoup** [comment]
I can work on this, but what is the easiest way to get a containerized dev workflow going? We use Skaffold typically which works great w/ relatively vanilla builds, but the UI's API [Dockerfile](https://github.com/kubernetes/dashboard/blob/4ee7249cbb26f16500117703d452956362d77629/modules/api/Dockerfile#L28) is doing some unconventional stuff (seems like it depends on `Makefile` to have populated the `.dist` directory for instance)... any dev tips would be appreciated!

**Comment by mecampbellsoup** [comment]
@floreks or @mlbiam - either of you guys know how I can get the api backend working w/ a combination of in-cluster config (i.e. the `kubernetes-dashboard` service account should mount and use the standard config via `/var/run/secrets/kubernetes.io/serviceaccount` in the pod), _plus_ adding impersonation headers?

My apiserver keeps responding w/ 401 unauthorized:

```
E1201 22:37:42.011121       1 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, Token has been invalidated]"
E1201 22:37:42.011137       1 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, Token has been invalidated]"
I1201 22:37:42.011206       1 httplog.go:94] "HTTP" verb="GET" URI="/api/v1/namespaces/tenant-dev-eac4f6-ns1" latency="2.930588ms" userAgent="dashboard/UNKNOWN" srcIP="10.241.126.247:42138" resp=401
I1201 22:37:42.011216       1 httplog.go:94] "HTTP" verb="GET" URI="/api/v1/namespaces/tenant-dev-eac4f6-ns1/events" latency="3.123772ms" userAgent="dashboard/UNKNOWN" srcIP="10.241.126.247:42138" resp=401
```

I'm passing the SA secret's token data via `Authorization: Bearer {token}`:
```
(⎈|default:kubernetes-dashboard)mcampbell-1➜  ~/github/coreweave/k8s-services/dev : mc/cloud/add-kube-dashboard-chart ✘ :✹✭ ᐅ  k neat get secret api-kubernetes-dashboard-token-p9jq9 | yq -r .data.token | base64 -d
eyJhbGciOiJSUzI1NiIsImtpZCI6IjJzLVhhOEpsLUtTREdKYXlqaDMtQktqYkZ4WDQwNW1aYjhhM2dRbHUybWsifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhcGkta3ViZXJuZXRlcy1kYXNoYm9hcmQtdG9rZW4tcDlqcTkiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiYXBpLWt1YmVybmV0ZXMtZGFzaGJvYXJkIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMWU3ZjllMWUtMWM1NC00ZTkxLWJhYWMtY2JlYzZmOTg0MWM1Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmVybmV0ZXMtZGFzaGJvYXJkOmFwaS1rdWJlcm5ldGVzLWRhc2hib2FyZCJ9.YGsxcg0h3J4ajEfyYRoN5aCpQb_A2N8aOUhegQX1bWrxWD74TK9XszNnS_Om2D9jspEVlNmQAnkiHljdBVCe6Em8PLcTdTOpIrKLxQ6_xihpfPLEXw7mKAQo_D-d4YK-TNAaNUVDd88k9ZpSBAhoqhdahal6gXTmuoCAU6bBWilBkUjaopOt8BL6Q01WgsGt6tSTVvRNXiFekuLIy6J10c4-7Y9Lst7qkkJfmY2Arv3Onrk3B5F3JMo6mM0SOhVEfR-6hvsGPosFDv_LVKTE9J0fiB-vQdeGTsED941fZymiI-OGqDQwnWj6RYoZJA1WoUGcvO9PxgwA7o-Cue77RA
```

**Comment by mlbiam** [comment]
The permissions on the dashboard's sa are irrelevant. With impersonation you need an authorization header with a token that is allowed to impersonate the user and the correct headers for who to impersonate. The dashboard's sa is only used when there's no external token or login cookie

**Comment by mecampbellsoup** [comment]
> I think if you created a kubeconfig file that was accessible from your dev environment with your certificate and a token you'd be all set from that perspective.

The issue w/ using a kubeconfig is that the token is _dynamic_ or variable. Each user that interacts with the dashboard (since we have a multi-tenant cluster) will provide a different token (i.e. `Cookie: sessionid=123abc`) that needs to be included w/ the request from dashboard api to k8s apiserver via our auth proxy ingress. Does that make sense?

**Comment by mlbiam** [comment]
> The issue w/ using a kubeconfig is that the token is dynamic or variable. Each user that interacts with the dashboard (since we have a multi-tenant cluster) will provide a different token (i.e. Cookie: sessionid=123abc) that needs to be included w/ the request from dashboard api to k8s apiserver via our auth proxy ingress. Does that make sense?

two different things.  The kueconfig used by the API server doesn't do anything besides tell the dashbaord where the API server is and what cert to use.  The token is only used if `--skip-login` is enabled.

> Yes, but would be easy to modify the configuration to enable this to be customizable.

1. I would consider this a new issue that should be opened if you really want to implement it
2. I would highly recommend against this approach.  Header based auth in Kubernetes doesn't require any authentication outside of having a valid client certificate (which I don't know if the API server connection from the dashboard to the API server would support? ).  You're using an Ingress so my guess is that your Ingress controller is what has the client cert, so that protection doesn't exist either.  While I understand you want to do this for development, this feature makes it easier to build a very insecure environment.  I'm all for making security easier, but not for making a breach friendly environment easier.

**Comment by mecampbellsoup** [comment]
@mlbiam do you have an example of such a kubeconfig anywhere? I'm a little unclear on how to populate the commented out `users` and to some extent `contexts` sections below:

```yaml
apiVersion: v1
           clusters:
             - cluster:
                 certificate-authority-data: <base64-encoded string containing the "ca.crt" in the TLS secret associated w/ the ingress hostname on following line>
               server: https://cloud-app-kubernetes-ingress.cloud/k8s  # This ingress host ensures all traffic is sent via our API gateway before hitting the k8s apiserver
               name: coreweave
           contexts:
             - context:
                 cluster: coreweave
                 # namespace: is this needed?
                 # user: is this needed?
               name: coreweave
           current-context: coreweave
           kind: Config
           preferences: {}
			###################################
			# ASSUME ALL BELOW ARE COMMENTED OUT
			# What "user" will this kubeconfig operate as?
           users:
            - name: minikube
              user:
              client-certificate: /home/hector/.minikube/profiles/minikube/client.crt
              client-key: /home/hector/.minikube/profiles/minikube/client.key
           users:
             - name: token-NNRMoro77pGm6FsZvkhU
               user:
                 token: JpuaBbZvDjHR3xqayJ8YYR2NKabQrcJaUWnu5jm3
```
