### ISSUE TITLE
No longer possible to put it behind Basic Authentication

### ISSUE THREAD

**Issue by spantaleev** [kubernetes/dashboard#8772]
### What happened?

I'm using Token Authentication for Kubernetes Dashboard.
As an additional layer of security, I'm also putting everything behind Basic Authentication (see my Helm configuration values below).

It seems like this worked well in `7.0.0-alpha1` of the Helm chart, but no longer works in `7.1.2`.

Right now, you can load the Kubernetes Dashboard web UI (protected by Basic Authentication). However, as soon as you log in via via the web UI (by providing a Token), this token starts getting passed as an `Authorization` header (`Authorization Bearer ...`), overwriting the `Authorization: Basic ..` header used for clearing Basic Auth.

The previous version of Kubernetes Dashboard (installed by `7.0.0-alpha1` of the Helm chart), seemed to be passing the Kubernetes Token as a `Cookie` or possibly some `jwetoken` header (I'm not sure), but wasn't trying to send it in `Authorization` and wasn't causing problems when combining this kind of usage with Basic Auth.

### What did you expect to happen?

I expected that it'd be possible to use Basic Auth and that whatever authentication happened later on would not be in conflict with it.

### How can we reproduce it (as minimally and precisely as possible)?

I'm installing via the Helm chart with the following values:

```yml
app:
  ingress:
    enabled: true
    hosts:
      - MY_HOSTNAME
    ingressClassName: nginx
    issuer:
      name: letsencrypt-live
      scope: cluster
    tls:
      secretName: kubernetes-dashboard-tls
    annotations:
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: kubernetes-dashboard-basic-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Kubernetes Dashboard'
```

I'm using ingress-nginx and cert-manager.

### Kubernetes Dashboard version

Helm chart 7.1.2

### Kubernetes version

v1.28.6
