### ISSUE TITLE
Unable to login after update to chart 7.1.2

### ISSUE THREAD

**Issue by vittoriocanilli** [kubernetes/dashboard#8820]
### What happened?

On my AKS cluster the authentication for the dashboard is managed with OAuth2 proxy and an Azure app. It worked correct till the version `7.0.0-alpha1` of the dashboard's Helm chart.

Unfortunately after the update to version `7.1.2` I land on this screen after the login:
![Screenshot 2024-03-20 at 15 57 40](https://github.com/kubernetes/dashboard/assets/6400531/4be97332-c989-4e3e-aeb3-5330d66406c4)
I guess that I would get the same error with any version greater than `7.0.0-alpha1`, i.e. after the **auth** and **kong** modules were added

### What did you expect to happen?

I would expect to be logged successfully on the dashboard. I have checked similar issues here and I have opened the `/api/v1/me` endpoint of my dashboard, which simply returns this:
`{"authenticated":true}`
If I try to open the dashboard again after that I have checked the `/api/v1/me` endpoint on the browser, then I am logged in the dashboard. So I guess that there is some step missing.

### How can we reproduce it (as minimally and precisely as possible)?

Here are the `app` values which could are relevant for the authentication:
```yaml
app:
  ingress:
    enabled: true
    ingressClassName: nginx
    issuer:
      name: letsencrypt-production
      scope: cluster
    tls:
      secretName: le-kubernetes-dashboard-tls
    annotations:
      nginx.ingress.kubernetes.io/auth-signin: "https://login.mycluster.azure.mycompany.com/oauth2/start?rd=$scheme://$host$request_uri"
      nginx.ingress.kubernetes.io/auth-url: "https://login.mycluster.azure.mycompany.com/oauth2/auth"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
      nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-Access-Token"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        auth_request_set $token $upstream_http_x_auth_request_access_token;
        proxy_set_header Authorization "Bearer $token";
    hosts:
      - dashboard.mycluster.azure.mycompany.com
  settings:
    global:
      clusterName: "mycluster.azure.mycompany.com"
```

### Anything else we need to know?

For the `auth` module I have simply set the node selector, while all other values are set to the default:
```yaml
auth:
  nodeSelector:
    node-selector-key: system
```
For the `kong` module I did not overwrite any value.

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

7.1.2

### Kubernetes version

1.27.7
