### ISSUE TITLE
Unknown error (200): Http failure during parsing for https://<site>/api/v1/csrftoken/login

### ISSUE THREAD

**Issue by noelashford** [kubernetes/dashboard#8829]
### What happened?

I use an ingress controller to access the dashboard and even thought the backend and frontend are https, it seems to think there is an HTTP parsing issue somewhere ? <site. is obfuscation for the actual site.

### What did you expect to happen?

I should be able to browse the dashboard.

### How can we reproduce it (as minimally and precisely as possible)?

Create a backend https ingress w front end HTTPS as well, you will see this: `Unknown error (200): Http failure during parsing for https://<site>/api/v1/csrftoken/login`

### Anything else we need to know?

The ingress is as follows:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: letsencrypt-production
  generation: 1
  name: dashboard
  namespace: kubernetes-dashboard
spec:
  rules:
  - host: <site>
    http:
      paths:
      - backend:
          service:
            name: kubernetes-dashboard-kong-proxy
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
    - hosts:
      - <site>
      secretName: k8s-dashboard
```

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

current

### Kubernetes version

Client Version: v1.25.0 Kustomize Version: v4.5.7 Server Version: v1.23.3

**Comment by TheoMorkel** [comment]
Is there any update on this issue? I am experiencing it as well.

**Comment by floreks** [comment]
That does not look like an issue on our side. Most likely it's a configuration issue on your side.

**Comment by noelashford** [comment]
I'm not so sure it's a configuration issue. Backend https & front end and
it is telling me there's an http error when the token is pasted in. Prior
versions worked with the exact same config at least for me.

**Comment by floreks** [comment]
You could try checking for logs in `auth` pod. Right now I am unsure how it could originate on our side.

**Comment by garymm** [comment]
I'm seeing this also.

@noelashford which version worked for you?

**Comment by tynianov1** [comment]
I had the same issue. Do we have any updates here? Thanks

**Comment by floreks** [comment]
Is there anything in the browser console/network tab in the dev tools that could help?

Another thing I can think of is that there is an issue with SSL passthrough. You might try adding the below annotations to the ingress.
```
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
```

**Comment by juvivas** [comment]
i resolved this issue modifying the kong configuration.
```
kong:
  proxy:
    http:
      enabled: true
```
so my ingressroute target the kong service at 80 port

**Comment by meekara** [comment]
I have same issue and changing kong proxy http enable does not fix issue and no log in auth pod. I'm using traefik ingress.
It work with port forward as well.
![001](https://github.com/kubernetes/dashboard/assets/12957393/ffe8c48f-7b1c-476a-9e67-881e0ecf934c)

**Comment by juvivas** [comment]
> I have same issue and changing kong proxy http enable does not fix issue and no log in auth pod. I'm using traefik ingress. It work with port forward as well. ![001](https://private-user-images.githubusercontent.com/12957393/321036095-ffe8c48f-7b1c-476a-9e67-881e0ecf934c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTEyMDAsIm5iZiI6MTcxMjk1MDkwMCwicGF0aCI6Ii8xMjk1NzM5My8zMjEwMzYwOTUtZmZlOGM0OGYtN2IxYy00NzZhLTllNjctODgxZTBlY2Y5MzRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDE5NDE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNzZmYzZmN2UwZWZlNzU4MTQxMzFhODUyYzVmNWI3NWYwNjk3ZWQ4ZjUwYjY0NjM2NzY2NzE4NWRhN2NkMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZfYBaHLnOb1P4DX9XIYszOBTztsmbQ7WLV05FLqoa0Y) ![002](https://private-user-images.githubusercontent.com/12957393/321037632-7907104d-573e-4d2b-89b3-81b9bb93e269.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTEyMDAsIm5iZiI6MTcxMjk1MDkwMCwicGF0aCI6Ii8xMjk1NzM5My8zMjEwMzc2MzItNzkwNzEwNGQtNTczZS00ZDJiLTg5YjMtODFiOWJiOTNlMjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDE5NDE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkNjA4ZWQxYWRjMTE2NDNjNTczZTk0NTg3NjdiNmMyOTE5OGQ0ZTY5OGZkYTM0NTA0YWY3MjZlNjViNDI1YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3ZUbdogQWIgOH7HePnzAuLbLuZkwC6qcaPybCqQY5CQ)
i used these parameters for helm installation
```
api:
  containers:
    args:
      - '--disable-csrf-protection=true'
web:
  scaling:
    replicas: 2
    args:
      - '--disable-csrf-protection=true'
kong:
  proxy:
    http:
      enabled: true
```

**Comment by thunko** [comment]
I was facing the same issue and thought it could have relation with this one [here](https://github.com/kubernetes/dashboard/issues/8794)

I configured the same settings as above, except for the web container, which doesn't support the disable csrf argument:
```
# helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard --set 'api.containers.args={--disable-csrf-protection=true}' --set kong.proxy.http.enabled=true
```

Accessed the kong proxy service and authenticated with admin-user token.

**Comment by c0desurfer** [comment]
> That does not look like an issue on our side. Most likely it's a configuration issue on your side.

Probably is, getting same error on fresh install.

**Comment by nevillelyh** [comment]
I ran into this as well and it works after clearing cookies.

**Comment by djereg** [comment]
In my case something went wrong at first try, and the /api/v1/csrftoken/login endpoint has returned the index page what is an html content and MY BROWSER CACHED IT, and every time the frontend called the enpoint, the response was returned from the cache. After disabling the cache it worked well.

Knowing this, you can imagine the 5 hours I spent the last night exploring this. But at least I was able to deepen my relationship with Ingresses and IngressRoutes.

**Comment by floreks** [comment]
This does not look like a bug on our side. Every comment with a solution indicates that. If there will be any evidence suggesting otherwise, we can reopen.

/close

**Comment by kk-technical** [comment]
I have same problem...but still in problem.....
I tried every method... not work...

**Comment by lgmg** [comment]
Also have this problem, it seems to come from
<img width="1321" alt="Capture d’écran 2024-06-06 à 15 36 37" src="https://github.com/kubernetes/dashboard/assets/17902367/3904d4c4-797c-4d14-b276-fb2ecad56a75">

The response seems to be a html page and not a json. (see line indicating fn= "<!-- ...)

**Comment by floreks** [comment]
You have to point to the kong service, not dashboard web. Web part will not work without proper access to the API and auth containers.

**Comment by lgmg** [comment]
thanks for your prompt answer. Using kong-proxy leads to a other error : 
"failed the initial dns/balancer resolve for 'kubernetes-dashboard-web' with: failed to receive reply from UDP server xx.xx.xx.xx:53: timeout". 
It is trying to call the kube-dns service. I probably have a problem with my k8s configuration

**Comment by linonetwo** [comment]
This issue should not be closed, there is no valid solution posted in this issue.
The [login view](https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/README.md#login-view) is buggy and not working.

A currently working workaround is to use https://modheader.com/ browser extension, and manually add `Authorization` header with value `Bearer xxxx`.

**Comment by lgmg** [comment]
I think this is another issue I also currently have. I use the same workaround but with "resquestly". According to me, I have a problem with the proxy configuration which does not transmit the header.

**Comment by lgmg** [comment]
or you may be right, because the authorization bearer token does not appear in the sent request

**Comment by Aleksey-Kalinin** [comment]
I have Istio and Helm and I solved this problem as follows

**Chart.yaml**
```
apiVersion: v2
name: kubernetes-dashboard
dependencies:
  - name: kubernetes-dashboard
    version: 7.5.0
    repository: https://kubernetes.github.io/dashboard/
```

**values.yaml**
``` 
kubernetes-dashboard:
  app:
    ingress:
      enabled: false

  kong: 
    proxy:
      type: ClusterIP
      http:
        enabled: true

  # https://github.com/kubernetes/dashboard/issues/8829
  api:
    containers:
      args:
        - '--disable-csrf-protection=true'
```

**templates/access-control.yaml**
```
apiVersion: v1
kind: ServiceAccount
metadata:  
  name: admin-user  
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:  
  name: admin-user
roleRef:  
  apiGroup: rbac.authorization.k8s.io  
  kind: ClusterRole  
  name: cluster-admin
subjects:
  - kind: ServiceAccount  
    name: admin-user  
    namespace: monitoring
---
apiVersion: v1
kind: Secret
metadata:  
  name: admin-user  
  namespace: monitoring
  annotations:    
    kubernetes.io/service-account.name: "admin-user"
type: kubernetes.io/service-account-token
```

**virtualservice.yaml**
``` 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kubernetes-dashboard-public
  labels:
    app: kubernetes-dashboard
spec:
  gateways:
    - istio-system/feature-ingressgateway
  hosts:
  - dashboard.my-company.com                                              # my  web domain
  http:
    - name: route-kubernetes-dashboard-main
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: kubernetes-dashboard-kong-proxy
            port:
              number: 80
          headers:
            request:
              set:
                Authorization: Bearer eyJhbGciOiJSUz...                           # copy output from kubectl get secret admin-user -n monitoring -o jsonpath={".data.token"} | base64 -d
```

.... **AND DISABLE CACHE IN CHROME to clear garbage from previous failed attempts** 
https://developer.chrome.com/docs/devtools/network/reference?utm_source=devtools&hl=en#disable-cache

Without cleaning cache it is not working in my machine (((

**Comment by naidu72** [comment]
Finally i figured out it is working for me with following changes 
vaules.yml
---------------------------
kong:
  proxy:
    http:
      enabled: true
----------------------------
helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard --set kong.admin.tls.enabled=false -f vaules.yml
----------------------------

**Comment by sumandepnath** [comment]
> In my case something went wrong at first try, and the /api/v1/csrftoken/login endpoint has returned the index page what is an html content and MY BROWSER CACHED IT, and every time the frontend called the enpoint, the response was returned from the cache. After disabling the cache it worked well.
> 
> Knowing this, you can imagine the 5 hours I spent the last night exploring this. But at least I was able to deepen my relationship with Ingresses and IngressRoutes.

Please someone pin this 🥹🥹🥹

**Comment by alexei-g-aloteq** [comment]
I was need to install it using ArgoCD, and figured out, that this is fully possible with just Helm parameters override.

**Most important thing**: Use private browser mode for tests - it disables cache and might save hours for you. Or clear the cache every time.

1. override in Helm Values: **kong.proxy.http.enabled: true** (enables Kong proxy HTTP endpoint)
2. Setup ingress to **publish Kong proxy port 80**, example:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    name: kubernetes-dashboard
    namespace: kubernetes-dashboard
spec:
  ingressClassName: nginx
  rules:
    - host: <your domain here>
      http:
        paths:
          - backend:
              service:
                name: kubernetes-dashboard-kong-proxy
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
```

**Note**: This ingress does not use TLS since I terminate HTTPS on a cloud load balancer (externally). If you need HTTPS support - just extend this definition.

Thats it! You just need to enable HTTP port on the Kong proxy and publish it using ingress.

Bonus!

Here is how to configure publishing using embedded ingress with ArgoCD (but also with Helm):

- **kong.proxy.http.enabled**: true
- **app.ingress.hosts[0]**: <your domain here>
- **app.ingress.enabled**: true
- **app.ingress.tls.enabled**: false (in my case I do not need HTTPS termination here)
- **app.ingress.useDefaultAnnotations**: false (in my case default annotations was invalid)
