### ISSUE TITLE
setting resourceAutoRefreshTimeInterval to 0 does not disable the auto refresh

### ISSUE THREAD

**Issue by rgl** [kubernetes/dashboard#8834]
### What happened?

Setting to zero as explained in the Values.yaml file does not work:

https://github.com/kubernetes/dashboard/blob/7d1785fc680aa71d8589986f2251d91f52bcbe46/charts/kubernetes-dashboard/values.yaml#L67-L68

### What did you expect to happen?

Expected the auto refresh to be totally disabled.

### How can we reproduce it (as minimally and precisely as possible)?

Example, in Ansible syntax:

```yaml
- name: Install kubernetes-dashboard
  kubernetes.core.helm:
    name: kube-dashboard
    chart_ref: kubernetes-dashboard/kubernetes-dashboard
    chart_version: '{{ kind_kubernetes_dashboard_chart_version }}'
    release_namespace: kube-dashboard
    create_namespace: true
    update_repo_cache: true
    values:
      app:
        settings:
          global:
            logsAutoRefreshTimeInterval: 0
            # setting this to 30, works.
            # setting this to 0, does not work. it actually sets to 10 seconds (the default that is hard-coded in the source-code).
            resourceAutoRefreshTimeInterval: 0
```

The source-code is at:

https://github.com/kubernetes/dashboard/blob/7d1785fc680aa71d8589986f2251d91f52bcbe46/modules/web/pkg/settings/settings.go#L29

### Kubernetes Dashboard version

7.1.2

### Kubernetes version

1.29.2
