### ISSUE TITLE
ui updates seem to be too slow

### ISSUE THREAD

**Issue by rgl** [kubernetes/dashboard#8835]
### What happened?

updating any resource takes too long (> 1s) which is substantial higher than the apparently equivalent kubectl command.

### What did you expect to happen?

Expected to see deployments displayed in roughly the same amount of time as `kubectl get deployments -A`.

### How can we reproduce it (as minimally and precisely as possible)?

Observe the time taken with kubectl, 0.068s:

```console
$ time kubectl get deployments -A
NAMESPACE            NAME                                                  READY   UP-TO-DATE   AVAILABLE   AGE
cert-manager         cert-manager                                          1/1     1            1           9h
cert-manager         cert-manager-cainjector                               1/1     1            1           9h
cert-manager         cert-manager-webhook                                  1/1     1            1           9h
kube-dashboard       kube-dashboard-kong                                   1/1     1            1           9h
kube-dashboard       kube-dashboard-kubernetes-dashboard-api               1/1     1            1           9h
kube-dashboard       kube-dashboard-kubernetes-dashboard-auth              1/1     1            1           9h
kube-dashboard       kube-dashboard-kubernetes-dashboard-metrics-scraper   1/1     1            1           9h
kube-dashboard       kube-dashboard-kubernetes-dashboard-web               1/1     1            1           9h
kube-external-dns    kube-external-dns                                     1/1     1            1           9h
kube-external-dns    pdns                                                  1/1     1            1           9h
kube-metallb         kube-metallb-controller                               1/1     1            1           9h
kube-system          coredns                                               1/1     1            1           9h
kube-traefik         kube-traefik                                          1/1     1            1           9h
local-path-storage   local-path-provisioner                                1/1     1            1           9h
pgadmin              pgadmin-pgadmin4                                      1/1     1            1           9h

real	0m0,068s
user	0m0,065s
sys	0m0,016s
```

Getting, and displaying the entire yaml, 0.140s:

```console
$ time kubectl get deployments -A -o yaml
...
real	0m0,140s
user	0m0,112s
sys	0m0,036s
```

Observe the time taken with the browser, 1.2s:

![image](https://github.com/kubernetes/dashboard/assets/43356/9389030a-9322-46ef-82b0-a34641715e7b)

### Anything else we need to know?

This was tested in a kind cluster, with traefik ingress controller, sending data to kong using http (without tls), and lifting all resource limits (also note that modifying the api replicas does not seem to make much difference):

```yaml
- name: Install kubernetes-dashboard
  kubernetes.core.helm:
    name: kube-dashboard
    chart_ref: kubernetes-dashboard/kubernetes-dashboard
    chart_version: '{{ kind_kubernetes_dashboard_chart_version }}'
    release_namespace: kube-dashboard
    create_namespace: true
    update_repo_cache: true
    values:
      kong:
        proxy:
          http:
            enabled: true
      app:
        settings:
          global:
            logsAutoRefreshTimeInterval: 0
            resourceAutoRefreshTimeInterval: 30
      api:
        scaling:
          replicas: 1
        containers:
          resources:
            requests:
              cpu: 0
              memory: 0
            limits:
              cpu: 0
              memory: 0
      auth:
        containers:
          resources:
            requests:
              cpu: 0
              memory: 0
            limits:
              cpu: 0
              memory: 0
      web:
        containers:
          resources:
            requests:
              cpu: 0
              memory: 0
            limits:
              cpu: 0
              memory: 0
      metricsScraper:
        containers:
          resources:
            requests:
              cpu: 0
              memory: 0
            limits:
              cpu: 0
              memory: 0

```

The entire ansible playbook is at:

https://github.com/rgl/my-ubuntu-ansible-playbooks/tree/upgrade-kubernetes-dashboard

Have a look a the last commit in that branch to see just the kubernetes-dashboard changes.

### Kubernetes Dashboard version

7.1.2

### Kubernetes version

1.29.2

**Comment by rgl** [comment]
@floreks ah that did the trick! now it pretty fast!

**Comment by floreks** [comment]
I will have to investigate that at some point. There were no real changes to metrics gathering. Maybe there is an issue with metrics server responsiveness.

**Comment by rgl** [comment]
hummm I do not have metrics-server installed in my kind cluster. without metrics-server is this expected to be slow?

if so, maybe the [FAQ](https://github.com/kubernetes/dashboard/blob/master/docs/common/faq.md#i-cannot-see-any-graphs-in-dashboard-how-to-enable-them) should make it more explicit?

the [chart values.yaml](https://github.com/kubernetes/dashboard/blob/759ab975c1932b6f46504763e4861063d8d691d1/charts/kubernetes-dashboard/values.yaml#L322-L332) comments seem to be more explicit. maybe put that in the faq?

**Comment by sushain97** [comment]
:wave: I'm experiencing a similar issue after upgrading from a much earlier version. I added:

```yaml
api:
  containers:
    args:
      - --metrics-provider=none
```
and things are substantially better on most pages.

However, some pages still struggle to load quickly (especially the Workloads page) and I have less than 150 pods.

I'm running k3s with the builtin `metrics-server`.

**Comment by sushain97** [comment]
> If you start clicking too much and spamming API server with requests throttling will kick in and significantly slow down your responses. Restarting API server can 'reset' throttling and it will work faster. Normal use should be ok.

Hmm, I'm still a bit surprised that I can cause throttling by human-scale-clicking around. To be clear, I wasn't trying to stress the system, just view different panels in the UI :)

Here's how the requests from `/#/workloads?namespace=_all` look after ~6 hours of not accessing the dashboard at all:

![image](https://github.com/kubernetes/dashboard/assets/4211838/e59c1cf3-b264-46a5-9a0e-6c674d5db971)

There aren't any timeouts but this is still really slow, right?

**Comment by floreks** [comment]
That is definitely unexpected. What device are you using for your k3s installation?

**Comment by sushain97** [comment]
> That is definitely unexpected. What device are you using for your k3s installation?

4 cores of an AMD EPYC 7371.

Some quick benchmarks:

```
sushain@vesuvianite ~ ❯❯❯ hyperfine 'kubectl get pods -A'           18:20:19
Benchmark 1: kubectl get pods -A
  Time (mean ± σ):     220.6 ms ±   4.1 ms    [User: 207.0 ms, System: 71.1 ms]
  Range (min … max):   214.3 ms … 227.9 ms    13 runs

sushain@vesuvianite ~ ❯❯❯ hyperfine 'kubectl describe pods -A'      18:20:29
Benchmark 1: kubectl describe pods -A
  Time (mean ± σ):      1.231 s ±  0.031 s    [User: 0.533 s, System: 0.123 s]
  Range (min … max):    1.188 s …  1.294 s    10 runs

sushain@vesuvianite ~ ❯❯❯ hyperfine 'kubectl get deployments -A'    18:20:43
Benchmark 1: kubectl get deployments -A
  Time (mean ± σ):     177.5 ms ±   7.1 ms    [User: 175.0 ms, System: 58.1 ms]
  Range (min … max):   169.8 ms … 195.3 ms    16 runs

sushain@vesuvianite ~ ❯❯❯ hyperfine 'kubectl describe deployments -A'
Benchmark 1: kubectl describe deployments -A
  Time (mean ± σ):      1.021 s ±  0.032 s    [User: 0.426 s, System: 0.121 s]
  Range (min … max):    0.980 s …  1.097 s    10 runs
```

**Comment by floreks** [comment]
We also can't directly compare kubectl to the UI as we have to make more calls than kubectl to get some extra information and apply additional logic such as server side pagination, sorting, filtering. It will always be slower.

**Comment by sushain97** [comment]
> We also can't directly compare kubectl to the UI as we have to make more calls than kubectl to get some extra information and apply additional logic such as server side pagination, sorting, filtering. It will always be slower.

Yep, that makes sense. FWIW I jumped from `docker.io/kubernetesui/dashboard-api:v1.0.0` to `docker.io/kubernetesui/dashboard-api:1.4.1` so there's a lot of changes... maybe I'll try bisecting through the Helm charts at some point.

**Comment by floreks** [comment]
@sushain97 I have been further debugging the performance issue and pinned it down exactly. Add `--sidecar-host` arg to dashboard API deployment. Example: `--sidecar-host=kubernetes-dashboard-metrics-scraper.dashboard` where `kubernetes-dashboard-metrics-scraper` is `metrics-scraper` service name and `dashboard` is your namespace where Dashboard is deployed.

I honestly have no idea what is causing in-cluster service proxy to be super slow compared to accessing metrics scraper with HTTP client through service proxy directly. I don't see anything that changed there recently.

**Comment by sushain97** [comment]
Hm, it doesn't feel too different to me:

![image](https://github.com/kubernetes/dashboard/assets/4211838/af88166d-207b-490d-b76f-33d73ca2cee2)

Here's what I have:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  repo: https://kubernetes.github.io/dashboard/
  chart: kubernetes-dashboard
  targetNamespace: kubernetes-dashboard
  version: 7.2.0
  valuesContent: |-
    app:
      scheduling:
        nodeSelector:
            kubernetes.io/hostname: kube.local.skc.name
    # https://github.com/kubernetes/dashboard/issues/8835
    api:
      containers:
        args:
          - --metrics-provider=none
          - --sidecar-host=kubernetes-dashboard-metrics-scraper.kubernetes-dashboard
    kong:
      proxy:
        http:
          enabled: true
```
