### ISSUE TITLE
Why kong? It consumes a lot of memory resources

### ISSUE THREAD

**Issue by davidroth** [kubernetes/dashboard#8842]
### What happened?

Is there a reason why kong is the new default gateway?
The problem I have with kong is that it consumes a lot of memory resources.
As a result, the nice lightweight dashboard becomes a heavy beast. 🙈

See attached screenshot.
All the new dashboard pods use 10-15MB.
But kong uses over 256MB doing nothing 😔

![image](https://github.com/kubernetes/dashboard/assets/338856/91efd97c-45bf-4b68-946a-0e5aa81d0d7e)

### What did you expect to happen?

Unless there's an important reason for kong, I'd recommend switching to nginx or a similar resource-aware alternative. For example, a simple nginx reverse proxy uses only 10Mib.

**Comment by floreks** [comment]
- This is an actual API Gateway that is designed for API management of apps that use microservices. nginx has a bit different purpose in my opinion. It can be used in front of an API gateway.
- Simple to use and configure. See [config.yaml](https://github.com/kubernetes/dashboard/blob/master/hack/gateway/prod.kong.yml)
- Allows to easily switch between i.e. REST/gRPC/GQL endpoints for routing. This gives us flexibility when we would want to incrementally switch our API to use different protocols.
- Single container, DBLess, in-memory storage for configuration and caching (that's probably why it consumes so much memory)

We have used nginx by default before and I didn't like it. There were lots of configuration issues from users who did not want to use it and had trouble configuring replacement since the microservice approach requires a proxy to act as an API gateway. Configuring Dashboard to work on a subpath was a huge pain too. Right now kong acts as a single point of access and exposes a unified API and the UI. I have looked at other options but this one was the most painless to set up and use in the end.

**Comment by davidroth** [comment]
Thanks for the quick response and the infos provided. 

I can confirm that the initial memory usage of kong went down to 75MB.
That's much better. I would be happy if it were even less, but at least it's a significant improvement.

> After all, nowadays 250 MiB of memory does not seem like much.

Well, it sums up with all the other "system-level" pods in a cluster. Less memory wasted for "system" stuff saves actual money. 💵

**Comment by davidroth** [comment]
@floreks Maybe the chart could also include an option to route to the services just via ingress rules?
E.g. the following ingress definition works perfectly without any kong dependency:

```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
spec:
  incressClassName: alb
  rules:
    - host: url-to-your-dashboard.com
      http:
        paths:
          - path: /api/v1/login
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard-auth
                port:
                  number: 8000
          - path: /api/v1/csrftoken/login
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard-auth
                port:
                  number: 8000
          - path: /api/v1/me
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard-auth
                port:
                  number: 8000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard-api
                port:
                  number: 8000
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard-web
                port:
                  number: 8000
 ```

Of couse this would also work with an nginx ingressClassName if nginx is used as the ingress controller.
