### ISSUE TITLE
Request header or cookie too large

### ISSUE THREAD

**Issue by vittoriocanilli** [kubernetes/dashboard#8878]
### What happened?

On my AKS cluster the authentication for the dashboard is managed with OAuth2 proxy and an Azure app. It worked correctly till the version `7.0.0-alpha1` of the dashboard's Helm chart.

Unfortunately after the update to version `7.1.3` some colleagues of mine land on this screen after the login:
<img width="1512" alt="image-blur" src="https://github.com/kubernetes/dashboard/assets/6400531/a45440b0-eb7a-41a8-80f2-d97142ebb9da">

They tried on various browsers, even in incognito more. They don't see anything from the dashboard; they just see this text:
```
Request header or cookie too large
request_id: <SOME_REQUEST_HEX_ID>
```

### What did you expect to happen?

I would expect that everyone can be logged successfully on the dashboard. I have tried to increase the resources and the replicas of the modules, but nothing seems to help. I have checked the modules' logs, but I could not find any error so far. Could you please point me to the right direction?

### How can we reproduce it (as minimally and precisely as possible)?

Here are the `app` values which could are relevant for the authentication:
```yaml
app:
  ingress:
    enabled: true
    ingressClassName: nginx
    issuer:
      name: letsencrypt-production
      scope: cluster
    tls:
      secretName: le-kubernetes-dashboard-tls
    annotations:
      nginx.ingress.kubernetes.io/auth-signin: "https://login.mycluster.azure.mycompany.com/oauth2/start?rd=$scheme://$host$request_uri"
      nginx.ingress.kubernetes.io/auth-url: "https://login.mycluster.azure.mycompany.com/oauth2/auth"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
      nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-Access-Token"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        auth_request_set $token $upstream_http_x_auth_request_access_token;
        proxy_set_header Authorization "Bearer $token";
    hosts:
      - dashboard.mycluster.azure.mycompany.com
  settings:
    global:
      clusterName: "mycluster.azure.mycompany.com"
```

### Anything else we need to know?

Here are the values for the various modules, in case they could help:
```yaml
web:
  nodeSelector:
    node-selector-key: system
  scaling:
    replicas: 1
  containers:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
api:
  nodeSelector:
    node-selector-key: system
  scaling:
    replicas: 1
  containers:
    args:
      - --v=0
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
auth:
  nodeSelector:
    node-selector-key: system
  scaling:
    replicas: 1
  containers:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
metricsScraper:
  nodeSelector:
    node-selector-key: system
  enabled: true
  scaling:
    replicas: 1
  containers:
    args:
      - --v=0
      - --metric-duration=30m0s
    resources:
      requests:
        cpu: 20m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi
metrics-server:
  enabled: false
cert-manager:
  enabled: false
nginx:
  enabled: false
```

### What browsers are you seeing the problem on?

Chrome, Safari, Others

### Kubernetes Dashboard version

7.1.3

### Kubernetes version

1.27.7

**Comment by floreks** [comment]
This looks like a response directly from kong proxy. You might need to increase buffer size. It can be done by providing `kong.env.XXX` value where XXX is i.e. `nginx_http_large_client_header_buffers` from the documentation.

https://docs.konghq.com/gateway/3.6.x/reference/configuration/#nginx_http_client_header_buffer_size

**Comment by vittoriocanilli** [comment]
Hi @floreks ,
thanks for your reply: I have now solved the issue as you suggested by adding this value:
```yaml
kong:
  env:
    nginx_http_large_client_header_buffers: "8 24k"
```
