### ISSUE TITLE
Issue when trying to complete ACME Challenge for custom domain used in chart: "failed to perform self check GET request Get \"http://<domain>/.well-known/acme-challenge/<token>": EOF"

### ISSUE THREAD

**Issue by adamency** [kubernetes/dashboard#8883]
### What happened?

Hi, I am trying to host the dashboard behind an nginx Ingress Controller. I already have `nginx-ingress` and `cert-manager` installed and working for other services on the cluster.

I have looked at the chart values for the dashboard and this is the override file I have used, believing this should work according to the documentation in the comments of the values.yaml file.

`override.yml`:
```
app:
  ingress:
    enabled: true
    hosts:
      - dashboard.<mydomain>
    ingressClassName: nginx
    issuer:
      name: kubernetes-dashboard-letsencrypt-prod
```

having also already created the `kubernetes-dashboard-letsencrypt-prod` Issuer in the `kubernetes-dashboard` namespace beforehand.

```
helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard -f override.yml
```

The annotation is correctly picked up by `cert-manager`, and the `CertificateRequest`, `Order` and `Challenge` are then correctly created. However the challenge self check never succeeds as cert-manager is receiving an empty response from the server:

```
propagation check failed" err="failed to perform self check GET request 'http://dashboard.<mydomain>/.well-known/acme-challenge/TCvyORbHqI6FZRfEfadnnWO5UlD5i4kQCcFrHqSYlSw': Get \"http://dashboard.<mydomain>/.well-known/acme-challenge/TCvyORbHqI6FZRfEfadnnWO5UlD5i4kQCcFrHqSYlSw\": EOF" logger="cert-manager.challenges" resource_name="kubernetes-dashboard-certs-1-2599902695-2430526343" resource_namespace="kubernetes-dashboard" resource_kind="Challenge" resource_version="v1" dnsName="dashboard.<mydomain>" type="HTTP-01"
```

I guess the issue stems from the use of the Kong Gateway API under the hood which I'm not familiar with, **_which IIUC blocks access to port 80 that ACME/cert-manager uses for the challenge ?_**

I have looked at the documentation for Korg a bit but cannot find a quick answer to the issue at hand here. I have also searched issues here and haven't found any that references this specific error message and context.

I have also tried using a ClusterIssuer instead of an Issuer in the corresponding namespace, getting the same error.

Would you be able to help me understand the issue at hand here ? Is my guess correct ? If so how to remediate it ? If not, what is happening ?

Thanks in advance.

### What did you expect to happen?

HTTP challenge correctly completed like for any other service on the cluster

### How can we reproduce it (as minimally and precisely as possible)?

- kubeadm cluster
- flannel
- nginx-ingress
- cert-manager

### Kubernetes Dashboard version

7.1.0

### Kubernetes version

1.29

**Comment by floreks** [comment]
That looks like a protocol mismatch issue (HTTP - HTTPS). Make sure you enabled HTTPS passthrough or tls termination on your ingress.

**Comment by adamency** [comment]
@floreks Thanks a lot for your answer. However I'm not sure I understand what you mean.

I am not trying to use an already existing TLS cert for the dashboard via a custom ingress, but simply to install the dashboard with the chart and have `cert-manager` automatically complete the HTTP ACME challenge to get a TLS certificate for the dashboard service, as per the documentation in the `values.yaml` file for the project. I simply applied the helm dashboard chart with the override.yml file shared above and the `Ingress` resource is entirely created by the chart, not me.

For all my other service, I have some deployment with pods serving a port e.g. 80 or 8080. Then I map the service and the ingress to the port without having done any special modification of the default `nginx-ingress` manifest and the challenge always worked.

Here's a working example with the `kuard` test app:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: kuard.<mydomain>
    http:
      paths:
      - backend:
          service:
            name: kuard
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - kuard.<mydomain>
    secretName: kuard-<mydomain>
---
apiVersion: v1
kind: Service
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  selector:
      app: kuard
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  ipFamilies:
    - IPv4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      name: kuard
      labels:
        app: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-arm64:blue
        name: kuard
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
            scheme: HTTP
```

For reference, here is the resulted Ingress resource created for the dashboard by the chart:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: kubernetes-dashboard-letsencrypt-prod
    meta.helm.sh/release-name: kubernetes-dashboard
    meta.helm.sh/release-namespace: kubernetes-dashboard
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  generation: 1
  labels:
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubernetes-dashboard
    helm.sh/chart: kubernetes-dashboard-7.1.3
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  ingressClassName: nginx
  rules:
  - host: dashboard.<mydomain>
    http:
      paths:
      - backend:
          service:
            name: kubernetes-dashboard-kong-proxy
            port:
              number: 443
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - dashboard.<mydomain>
    secretName: kubernetes-dashboard-certs
```

and the Ingress for the solver automatically created by `cert-manager`:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0,::/0
  labels:
    acme.cert-manager.io/http-domain: "1377175528"
    acme.cert-manager.io/http-token: "1107562181"
    acme.cert-manager.io/http01-solver: "true"
  name: cm-acme-http-solver-l6mmj
  namespace: kubernetes-dashboard
  ownerReferences:
  - apiVersion: acme.cert-manager.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Challenge
    name: kubernetes-dashboard-certs-1-2599902695-2430526343
spec:
  ingressClassName: nginx
  rules:
  - host: dashboard.<mydomain>
    http:
      paths:
      - backend:
          service:
            name: cm-acme-http-solver-mm5cn
            port:
              number: 8089
        path: /.well-known/acme-challenge/TCvyORbHqI6FZRfEfadnnWO5UlD5i4kQCcFrHqSYlSw
        pathType: ImplementationSpecific
```

I can see that `nginx.ingress.kubernetes.io/ssl-passthrough: "true"` is set for the Dashboard Ingress, so this should not be the issue. 

As for the point on https vs http, an http01 ACME challenge uses `http` mandatorily as it is precisely used to prove ownership of the domain so that letsencrypt then grants us a TLS cert for https. Would this be prevented by Kong ? That is why I'm afraid of.

Here is the listing of my relevant ingresses:

```
# k get ing -A
NAMESPACE              NAME                        CLASS   HOSTS                  ADDRESS    PORTS     AGE
[...]
kubernetes-dashboard   cm-acme-http-solver-l6mmj   nginx   dashboard.<mydomain>   10.0.0.4   80        3m55s
kubernetes-dashboard   kubernetes-dashboard        nginx   dashboard.<mydomain>   10.0.0.4   80, 443   4m1s
```

Couldn't Kong absorb the request to http://dashboard.<mydomain>//.well-known/acme-challenge/TCvyORbHqI6FZRfEfadnnWO5UlD5i4kQCcFrHqSYlSw and return an empty response when it should have gone to `cm-acme-http-solver-l6mmj` instead ?
