### ISSUE TITLE
Support configurable Service Type field

### ISSUE THREAD

**Issue by chunter0** [kubernetes/dashboard#8885]
### What would you like to be added?

Would it be possible to make service types configurable via helm values?

E.g:

```yaml
# WEB UI deployment configuration
web:
  serviceType: <type> # Set the Service Type for Web deployment (default: ClusterIP)
```

Helm: templates/services/web.yaml
```
{{- if eq .Values.app.mode "dashboard" }}

kind: Service
apiVersion: v1
spec:
  type: {{ .Values.web.serviceType }}
{{- end -}}
```

### Why is this needed?

Provides users more flexibility when deploying Kubernetes Dashboard components
