### ISSUE TITLE
Dashboard Helm Chart incompatible with Traefik ingress controller

### ISSUE THREAD

**Issue by andeke07** [kubernetes/dashboard#9051]
### What happened?

I am using a k3s setup and was trying to use the Helm chart to get the Kubernetes Dashboard installed.

K3S uses Traefik as its ingress controller, which, by default, will give an internal server error if trying to pass traffic to a TLS endpoint where it cannot validate the SSL certificates (and kong is using a self-signed certificate).

To get around this, one option is to create a Traefik ServersTransport resource:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: skipverify
  namespace: kubedb
spec:
  insecureSkipVerify: true
```

However you must apply annotations on the **service** for this to work:

```yaml
traefik.ingress.kubernetes.io/service.serversscheme: https
traefik.ingress.kubernetes.io/service.serverstransport: <namespace>-skipverify@kubernetescrd
```

In the Helm chart there does not seem to be a method to apply annotations to services, so this must be manually applied. Would it be possible to expose service annotations for kong to allow this to be done automatically?

### What did you expect to happen?

Traffic to flow to kong-proxy via an ingress without manual intervention

### How can we reproduce it (as minimally and precisely as possible)?

- Set up a K3S cluster (by default it will install Traefik as your ingress controller)
- Install kubernetes-dashboard Helm chart with these values:

```yaml
app:
    ingress:
      enabled: true
      hosts:
        - your.domain.tld
      ingressClassName: traefik
      issuer:
        name: letsencrypt-prod
        scope: cluster
```

### Kubernetes Dashboard version

7.4.0

### Kubernetes version

v1.28.8+k3s1

**Comment by floreks** [comment]
We do not have any control over kong chart. It is a dependency of our chart. Look into their chart and see what values can be overridden.

https://github.com/kubernetes/dashboard/blob/bac8c5fb752c118ed5aa8de2b2b323f7ec57c595/charts/kubernetes-dashboard/Chart.yaml#L46-L49

If it helps, there should also be an HTTP port exposed via the Kong service so you could try TLS termination.

**Comment by andeke07** [comment]
Thank you! That got me looking in the right direction. I found I could add:

```yaml
kong:
    proxy:
      annotations:
        traefik.ingress.kubernetes.io/service.serversscheme: https
        traefik.ingress.kubernetes.io/service.serverstransport: kubedb-skipverify@kubernetescrd
```

to my values file which has added the correct annotations to the service.
