### ISSUE TITLE
LoadBalancer service type

### ISSUE THREAD

**Issue by DaanSelen** [kubernetes/dashboard#9078]
### What would you like to be added?

If its possible to expose the dashboard, not through a terminal command but through a service like LoadBalancer without Ingress, at least outside of the cluster.

### Why is this needed?

The current information I am able to find about exposing the dashboard outside of localhost is through vague additions with extra servers, most of which result in a HTTP (200) unable to parse api/csrf token. Which is unwanted.

**Comment by yybht155** [comment]
I encountered the same problem

**Comment by bogd** [comment]
I came here after banging my head against the walls for an hour, trying to figure out the `api/csrftoken` error.

In my case, it was because I was exposing (via a NodePort) the `dashboard-web` service, when instead the exposed service should be `dashboard-kong-proxy`

In your case, setting the `dashboard-kong-proxy` as `LoadBalancer` should work as well.

Issue #9066 was the one that got me on the right track.

**Comment by floreks** [comment]
The above response is correct. Closing.

/close

**Comment by Aleksey-Kalinin** [comment]
I have Istio and Helm and I solved this problem as follows

**Chart.yaml**
```
apiVersion: v2
name: kubernetes-dashboard
dependencies:
  - name: kubernetes-dashboard
    version: 7.5.0
    repository: https://kubernetes.github.io/dashboard/
```

**values.yaml**
``` 
kubernetes-dashboard:
  app:
    ingress:
      enabled: false

  kong: 
    proxy:
      type: ClusterIP
      http:
        enabled: true

  # https://github.com/kubernetes/dashboard/issues/8829
  api:
    containers:
      args:
        - '--disable-csrf-protection=true'
```

**templates/access-control.yaml**
```
apiVersion: v1
kind: ServiceAccount
metadata:  
  name: admin-user  
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:  
  name: admin-user
roleRef:  
  apiGroup: rbac.authorization.k8s.io  
  kind: ClusterRole  
  name: cluster-admin
subjects:
  - kind: ServiceAccount  
    name: admin-user  
    namespace: monitoring
---
apiVersion: v1
kind: Secret
metadata:  
  name: admin-user  
  namespace: monitoring
  annotations:    
    kubernetes.io/service-account.name: "admin-user"
type: kubernetes.io/service-account-token
```

**virtualservice.yaml**
``` 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kubernetes-dashboard-public
  labels:
    app: kubernetes-dashboard
spec:
  gateways:
    - istio-system/feature-ingressgateway
  hosts:
  - dashboard.my-company.com                                              # my  web domain
  http:
    - name: route-kubernetes-dashboard-main
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: kubernetes-dashboard-kong-proxy
            port:
              number: 80
          headers:
            request:
              set:
                Authorization: Bearer eyJhbGciOiJSUz...                           # copy output from kubectl get secret admin-user -n monitoring -o jsonpath={".data.token"} | base64 -d
```

.... **AND DISABLE CACHE IN CHROME to clear garbage from previous failed attempts** 
https://developer.chrome.com/docs/devtools/network/reference?utm_source=devtools&hl=en#disable-cache

Without cleaning cache it is not working in my machine (((
