### ISSUE TITLE
Kubernetes-Dashboard on a sub-path with Istio

### ISSUE THREAD

**Issue by sivanagireddyb** [kubernetes/dashboard#9165]
### What happened?

Getting below error while accessing dashboard.
`Unknown error (200): Http failure during parsing for http://example.com/k8s-dashboard/api/v1/csrftoken/login
`

### What did you expect to happen?

Able to access Dashboard with token.

### How can we reproduce it (as minimally and precisely as possible)?

Install Helm 7.5.0 on EKS 1.28 with below values. And create Istio virtual service.
```
app:
  settings:
    global:
      clusterName: ${cluster_name}
  ingress:
    enabled: false
metricsScraper:
  enabled: true
kong:
  enabled: false
cert-manager:
  enabled: false
  installCRDs: false
```
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kubernetes-dashboard
  namespace: ingress-routes
spec:
  hosts:
  - "example.com"
  gateways:
  - dev-app-gateway
  http:
  - match:
    - uri:
        prefix: /k8s-dashboard/
    rewrite:
      uri: /
    route:
    - destination:
        host: kubernetes-dashboard-web.kubernetes-dashboard.svc.cluster.local
        port:
          number: 8000
```

### Anything else we need to know?

I am using ssl at Istio Gateway level so i want to terminate at ssl at Istio.
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: "dev-app-gateway"
  namespace: ingress-routes
spec:
  selector:
    istio: custom-gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - 'example.com'
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      credentialName: "dev-tls-cert"
      mode: SIMPLE
    hosts:
    - 'example.com''
```

### What browsers are you seeing the problem on?

Microsoft Edge

### Kubernetes Dashboard version

7.5.0

### Kubernetes version

1.28

**Comment by sivanagireddyb** [comment]
It started working for me after creating Virtual Service like below. It would have been good if document has more information about ingress/accessing dashboard.

**Note**: I am using common domain for app & dashboard so used path base routing with `/kubedashboard`. If you have seperate domain it can beremoved.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kubernetes-dashboard
  namespace: ingress-routes
spec:
  hosts:
  - "example.com"
  gateways:
  - dev-app-gateway
  http:
  - match:
    - uri:
        exact: /kubedashboard/api/v1/login
    rewrite:
      uri: /api/v1/login  
    route:
    - destination:
        host: kubernetes-dashboard-auth.kubernetes-dashboard.svc.cluster.local
        port:
          number: 8000  
  - match:
    - uri:
        exact:  /kubedashboard/api/v1/csrftoken/login
    rewrite:
      uri: /api/v1/csrftoken/login      
    route:
    - destination:
        host: kubernetes-dashboard-auth.kubernetes-dashboard.svc.cluster.local
        port:
          number: 8000           
  - match:
    - uri:
        exact: /kubedashboard/api/v1/me
    rewrite:
      uri: /api/v1/me
    route:
    - destination:
        host: kubernetes-dashboard-auth.kubernetes-dashboard.svc.cluster.local
        port:
          number: 8000
  - match:
    - uri:
        prefix: /kubedashboard/api
    rewrite:
      uri: /api  
    route:
    - destination:
        host: kubernetes-dashboard-api.kubernetes-dashboard.svc.cluster.local
        port:
          number: 8000
  - match:
    - uri:
        exact: /kubedashboard/metrics
    rewrite:
      uri: /metrics  
    route:
    - destination:
        host: kubernetes-dashboard-api.kubernetes-dashboard.svc.cluster.local
        port:
          number: 8000
  - match:
    - uri:
        prefix: /kubedashboard/
    - uri:
        exact: /kubedashboard
    rewrite:
      uri: /  
    route:
    - destination:
        host: kubernetes-dashboard-web.kubernetes-dashboard.svc.cluster.local
        port:
          number: 8000

```
