### ISSUE TITLE
configmap "kong-dbless-config" not found

### ISSUE THREAD

**Issue by schlichtanders** [kubernetes/dashboard#9263]
### What happened?

I created kubernetes dashboard by first collecting the yaml via
```bash
helm template kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard -n kubernetes-dashboard -f values.yaml --version "7.5.0" > helm.yaml
```
and then applying it, however it fails with an error on the kong dashboard
```
configmap "kong-dbless-config" not found
```
which is due to the kong deployment and pod being run inside namespace `kubernetes-dashboard`, but the config being deployed to default namespace.
https://github.com/kubernetes/dashboard/blob/e0e925a9a91e7a16d1dde0387805a7c4bea7dbcb/charts/kubernetes-dashboard/templates/config/gateway.yaml#L22

Looking through the generated yaml, it seems many parts of kubernetes dashboard do not respect the helm namespace argument, which confuses me, as this is such a stable package.
Anyone who can help finding out what is going on and how to fix it?

### What did you expect to happen?

I expect everything to be correctly deployed inside the namespace `kubernetes-dashboard`

### How can we reproduce it (as minimally and precisely as possible)?

Create `helm.yaml` by running
```bash
helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/

helm template kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard -n kubernetes-dashboard -f values.yaml --version "7.5.0" > helm.yaml
```
👆 actually you can stop here and investigate the `helm.yaml` to see that not everything is deployed inside kubernetes-dashboard

- - - - - - - - - - - - -

create `namespace.yaml` with the following content
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard
```

create `kustomization.yaml` with the following content
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- helm.yaml

sortOptions:
  order: fifo
```

finally, run `kubectl apply -k .`

### Kubernetes Dashboard version

7.5.0

### Kubernetes version

Client Version: v1.30.2 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.29.6+k3s2
