### ISSUE TITLE
services \"kubernetes-dashboard\" not found

### ISSUE THREAD

**Issue by schlichtanders** [kubernetes/dashboard#9264]
### What happened?

I installed kubernetes-dashboard via the following yaml

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard

---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  repo: https://kubernetes.github.io/dashboard/
  chart: kubernetes-dashboard
  version: 7.5.0
  targetNamespace: kubernetes-dashboard
  valuesContent: |-
    app:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
```

however when opening `http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/` I get the following response

```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "services \"kubernetes-dashboard\" not found",
  "reason": "NotFound",
  "details": {
    "name": "kubernetes-dashboard",
    "kind": "services"
  },
  "code": 404
}
```

### What did you expect to happen?

I'd like to to see the kubernetes dashboard, at least the login screen

### How can we reproduce it (as minimally and precisely as possible)?
on a k3s kubernetes (use e.g. k3d for a local k3s cluster), or kubernetes with helm-controller installed `kubectl apply` the following
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard

---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  repo: https://kubernetes.github.io/dashboard/
  chart: kubernetes-dashboard
  version: 7.5.0
  targetNamespace: kubernetes-dashboard
  valuesContent: |-
    app:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
```

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

7.5.0

### Kubernetes version

Client Version: v1.30.2 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.29.6+k3s2
