### ISSUE TITLE
Dashboard pod status not reported correctly for pods using native sidecar containers

### ISSUE THREAD

**Issue by brentmjohnson** [kubernetes/dashboard#9299]
### What happened?

Pod status in the dashboard showing "Init: x/y" instead of "Running":

![image](https://github.com/user-attachments/assets/94c3039b-c222-4244-9e53-fbc8291fd26a)
![image](https://github.com/user-attachments/assets/e93f0f9d-cbaa-4bbb-aa09-b69085bb8224)

Correct pod status shown in kubectl cli:

![image](https://github.com/user-attachments/assets/6fe33fe3-9ca8-4fad-9fa7-4573e6fd0bc5)

### What did you expect to happen?

Pod status should show "Running" if all containers (including native sidecar containers) are ready.

### How can we reproduce it (as minimally and precisely as possible)?

1. Use the example here: https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/#sidecar-example
2. Observe the "Init: x/y" status in the dashboard
3. Replace the deployment definition with the below - converting to a standard init container
4. Observe the "Running" status in the dashboard

```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: alpine:latest
          command: ['sh', '-c', 'while true; do echo "logging" >> /opt/logs.txt; sleep 1; done']
          volumeMounts:
            - name: data
              mountPath: /opt
      initContainers:
        - name: logshipper
          image: alpine:latest
          # restartPolicy: Always
          # command: ['sh', '-c', 'tail -F /opt/logs.txt']
          command: ['sh', '-c', 'sleep 1']
          volumeMounts:
            - name: data
              mountPath: /opt
      volumes:
        - name: data
          emptyDir: {}
```

### What browsers are you seeing the problem on?

Microsoft Edge

### Kubernetes Dashboard version

helm.sh/chart: kubernetes-dashboard-7.5.0

### Kubernetes version

Client Version: v1.29.4 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.29.3
