### ISSUE TITLE
Error no Route matched with those values

### ISSUE THREAD

**Issue by whizyrel** [kubernetes/dashboard#9476]
### What happened?

I installed kubernetes dashboard using helm from here https://github.com/kubernetes/dashboard/blob/master/README.md and passed in a few values set in a bid to expose kubernetes dashboard using ingress.

When I visit the domain, I get the error 
```
Error

no Route matched with those values.

request_id: ...
```

```
...
kong:
  ingressController:
    enabled: true
  proxy:
    type: ClusterIP
    http:
      enabled: true
app:
  ingress:
    enabled: true
    hosts:
    - domain-name
    ingressClassName: nginx
    useDefaultIngressClass: false
    useDefaultAnnotations: true
    pathType: ImplementationSpecific
    path: /
    issuer:
      name: ...
      scope: cluster
    tls:
      enabled: true
...
```

### What did you expect to happen?

Kubernetes Dashboard should be accessible on the domain specififed.

### How can we reproduce it (as minimally and precisely as possible)?

# Add kubernetes-dashboard repository
helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
# Deploy a Helm Release named "kubernetes-dashboard" using the kubernetes-dashboard chart
helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard 

### Anything else we need to know?

I set up kubernetes in a raw vm with
- Metallb
- Flannel
- Ingress
- CertManager
- Helm

Other services and ingress work just fine

### What browsers are you seeing the problem on?

Chrome, Firefox

### Kubernetes Dashboard version

7.6.1

### Kubernetes version

1.31.0
