### ISSUE TITLE
Specifying additional labels doesn't work 

### ISSUE THREAD

**Issue by Moglum** [kubernetes/dashboard#9503]
### What happened?

When you specify custom labels using `app.labels` the helm chart produces invalid YAML and can't be used.

### What did you expect to happen?

Custom labels would be correctly appended after the built-in ones.

### How can we reproduce it (as minimally and precisely as possible)?

Specifying any custom label will break helm templating.

```
> helm template kubernetes-dashboard/kubernetes-dashboard --version 7.7.0 --set app.labels.foo=bar
Error: YAML parse error on kubernetes-dashboard/templates/config/gateway.yaml: error converting YAML to JSON: yaml: line 22: mapping values are not allowed in this context

Use --debug flag to render out invalid YAML
```

With `--debug` enabled, the resulting YAML shows the problem - missing newline
```yaml
metadata:
  labels:
    helm.sh/chart: kubernetes-dashboard-7.7.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubernetes-dashboardfoo: bar
```

### Anything else we need to know?

The bug was introduced here https://github.com/kubernetes/dashboard/pull/9490/files#diff-92db08aee8439a4e118fa16cbdeaebdc56a02bea105208db93f365a603645434R56

I will submit a PR to fix it shortly.

### Kubernetes Dashboard version

7.7.0

### Kubernetes version

irrelevant
