### ISSUE TITLE
Service state incorrectly shown as "Pending" for NodePort type services

### ISSUE THREAD

**Issue by ApsOps** [kubernetes/dashboard#955]
#### Issue details
Looking at the code [here](https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/servicelist/servicecardlist_component.js#L51-L55). Why does it consider a `LoadBalancer` or `NodePort` type service Pending if `externalEndpoints` is missing? As per the [docs](http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_servicespec), it’s not a “required” value.

##### Environment

Kubernetes cluster running on AWS nodes. Dashboard running as a `ReplicationController` and exposed as a cluster service.

```
Dashboard version: v1.1.0
Kubernetes version: v1.2.4
Operating system: Ubuntu 14.04.3 LTS
```

##### Steps to reproduce

* Create a service of `type=NodePort`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    run: test
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    nodePort: 31182
  selector:
    run: test
```
* Visit the `#/service` page.

##### Observed result

Service is shown as being in `pending state`.

<img width="94" alt="screen shot 2016-06-26 at 8 57 34 pm" src="https://cloud.githubusercontent.com/assets/2363074/16363198/aed4909c-3be0-11e6-8c3f-b05e41cb257c.png">
<img width="216" alt="screen shot 2016-06-26 at 8 57 49 pm" src="https://cloud.githubusercontent.com/assets/2363074/16363199/af23739c-3be0-11e6-92b7-ba39f0155630.png">

##### Expected result

Service should not be shown as pending.

<img width="86" alt="screen shot 2016-06-26 at 9 00 06 pm" src="https://cloud.githubusercontent.com/assets/2363074/16363208/0fd03e78-3be1-11e6-8a90-4b4e424e5939.png">
