### ISSUE TITLE
Explicit namespace indication for resources created by Helm

### ISSUE THREAD

**Issue by YoungJinJung** [kubernetes/dashboard#9600]
### What would you like to be added?

I want to add a feature to explicitly specify a namesapce for objects created by specifying a namespace, such as Deployments or service Objects created with helm.

### Why is this needed?

I created it locally by adding a namespace to the Helm template as in the command below.
`helm template . --namespace test`

As a result, I found that the generated Deployment or service objects do not display an explicit namespace. A representative example is the auth deployment.yaml below.
```
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    helm.sh/chart: kubernetes-dashboard-7.9.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubernetes-dashboard
    app.kubernetes.io/name: kubernetes-dashboard-auth
    app.kubernetes.io/version: 1.10.0
    app.kubernetes.io/component: auth
  annotations:

  name: release-name-kubernetes-dashboard-auth
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/part-of: kubernetes-dashboard
      app.kubernetes.io/name: kubernetes-dashboard-auth
  template:
    metadata:
      labels:
        helm.sh/chart: kubernetes-dashboard-7.9.0
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kubernetes-dashboard
        app.kubernetes.io/name: kubernetes-dashboard-auth
        app.kubernetes.io/version: 1.2.1
        app.kubernetes.io/component: auth
      annotations:
        checksum/config: bd7b4b3ecc51bf75f459e018a70fa02ca3344248947f59f5b75ccbd5db8f87d5
    spec:
      containers:
        - name: kubernetes-dashboard-auth
          image: "docker.io/kubernetesui/dashboard-auth:1.2.1"
          imagePullPolicy: IfNotPresent
          args:

          env:
            - name: CSRF_KEY
              valueFrom:
                secretKeyRef:
                  name: release-name-kubernetes-dashboard-csrf
                  key: private.key
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
                  divisor: "1"
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
                  divisor: "1"
          ports:

            - containerPort: 8000
              name: auth
              protocol: TCP
          volumeMounts:

            - mountPath: /tmp
              name: tmp-volume
          securityContext:

            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 2001
            runAsUser: 1001
          resources:

            limits:
              cpu: 250m
              memory: 400Mi
            requests:
              cpu: 100m
              memory: 200Mi

      automountServiceAccountToken: true
      securityContext:

        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:

        - emptyDir: {}
          name: tmp-volume
  ```
When install helm chart, Helm Install or upgrade command to deploy selected namespace. However, when validating the value, it should be added because the value output through the template is thought to be incorrect.
