### ISSUE TITLE
Plain HTTP Request was sent to HTTP port

### ISSUE THREAD

**Issue by EvodiDunn** [kubernetes/dashboard#9601]
### What happened?

I tried to setup the Kubernetes Dashboard chart using the Default values file with the default values file having the below changes.
![Screenshot 2024-10-28 at 3 03 23 PM](https://github.com/user-attachments/assets/622974f7-2d95-4187-b9c9-d61e75118e5a)

The main things of note here, the certificate required is created as a TLS secret and works for other ingress' with no issue. and likewise the nginx-internal classname works perfectly for other ingress'. There are no other changes to the values file, However when i run helm install using this file it successfully creates everything. But when navigating to the URL https://k8s.evodian.au i get a 400 Bad Request with the error The plain HTTP request was sent to HTTPS port.
<img width="1510" alt="Screenshot 2024-10-28 at 3 03 07 PM" src="https://github.com/user-attachments/assets/7e90ac96-4787-4e2c-8eaf-0de19be8b783">

I can see that the connection is secured and i've specified https in the browser, so not sure why this would be attempting to use HTTP? Out of interest i also tried swapping Kong from ClusterIP to NodePort and can access the dashboard successfully over NodePort, so this appears to be a communication issue between Ingress and service?
<img width="317" alt="Screenshot 2024-10-28 at 3 09 19 PM" src="https://github.com/user-attachments/assets/91b98a1d-6a69-4a9c-90aa-d4d161d254e6">

### What did you expect to happen?

I expected to go to https://k8s.evodian.au and land on the authentication page for kubernetes dashboard.

### How can we reproduce it (as minimally and precisely as possible)?

To reproduce, take the current values file from the repo and set

1. Ingress.enabled: true
2. ingress.hosts : your host name
3. ingress.issuer.scope: disabled
4. ingress.tls.enabled: true
5. ingress.tls.secretname: certificate secret

### What browsers are you seeing the problem on?

Chrome, Firefox

### Kubernetes Dashboard version

7.9.0

### Kubernetes version

v1.28.5

**Comment by dvdlevanon** [comment]
Getting similar results after upgrade to 7.x

**Comment by perrynaise** [comment]
Adding the ssl-services annotation to my ingress fixed it for me:

`kubectl annotate ingress kubernetes-dashboard -n kubernetes-dashboard nginx.org/ssl-services='kubernetes-dashboard-kong-proxy' --overwrite`

You can also do it from the "values.yaml" file during Helm deployment.  This is mine currently:

```
app:
  ingress:
    enabled: true
    hosts:
      - localhost
      - dashboard.mydomain.com
    ingressClassName: nginx
    issuer:
      name: selfsigned-issuer
      scope: cluster
    tls:
      enabled: true
      secretName: tls-mydomain.com-dashboard
    annotations:
      nginx.org/ssl-services: "kubernetes-dashboard-kong-proxy"
```
