### ISSUE TITLE
Helm Chart Uses Kong TLS Port Despite TLS Disabled in Kubernetes Dashboard Ingress

### ISSUE THREAD

**Issue by hamadodene** [kubernetes/dashboard#9861]
### What happened?

When I enable the Kong HTTP proxy:

```
kong:  
  proxy:
      type: ClusterIP
      http:
        enabled: true
```

and disable SSL for the Kubernetes Dashboard, the Helm chart still uses the Kong TLS service port instead of the HTTP port:
```
name: {{ template "kong.fullname" (index $.Subcharts "kong") }}-proxy
port:
  number: {{ $.Values.kong.proxy.tls.servicePort }}
```

Even though TLS is disabled, the HTTP port is not being used. For example, with the following configuration:

```
app:
  mode: 'dashboard'
  ingress:
    enabled: true
    hosts:
      - my-hostname.example.com
    ingressClassName: traefik
    useDefaultAnnotations: false
    tls:
      enabled: false
    annotations:
      kubernetes.io/ingress.class: "traefik"
```

### What did you expect to happen?

I expect the Kong HTTP port to be used when TLS is disabled on the ingress side. However, the chart still references the TLS service port.

### How can we reproduce it (as minimally and precisely as possible)?

I simply install kubernetes-dashboard via helm using helmfile:

helmfile.yaml:
```yaml
repositories:
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/

releases:
- name:  kubernetes-dashboard
  namespace:  kubernetes-dashboard
  chart: kubernetes-dashboard/kubernetes-dashboard
  version: 7.10.1
  installed: true
  createNamespace: true
  disableValidation: true
  values:
    - values.yaml.gotmpl
```

values.yaml.gotmpl

```
app:
  mode: 'dashboard'
  ingress:
    enabled: true
    hosts:
      - my-hostname.example.com
    ingressClassName: traefik
    useDefaultAnnotations: false
    tls:
      enabled: false
    annotations:
        kubernetes.io/ingress.class: "traefik"

kong:
  proxy:
    http:
      enabled: true
```

### Kubernetes Dashboard version

helm version 7.10.1

### Kubernetes version

v1.30.5
